Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/Jiz1028/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (set args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/conf/change_args.py '{"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","connect_switch_sut_pf":"ens2f0","pf1":"ens2f0","pf1_ipv6":"fe80::b696:91ff:fe9c:f7a4","os":"rehat"},"dhcp":{"ipv4":"192.168.10.11","ipv6":"fe80::b696:91ff:fea5:9b45"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 16 items / 15 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-02-16 11:46:43 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-02-16 11:46:43 - test_network_sriov_stress.py - [line:31] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-02-16 11:46:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-02-16 11:46:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-02-16 11:46:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-02-16 11:46:43 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-02-16 11:46:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-02-16 11:46:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-02-16 11:46:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-02-16 11:46:43 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-02-16 11:46:46 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-16 11:46:47 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-16 11:46:52 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-16 11:46:52 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-16 11:46:52 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-16 11:46:58 - sshInstance.py - [line:92] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Feb 16 10:16:10 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-16 11:47:01 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-16 11:47:04 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 11:47:04 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:47:09 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-16 11:47:12 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-16 11:47:12 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-16 11:47:17 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-16 11:47:20 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-16 11:47:20 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-16 11:47:25 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-16 11:47:28 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-16 11:47:28 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:47:33 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 11:47:36 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-16 11:47:37 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:47:42 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 11:47:42 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 11:47:45 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 11:47:45 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-16 11:47:50 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-16 11:47:53 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-16 11:47:53 - sshInstance.py - [line:48] - root - INFO - no

2022-02-16 11:47:58 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? no

2022-02-16 11:47:58 - test_network_sriov_stress.py - [line:186] - root - INFO - virsh net-start default
2022-02-16 11:48:01 - sshInstance.py - [line:44] - root - INFO - virsh net-start default
2022-02-16 11:48:01 - sshInstance.py - [line:48] - root - INFO - Network default started


2022-02-16 11:48:06 - test_network_sriov_stress.py - [line:190] - root - INFO - Successfully started network default.
2022-02-16 11:48:10 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:13746): [1;33mWARNING[0m **: [34m11:57:32.963[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 11:48:12 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 11:48:15 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-16 11:48:19 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13842): [1;33mWARNING[0m **: [34m11:57:41.798[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 11:48:21 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 11:48:24 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-16 11:48:27 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-16 11:48:27 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:48:32 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest1
2022-02-16 11:49:35 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-16 11:49:35 - sshInstance.py - [line:48] - root - INFO - 192.168.122.138/24

2022-02-16 11:49:40 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.138/24

2022-02-16 11:49:43 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 11:49:43 - sshInstance.py - [line:48] - root - INFO - 192.168.122.155/24

2022-02-16 11:49:48 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.155/24

2022-02-16 11:49:48 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.138
2022-02-16 11:49:48 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.155
2022-02-16 11:49:52 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.496 ms
2022-02-16 11:49:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.264 ms
2022-02-16 11:49:54 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.279 ms
2022-02-16 11:49:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.355 ms
2022-02-16 11:49:56 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.461 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4131ms
rtt min/avg/max/mdev = 0.264/0.371/0.496/0.093 ms
[root@WW25ICX2 ~]# 
2022-02-16 11:50:05 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
The authenticity of host '192.168.122.138 (192.168.122.138)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-02-16 11:50:14 - sshInstance.py - [line:92] - root - INFO - yes
Warning: Permanently added '192.168.122.138' (ECDSA) to the list of known hosts.
root@192.168.122.138's password: 
2022-02-16 11:50:23 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 10:59:43 PM EST
  System load:  0.0                Processes:             138
  Usage of /:   40.5% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 18:46:48 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 11:50:32 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 11:50:38 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 11:50:44 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 11:50:49 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 11:50:55 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-16 11:50:58 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 11:51:04 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 11:51:14 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-16 11:51:23 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 11:51:32 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 11:51:41 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 684 (684.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 11:51:50 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 11:51:57 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.155
PING 192.168.122.155 (192.168.122.155) 56(84) bytes of data.
64 bytes from 192.168.122.155: icmp_seq=1 ttl=64 time=0.492 ms
2022-02-16 11:51:58 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=2 ttl=64 time=0.474 ms
2022-02-16 11:51:59 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=3 ttl=64 time=0.478 ms
2022-02-16 11:52:00 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=4 ttl=64 time=0.254 ms
2022-02-16 11:52:01 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=5 ttl=64 time=0.470 ms

--- 192.168.122.155 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4112ms
rtt min/avg/max/mdev = 0.254/0.433/0.492/0.092 ms
[root@WW25ICX2 ~]# 
2022-02-16 11:52:10 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.155
The authenticity of host '192.168.122.155 (192.168.122.155)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-02-16 11:52:19 - sshInstance.py - [line:92] - root - INFO - yes
Warning: Permanently added '192.168.122.155' (ECDSA) to the list of known hosts.
root@192.168.122.155's password: 
2022-02-16 11:52:28 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:01:48 PM EST
  System load:  0.0                Processes:             141
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.155
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 18:44:51 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 11:52:37 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 11:52:43 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 11:52:49 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 11:52:54 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 11:53:00 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-16 11:53:03 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 11:53:09 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 11:53:19 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-16 11:53:28 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 11:53:37 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 11:53:47 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 11:53:56 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.155 closed.
[root@WW25ICX2 ~]# 
2022-02-16 11:53:59 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-16 11:54:03 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.514 ms
2022-02-16 11:54:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.193 ms
2022-02-16 11:54:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.199 ms
2022-02-16 11:54:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.125 ms
2022-02-16 11:54:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.214 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4093ms
rtt min/avg/max/mdev = 0.125/0.249/0.514/0.135 ms
[root@WW25ICX2 ~]# 
2022-02-16 11:54:14 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.545 ms
2022-02-16 11:54:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.263 ms
2022-02-16 11:54:16 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.205 ms
2022-02-16 11:54:17 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.207 ms
2022-02-16 11:54:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.196 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.196/0.283/0.545/0.133 ms
[root@WW25ICX2 ~]# 
2022-02-16 11:54:21 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 11:54:25 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.287 ms
2022-02-16 11:54:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.459 ms
2022-02-16 11:54:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.268 ms
2022-02-16 11:54:28 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.480 ms
2022-02-16 11:54:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.466 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4082ms
rtt min/avg/max/mdev = 0.268/0.392/0.480/0.093 ms
[root@WW25ICX2 ~]# 
2022-02-16 11:54:38 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 11:54:47 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:04:06 PM EST
  System load:  0.0                Processes:             132
  Usage of /:   40.5% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 22:59:43 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 11:54:54 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.546 ms
2022-02-16 11:54:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.331 ms
2022-02-16 11:54:56 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.160 ms
2022-02-16 11:54:57 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.112 ms
2022-02-16 11:54:58 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.112 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4089ms
rtt min/avg/max/mdev = 0.112/0.252/0.546/0.167 ms
root@localhost:~# 
2022-02-16 11:55:38 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 11:55:41 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 11:55:45 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.251 ms
2022-02-16 11:55:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.225 ms
2022-02-16 11:55:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.234 ms
2022-02-16 11:55:48 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.315 ms
2022-02-16 11:55:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.218 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4120ms
rtt min/avg/max/mdev = 0.218/0.248/0.315/0.039 ms
[root@WW25ICX2 ~]# 
2022-02-16 11:55:55 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 11:55:57 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:56:02 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-16 11:56:05 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-16 11:56:05 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-16 11:56:10 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-16 11:56:13 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-16 11:56:13 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-16 11:56:18 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-16 11:56:21 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-16 11:56:21 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-16 11:56:26 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-16 11:56:29 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-16 11:56:29 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-16 11:56:34 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-16 11:56:34 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2022-02-16 11:56:37 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-16 11:56:38 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-16 11:56:43 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-16 11:56:43 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-16 11:56:43 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-16 11:56:49 - sshInstance.py - [line:92] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-16 11:56:52 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-16 11:56:55 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 11:56:55 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:57:00 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-16 11:57:03 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-16 11:57:03 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-16 11:57:08 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-16 11:57:11 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-16 11:57:11 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-16 11:57:16 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-16 11:57:19 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-16 11:57:19 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:57:25 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 11:57:28 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-16 11:57:28 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:57:33 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 11:57:33 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 11:57:36 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 11:57:36 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-16 11:57:41 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-16 11:57:44 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-16 11:57:44 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-16 11:57:49 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-16 11:57:53 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14930): [1;33mWARNING[0m **: [34m12:07:15.965[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 11:57:56 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14930): [1;33mWARNING[0m **: [34m12:07:15.965[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 11:57:56 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-16 11:58:00 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14975): [1;33mWARNING[0m **: [34m12:07:23.026[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 11:58:02 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 11:58:05 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-16 11:58:09 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:15032): [1;33mWARNING[0m **: [34m12:07:31.931[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 11:58:12 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:15032): [1;33mWARNING[0m **: [34m12:07:31.931[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 11:58:12 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-16 11:58:16 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:15089): [1;33mWARNING[0m **: [34m12:07:39.000[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 11:58:18 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 11:58:21 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-16 11:58:24 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-16 11:58:24 - sshInstance.py - [line:48] - root - INFO - 192.168.122.138/24

2022-02-16 11:58:29 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.138/24

2022-02-16 11:58:32 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 11:58:32 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 11:58:37 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest2
2022-02-16 11:59:40 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 11:59:40 - sshInstance.py - [line:48] - root - INFO - 192.168.122.155/24

2022-02-16 11:59:45 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.155/24

2022-02-16 11:59:45 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.138
2022-02-16 11:59:45 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.155
2022-02-16 11:59:49 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=1.68 ms
2022-02-16 11:59:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.480 ms
2022-02-16 11:59:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.337 ms
2022-02-16 11:59:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.317 ms
2022-02-16 11:59:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.478 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.317/0.657/1.677/0.515 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:00:02 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 12:00:11 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:09:31 PM EST
  System load:  0.0                Processes:             137
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:04:07 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:00:20 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 12:00:26 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 12:00:32 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 12:00:37 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 12:00:43 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-16 12:00:46 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 12:00:52 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 12:01:02 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-16 12:01:11 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 12:01:21 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 12:01:30 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 12:01:39 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:01:46 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.155
PING 192.168.122.155 (192.168.122.155) 56(84) bytes of data.
64 bytes from 192.168.122.155: icmp_seq=1 ttl=64 time=0.319 ms
2022-02-16 12:01:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=2 ttl=64 time=0.326 ms
2022-02-16 12:01:48 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=3 ttl=64 time=0.488 ms
2022-02-16 12:01:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=4 ttl=64 time=0.478 ms
2022-02-16 12:01:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=5 ttl=64 time=0.473 ms

--- 192.168.122.155 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4128ms
rtt min/avg/max/mdev = 0.319/0.416/0.488/0.081 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:01:59 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.155
root@192.168.122.155's password: 
2022-02-16 12:02:08 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:11:27 PM EST
  System load:  0.0                Processes:             138
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.155
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:01:48 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:02:17 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 12:02:23 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 12:02:29 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 12:02:34 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 12:02:40 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-16 12:02:43 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 12:02:49 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 12:02:59 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-16 12:03:08 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 12:03:17 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 12:03:26 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 12:03:35 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.155 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:03:38 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-16 12:03:42 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.359 ms
2022-02-16 12:03:43 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.220 ms
2022-02-16 12:03:44 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.267 ms
2022-02-16 12:03:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.281 ms
2022-02-16 12:03:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.206 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4093ms
rtt min/avg/max/mdev = 0.206/0.266/0.359/0.056 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:03:53 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.875 ms
2022-02-16 12:03:54 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.277 ms
2022-02-16 12:03:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.245 ms
2022-02-16 12:03:56 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.205 ms
2022-02-16 12:03:57 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.226 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.205/0.365/0.875/0.256 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:04:00 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 12:04:04 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.288 ms
2022-02-16 12:04:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.350 ms
2022-02-16 12:04:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.310 ms
2022-02-16 12:04:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.359 ms
2022-02-16 12:04:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.201 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.201/0.301/0.359/0.059 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:04:17 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 12:04:26 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:13:45 PM EST
  System load:  0.0                Processes:             126
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:09:32 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:04:33 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.412 ms
2022-02-16 12:04:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.239 ms
2022-02-16 12:04:35 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.118 ms
2022-02-16 12:04:36 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.205 ms
2022-02-16 12:04:37 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.204 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.118/0.235/0.412/0.096 ms
root@localhost:~# 
2022-02-16 12:05:17 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:05:20 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 12:05:24 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.296 ms
2022-02-16 12:05:25 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.323 ms
2022-02-16 12:05:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.266 ms
2022-02-16 12:05:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.223 ms
2022-02-16 12:05:28 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.264 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4117ms
rtt min/avg/max/mdev = 0.223/0.274/0.323/0.036 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:05:34 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 12:05:36 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:05:41 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-16 12:05:44 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-16 12:05:44 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-16 12:05:49 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-16 12:05:52 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-16 12:05:52 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-16 12:05:57 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-16 12:06:00 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-16 12:06:00 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-16 12:06:05 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-16 12:06:08 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-16 12:06:08 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-16 12:06:13 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-16 12:06:13 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 3 time when VF is Assigned VM guest.*************************************************************


2022-02-16 12:06:16 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-16 12:06:17 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-16 12:06:22 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-16 12:06:22 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-16 12:06:22 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-16 12:06:28 - sshInstance.py - [line:92] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-16 12:06:31 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-16 12:06:34 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 12:06:34 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:06:39 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-16 12:06:42 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-16 12:06:42 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-16 12:06:47 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-16 12:06:50 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-16 12:06:50 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-16 12:06:55 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-16 12:06:58 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-16 12:06:59 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:07:04 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 12:07:07 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-16 12:07:07 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:07:12 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 12:07:12 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 12:07:15 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 12:07:15 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-16 12:07:20 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-16 12:07:23 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-16 12:07:23 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-16 12:07:28 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-16 12:07:32 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:15996): [1;33mWARNING[0m **: [34m12:16:55.052[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:07:35 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:15996): [1;33mWARNING[0m **: [34m12:16:55.052[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:07:35 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-16 12:07:39 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:16037): [1;33mWARNING[0m **: [34m12:17:02.042[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 12:07:41 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 12:07:44 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-16 12:07:48 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:16092): [1;33mWARNING[0m **: [34m12:17:11.086[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:07:51 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:16092): [1;33mWARNING[0m **: [34m12:17:11.086[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:07:51 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-16 12:07:55 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:16135): [1;33mWARNING[0m **: [34m12:17:18.120[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 12:07:57 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 12:08:00 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-16 12:08:03 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:08:03 - sshInstance.py - [line:48] - root - INFO - 192.168.122.138/24

2022-02-16 12:08:08 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.138/24

2022-02-16 12:08:11 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:08:11 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:08:16 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest2
2022-02-16 12:09:20 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:09:20 - sshInstance.py - [line:48] - root - INFO - 192.168.122.155/24

2022-02-16 12:09:25 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.155/24

2022-02-16 12:09:25 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.138
2022-02-16 12:09:25 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.155
2022-02-16 12:09:29 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.311 ms
2022-02-16 12:09:30 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.219 ms
2022-02-16 12:09:31 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.324 ms
2022-02-16 12:09:32 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.451 ms
2022-02-16 12:09:33 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.352 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4129ms
rtt min/avg/max/mdev = 0.219/0.331/0.451/0.076 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:09:42 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 12:09:51 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:19:10 PM EST
  System load:  0.0                Processes:             139
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:13:46 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:10:00 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 12:10:06 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 12:10:12 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 12:10:17 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 12:10:23 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-16 12:10:26 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 12:10:32 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 12:10:42 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-16 12:10:51 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 12:11:00 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 12:11:09 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 684 (684.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 12:11:18 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:11:25 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.155
PING 192.168.122.155 (192.168.122.155) 56(84) bytes of data.
64 bytes from 192.168.122.155: icmp_seq=1 ttl=64 time=0.466 ms
2022-02-16 12:11:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=2 ttl=64 time=0.504 ms
2022-02-16 12:11:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=3 ttl=64 time=0.375 ms
2022-02-16 12:11:28 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=4 ttl=64 time=0.494 ms
2022-02-16 12:11:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=5 ttl=64 time=0.383 ms

--- 192.168.122.155 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4095ms
rtt min/avg/max/mdev = 0.375/0.444/0.504/0.058 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:11:38 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.155
root@192.168.122.155's password: 
2022-02-16 12:11:47 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:21:06 PM EST
  System load:  0.0                Processes:             140
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.155
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:11:28 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:11:56 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 12:12:02 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 12:12:08 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 12:12:13 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 12:12:19 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-16 12:12:22 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 12:12:28 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 12:12:38 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-16 12:12:47 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 12:12:56 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 12:13:05 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 12:13:14 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.155 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:13:17 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-16 12:13:21 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.491 ms
2022-02-16 12:13:22 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.298 ms
2022-02-16 12:13:23 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.271 ms
2022-02-16 12:13:24 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.243 ms
2022-02-16 12:13:25 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.253 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4124ms
rtt min/avg/max/mdev = 0.243/0.311/0.491/0.092 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:13:32 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.327 ms
2022-02-16 12:13:33 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.076 ms
2022-02-16 12:13:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.161 ms
2022-02-16 12:13:35 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.200 ms
2022-02-16 12:13:36 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.072 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4118ms
rtt min/avg/max/mdev = 0.072/0.167/0.327/0.094 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:13:39 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 12:13:43 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.412 ms
2022-02-16 12:13:44 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.204 ms
2022-02-16 12:13:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.396 ms
2022-02-16 12:13:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.206 ms
2022-02-16 12:13:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.398 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4112ms
rtt min/avg/max/mdev = 0.204/0.323/0.412/0.097 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:13:56 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 12:14:05 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:23:24 PM EST
  System load:  0.0                Processes:             127
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:19:10 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:14:12 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.451 ms
2022-02-16 12:14:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.360 ms
2022-02-16 12:14:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.218 ms
2022-02-16 12:14:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.341 ms
2022-02-16 12:14:16 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.370 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4073ms
rtt min/avg/max/mdev = 0.218/0.348/0.451/0.075 ms
root@localhost:~# 
2022-02-16 12:14:56 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:14:59 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 12:15:03 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.251 ms
2022-02-16 12:15:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.279 ms
2022-02-16 12:15:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.254 ms
2022-02-16 12:15:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.251 ms
2022-02-16 12:15:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.250 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.250/0.257/0.279/0.011 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:15:13 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 12:15:15 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:15:20 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-16 12:15:23 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-16 12:15:23 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-16 12:15:28 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-16 12:15:31 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-16 12:15:31 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-16 12:15:36 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-16 12:15:39 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-16 12:15:40 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-16 12:15:45 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-16 12:15:48 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-16 12:15:48 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-16 12:15:53 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-16 12:15:53 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 4 time when VF is Assigned VM guest.*************************************************************


2022-02-16 12:15:56 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-16 12:15:56 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-16 12:16:01 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-16 12:16:01 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-16 12:16:01 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-16 12:16:07 - sshInstance.py - [line:92] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-16 12:16:10 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-16 12:16:13 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 12:16:13 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:16:18 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-16 12:16:21 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-16 12:16:21 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-16 12:16:26 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-16 12:16:29 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-16 12:16:29 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-16 12:16:34 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-16 12:16:37 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-16 12:16:38 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:16:43 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 12:16:46 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-16 12:16:46 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:16:51 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 12:16:51 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 12:16:54 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 12:16:54 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-16 12:16:59 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-16 12:17:02 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-16 12:17:03 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-16 12:17:08 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-16 12:17:12 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:17451): [1;33mWARNING[0m **: [34m12:26:34.319[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:17:15 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:17451): [1;33mWARNING[0m **: [34m12:26:34.319[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:17:15 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-16 12:17:19 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:17500): [1;33mWARNING[0m **: [34m12:26:41.303[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 12:17:21 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 12:17:24 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-16 12:17:28 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:17556): [1;33mWARNING[0m **: [34m12:26:50.277[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:17:31 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:17556): [1;33mWARNING[0m **: [34m12:26:50.277[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:17:31 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-16 12:17:35 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:17617): [1;33mWARNING[0m **: [34m12:26:57.318[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 12:17:37 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 12:17:40 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-16 12:17:43 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:17:43 - sshInstance.py - [line:48] - root - INFO - 192.168.122.138/24

2022-02-16 12:17:48 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.138/24

2022-02-16 12:17:51 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:17:51 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:17:56 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest2
2022-02-16 12:18:59 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:18:59 - sshInstance.py - [line:48] - root - INFO - 192.168.122.155/24

2022-02-16 12:19:04 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.155/24

2022-02-16 12:19:04 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.138
2022-02-16 12:19:04 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.155
2022-02-16 12:19:08 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.456 ms
2022-02-16 12:19:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.442 ms
2022-02-16 12:19:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.465 ms
2022-02-16 12:19:11 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.393 ms
2022-02-16 12:19:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.389 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4083ms
rtt min/avg/max/mdev = 0.389/0.429/0.465/0.031 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:19:21 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 12:19:30 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:28:48 PM EST
  System load:  0.0                Processes:             139
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:23:24 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:19:39 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 12:19:45 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 12:19:51 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 12:19:56 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 12:20:02 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-16 12:20:05 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 12:20:11 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 12:20:21 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-16 12:20:30 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 12:20:39 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 12:20:48 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 12:20:57 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:21:04 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.155
PING 192.168.122.155 (192.168.122.155) 56(84) bytes of data.
64 bytes from 192.168.122.155: icmp_seq=1 ttl=64 time=0.286 ms
2022-02-16 12:21:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=2 ttl=64 time=0.470 ms
2022-02-16 12:21:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=3 ttl=64 time=0.476 ms
2022-02-16 12:21:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=4 ttl=64 time=0.465 ms
2022-02-16 12:21:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=5 ttl=64 time=0.356 ms

--- 192.168.122.155 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4112ms
rtt min/avg/max/mdev = 0.286/0.410/0.476/0.079 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:21:17 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.155
root@192.168.122.155's password: 
2022-02-16 12:21:26 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:30:45 PM EST
  System load:  0.0                Processes:             137
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.155
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:21:06 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:21:35 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 12:21:41 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 12:21:47 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 12:21:52 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 12:21:58 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-16 12:22:01 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 12:22:07 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 12:22:17 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-16 12:22:26 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 12:22:35 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 12:22:44 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 684 (684.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 12:22:53 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.155 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:22:56 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-16 12:23:00 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=1.02 ms
2022-02-16 12:23:01 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.291 ms
2022-02-16 12:23:02 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.287 ms
2022-02-16 12:23:03 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.246 ms
2022-02-16 12:23:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.278 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4078ms
rtt min/avg/max/mdev = 0.246/0.424/1.022/0.300 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:23:11 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.410 ms
2022-02-16 12:23:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.299 ms
2022-02-16 12:23:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.220 ms
2022-02-16 12:23:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.326 ms
2022-02-16 12:23:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.205 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4073ms
rtt min/avg/max/mdev = 0.205/0.292/0.410/0.074 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:23:18 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 12:23:22 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.362 ms
2022-02-16 12:23:23 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.472 ms
2022-02-16 12:23:24 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.479 ms
2022-02-16 12:23:25 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.465 ms
2022-02-16 12:23:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.470 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4131ms
rtt min/avg/max/mdev = 0.362/0.449/0.479/0.049 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:23:35 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 12:23:44 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:33:03 PM EST
  System load:  0.0                Processes:             127
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:28:49 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:23:51 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.224 ms
2022-02-16 12:23:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.160 ms
2022-02-16 12:23:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.219 ms
2022-02-16 12:23:54 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.347 ms
2022-02-16 12:23:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.047 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4091ms
rtt min/avg/max/mdev = 0.047/0.199/0.347/0.097 ms
root@localhost:~# 
2022-02-16 12:24:35 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:24:38 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 12:24:42 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.205 ms
2022-02-16 12:24:43 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.249 ms
2022-02-16 12:24:44 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.253 ms
2022-02-16 12:24:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.243 ms
2022-02-16 12:24:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.256 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4104ms
rtt min/avg/max/mdev = 0.205/0.241/0.256/0.021 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:24:52 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 12:24:54 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:24:59 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-16 12:25:02 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-16 12:25:02 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-16 12:25:07 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-16 12:25:10 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-16 12:25:11 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-16 12:25:16 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-16 12:25:19 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-16 12:25:19 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-16 12:25:24 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-16 12:25:27 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-16 12:25:27 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-16 12:25:32 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-16 12:25:32 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 5 time when VF is Assigned VM guest.*************************************************************


2022-02-16 12:25:35 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-16 12:25:35 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-16 12:25:40 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-16 12:25:40 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-16 12:25:40 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-16 12:25:46 - sshInstance.py - [line:92] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-16 12:25:49 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-16 12:25:52 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 12:25:52 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:25:57 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-16 12:26:00 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-16 12:26:00 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-16 12:26:05 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-16 12:26:08 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-16 12:26:08 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-16 12:26:13 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-16 12:26:16 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-16 12:26:17 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:26:22 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 12:26:25 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-16 12:26:26 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:26:31 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-16 12:26:31 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 12:26:34 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-16 12:26:34 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-16 12:26:39 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-16 12:26:42 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-16 12:26:42 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-16 12:26:47 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-16 12:26:51 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:18734): [1;33mWARNING[0m **: [34m12:36:13.429[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:26:54 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:18734): [1;33mWARNING[0m **: [34m12:36:13.429[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:26:54 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-16 12:26:58 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:18775): [1;33mWARNING[0m **: [34m12:36:20.441[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 12:27:00 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 12:27:03 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-16 12:27:07 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:18850): [1;33mWARNING[0m **: [34m12:36:29.419[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:27:10 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:18850): [1;33mWARNING[0m **: [34m12:36:29.419[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-16 12:27:10 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-16 12:27:14 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:18895): [1;33mWARNING[0m **: [34m12:36:36.432[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-16 12:27:16 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-16 12:27:19 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-16 12:27:22 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:27:22 - sshInstance.py - [line:48] - root - INFO - 192.168.122.138/24

2022-02-16 12:27:27 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.138/24

2022-02-16 12:27:30 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:27:30 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:27:35 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest2
2022-02-16 12:28:38 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-16 12:28:38 - sshInstance.py - [line:48] - root - INFO - 192.168.122.155/24

2022-02-16 12:28:43 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.155/24

2022-02-16 12:28:43 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.138
2022-02-16 12:28:43 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.155
2022-02-16 12:28:47 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.420 ms
2022-02-16 12:28:48 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.325 ms
2022-02-16 12:28:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.270 ms
2022-02-16 12:28:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.319 ms
2022-02-16 12:28:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.472 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4090ms
rtt min/avg/max/mdev = 0.270/0.361/0.472/0.074 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:29:00 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 12:29:09 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:38:27 PM EST
  System load:  0.08               Processes:             136
  Usage of /:   40.7% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:33:03 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:29:18 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 12:29:24 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 12:29:30 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 12:29:35 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 12:29:41 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-16 12:29:44 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 12:29:50 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 12:30:00 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-16 12:30:09 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 12:30:18 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 12:30:27 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 12:30:36 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:30:43 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.155
PING 192.168.122.155 (192.168.122.155) 56(84) bytes of data.
64 bytes from 192.168.122.155: icmp_seq=1 ttl=64 time=0.461 ms
2022-02-16 12:30:44 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=2 ttl=64 time=0.336 ms
2022-02-16 12:30:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=3 ttl=64 time=0.467 ms
2022-02-16 12:30:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=4 ttl=64 time=0.332 ms
2022-02-16 12:30:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.155: icmp_seq=5 ttl=64 time=0.260 ms

--- 192.168.122.155 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4118ms
rtt min/avg/max/mdev = 0.260/0.371/0.467/0.081 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:30:56 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.155
root@192.168.122.155's password: 
2022-02-16 12:31:05 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:40:24 PM EST
  System load:  0.0                Processes:             140
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.155
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:30:45 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:31:14 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-16 12:31:20 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-16 12:31:26 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-16 12:31:31 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-16 12:31:37 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-16 12:31:40 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-16 12:31:46 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-16 12:31:56 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-16 12:32:05 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-16 12:32:14 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-16 12:32:23 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-16 12:32:32 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.155 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:32:35 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-16 12:32:39 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.492 ms
2022-02-16 12:32:40 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.267 ms
2022-02-16 12:32:41 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.287 ms
2022-02-16 12:32:42 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.264 ms
2022-02-16 12:32:43 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.205 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4083ms
rtt min/avg/max/mdev = 0.205/0.303/0.492/0.098 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:32:50 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.424 ms
2022-02-16 12:32:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.258 ms
2022-02-16 12:32:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.266 ms
2022-02-16 12:32:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.172 ms
2022-02-16 12:32:54 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.250 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4077ms
rtt min/avg/max/mdev = 0.172/0.274/0.424/0.082 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:32:57 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 12:33:01 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.138
PING 192.168.122.138 (192.168.122.138) 56(84) bytes of data.
64 bytes from 192.168.122.138: icmp_seq=1 ttl=64 time=0.188 ms
2022-02-16 12:33:02 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=2 ttl=64 time=0.311 ms
2022-02-16 12:33:03 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=3 ttl=64 time=0.269 ms
2022-02-16 12:33:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=4 ttl=64 time=0.315 ms
2022-02-16 12:33:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.138: icmp_seq=5 ttl=64 time=0.250 ms

--- 192.168.122.138 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4134ms
rtt min/avg/max/mdev = 0.188/0.266/0.315/0.049 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:33:14 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.138
root@192.168.122.138's password: 
2022-02-16 12:33:23 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Feb 2022 11:42:42 PM EST
  System load:  0.0                Processes:             129
  Usage of /:   40.7% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.138
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 15 23:38:28 2022 from 192.168.122.1
root@localhost:~# 
2022-02-16 12:33:30 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.268 ms
2022-02-16 12:33:31 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.154 ms
2022-02-16 12:33:32 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.246 ms
2022-02-16 12:33:33 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.330 ms
2022-02-16 12:33:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.342 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4083ms
rtt min/avg/max/mdev = 0.154/0.268/0.342/0.067 ms
root@localhost:~# 
2022-02-16 12:34:14 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.138 closed.
[root@WW25ICX2 ~]# 
2022-02-16 12:34:17 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-16 12:34:21 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.208 ms
2022-02-16 12:34:22 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.290 ms
2022-02-16 12:34:23 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.281 ms
2022-02-16 12:34:24 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.214 ms
2022-02-16 12:34:25 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.256 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4109ms
rtt min/avg/max/mdev = 0.208/0.249/0.290/0.039 ms
[root@WW25ICX2 ~]# 
2022-02-16 12:34:31 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 12:34:33 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:34:38 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-16 12:34:41 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-16 12:34:42 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-16 12:34:47 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-16 12:34:50 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-16 12:34:50 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-16 12:34:55 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-16 12:34:58 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-16 12:34:58 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-16 12:35:03 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-16 12:35:06 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-16 12:35:06 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-16 12:35:11 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
.2022-02-16 12:35:14 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-16 12:35:14 - sshInstance.py - [line:48] - root - INFO - 

2022-02-16 12:35:19 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-16 12:35:22 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-16 12:35:22 - sshInstance.py - [line:48] - root - INFO - 

2022-02-16 12:35:27 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-16 12:35:30 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-16 12:35:30 - sshInstance.py - [line:48] - root - INFO - 

2022-02-16 12:35:35 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-16 12:35:38 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-16 12:35:38 - sshInstance.py - [line:48] - root - INFO - 

2022-02-16 12:35:43 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-16 12:35:46 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-16 12:35:46 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:35:54 - sshInstance.py - [line:44] - root - INFO - ifconfig ens2f0 0
2022-02-16 12:35:54 - sshInstance.py - [line:48] - root - INFO - 
2022-02-16 12:35:59 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-02-16 12:35:59 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
                  [100%]

=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:38
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:38: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:71
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:71: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:48
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:48: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:87
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:87: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:362
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:362: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:478
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:478: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:776
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:776: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:52
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:52: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:76
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:76: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:98
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:98: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:124
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:124: PytestUnknownMarkWarning: Unknown pytest.mark.drive - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.drive

npxtester/Tests/testNics/test_nics.py:162
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:162: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html -
========== 1 passed, 15 deselected, 12 warnings in 2956.43s (0:49:16) ==========
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4Ix6O+hSs/J+WYhicXoVNFsq2LY7NwaGm8aSejP8W5cDAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRgg5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77aCbP8BPqPtor0AAAA=[0m[Pipeline] }
[8mha:////4GHchb786wl688erDJjASqsmJ9Hr4hPtHO8ytwYHX0MzAAAAoh+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IkMhon14bFL6hQa6F5D9uHMPlF/pr/IJHEyTvdc5bzemOdIo4cnWotdZ5S7VUfBjc/NXLsroFH1fJF1UyJg1WVHStu7GnBisViWZZjpbGxVAdOnpxgq1vzMEUw5IqzxNkdNHLf3PFEpueymChfmCJ2t6FJTL/O3wCmvhfk5V6QlR9NTCl7vQAAAA==[0m[Pipeline] // node
[8mha:////4N3Zwv+i78+NyT5x5Iut/zlc/vu2cqXlCZqUPy9nGyYaAAAAoh+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IkMhon14bFL6hQa6F5D9uHMPlF/pr/IJHEyTvdc5bzemOdIo4cnWotdZ5S7VUfBjc/NXLsroFH1fJF1UyJg1WVHStu7GnBisViWZZjpbGxVAdOnpxgq1vzMEUw5IqzxNkdNHLf3PFEpueymChfmCJ2t6FJTL/O3wCmvhfkZSnI9h9rVU4xvQAAAA==[0m[Pipeline] End of Pipeline
Finished: SUCCESS
