Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/cyp-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"1.6.4"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-21.02/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.239.182.209","pf1":"ens785f2","os":"RHEL"},"pkg_generator":{"host":"10.239.182.79","pf1":"ens787f2"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 19 items / 18 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-04-22 11:16:45 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-22/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]_11_16_45/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img].log, case_logdir: /root/testconfig/testlogs/2022-04-22/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]_11_16_45
2022-04-22 11:16:45 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
2022-04-22 11:16:45 - test_network_sriov_stress.py - [line:32] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-04-22 11:16:45 - test_network_sriov_stress.py - [line:50] - root - INFO - ssh to the sut1
2022-04-22 11:16:45 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-22 11:16:45 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-22 11:16:45 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-22 11:16:45 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-22 11:16:45 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-22 11:16:45 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-22 11:16:45 - test_network_sriov_stress.py - [line:64] - root - INFO - clean up iperf and taskset process...
2022-04-22 11:16:48 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-04-22 11:16:48 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:16:56 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-04-22 11:16:56 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:04 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-04-22 11:17:04 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:12 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-04-22 11:17:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:17 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 3] Opened sftp connection (server version 3)
2022-04-22 11:17:17 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-22 11:17:20 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-22 11:17:20 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-22 11:17:25 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-22 11:17:25 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-22 11:17:28 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-22 11:17:37 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:43 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-22 11:17:43 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-22 11:17:46 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-22 11:17:50 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:55 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-22 11:17:58 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-22 11:17:58 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-22 11:18:03 - test_network_sriov_stress.py - [line:72] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-22 11:18:03 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-22 11:18:09 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Apr 22 11:30:44 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (79ee7527-2cc5-44ff-88d0-147dde6b8b0f) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:18:12 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-22 11:18:18 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:18:21 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-22 11:18:27 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (ed375318-dadf-4fa9-8bf8-d0bd5c92cc83) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:18:30 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-22 11:18:36 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:18:39 - test_network_sriov_stress.py - [line:79] - root - INFO - trying to get ipv6 addr for pf1
2022-04-22 11:18:42 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-22 11:18:42 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::7345:8512:8eae:34  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41  bytes 6744 (6.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-22 11:18:50 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-22 11:18:50 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 299905559  bytes 454025351005 (422.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14572949  bytes 963532064 (918.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-22 11:18:55 - test_network_sriov_stress.py - [line:597] - root - INFO - 
Stress Disable and Enable for 1 time when VF is Assigned VM guest.

2022-04-22 11:18:58 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
2022-04-22 11:18:58 - sshInstance.py - [line:54] - root - INFO - 0000:4b:00.2

2022-04-22 11:19:04 - test_network_sriov_stress.py - [line:130] - root - INFO - pf_id was found: 0000:4b:00.2

2022-04-22 11:19:04 - test_network_sriov_stress.py - [line:605] - root - INFO - format_pf_id is 0000\:4b\:00.2

2022-04-22 11:19:04 - test_network_sriov_stress.py - [line:608] - root - INFO - pf_id_key: 4b
2022-04-22 11:19:04 - test_network_sriov_stress.py - [line:612] - root - INFO - start to assign ip for ens785f2 of SUT1: 192.168.10.10
2022-04-22 11:19:10 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 192.168.10.10
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:19:13 - test_network_sriov_stress.py - [line:339] - root - INFO - Successfully assigned ip to ethernet: ens785f2
2022-04-22 11:19:13 - test_network_sriov_stress.py - [line:614] - root - INFO - start to assign ip for ens787f2 of SUT2: 192.168.10.11
2022-04-22 11:19:19 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Apr 22 11:29:07 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# ifconfig ens787f2 192.168.10.11
[root@npx-cypsilver1-rel84 ~]# 
2022-04-22 11:19:22 - test_network_sriov_stress.py - [line:339] - root - INFO - Successfully assigned ip to ethernet: ens787f2
2022-04-22 11:19:22 - test_network_sriov_stress.py - [line:136] - root - INFO - virtulize sut1 pf to 4 vfs
2022-04-22 11:19:25 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-22 11:19:25 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:19:30 - test_network_sriov_stress.py - [line:145] - root - INFO - Successfully Virtualized PF to VFs.
2022-04-22 11:19:33 - sshInstance.py - [line:50] - root - INFO - lspci | grep "Virtual" |grep 4b | awk '{print $1;}'list
2022-04-22 11:19:33 - sshInstance.py - [line:54] - root - INFO - 4b:11.0
4b:11.1
4b:11.2
4b:11.3

2022-04-22 11:19:38 - test_network_sriov_stress.py - [line:159] - root - INFO - Succssfully Gotten vf_id list:

2022-04-22 11:19:41 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-04-22 11:19:41 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:19:46 - test_network_sriov_stress.py - [line:179] - root - INFO - start to bind drive in sut1
2022-04-22 11:19:49 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.0
2022-04-22 11:19:50 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:19:55 - test_network_sriov_stress.py - [line:193] - root - INFO - Successfuly bound VF to vfio-pci
2022-04-22 11:19:58 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.1
2022-04-22 11:19:59 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:20:04 - test_network_sriov_stress.py - [line:193] - root - INFO - Successfuly bound VF to vfio-pci
2022-04-22 11:20:04 - test_network_sriov_stress.py - [line:632] - root - INFO - lspci -Dnn | grep 4b:11.1
2022-04-22 11:20:07 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 4b:11.1
2022-04-22 11:20:07 - sshInstance.py - [line:54] - root - INFO - 0000:4b:11.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-04-22 11:20:12 - test_network_sriov_stress.py - [line:644] - root - INFO - Successfully get vf device id: 8086:1889
2022-04-22 11:20:12 - test_network_sriov_stress.py - [line:216] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-04-22 11:20:15 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-04-22 11:20:15 - sshInstance.py - [line:54] - root - INFO - yes

2022-04-22 11:20:20 - test_network_sriov_stress.py - [line:219] - root - INFO - Default network is active? yes

2022-04-22 11:20:20 - test_network_sriov_stress.py - [line:657] - root - INFO - start to create VMs....
2022-04-22 11:20:20 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:20:24 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:27 - test_network_sriov_stress.py - [line:252] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:20:31 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:37 - sshInstance.py - [line:50] - root - INFO - virsh list --all
2022-04-22 11:20:37 - sshInstance.py - [line:54] - root - INFO -  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


2022-04-22 11:20:42 - test_network_sriov_stress.py - [line:262] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:42 - test_network_sriov_stress.py - [line:263] - root - INFO - Failed to create a VM: 
2022-04-22 11:20:42 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:20:46 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:49 - test_network_sriov_stress.py - [line:252] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:20:53 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:59 - sshInstance.py - [line:50] - root - INFO - virsh list --all
2022-04-22 11:20:59 - sshInstance.py - [line:54] - root - INFO -  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


2022-04-22 11:21:04 - test_network_sriov_stress.py - [line:262] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:21:04 - test_network_sriov_stress.py - [line:263] - root - INFO - Failed to create a VM: 
2022-04-22 11:21:04 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:21:08 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:21:11 - test_network_sriov_stress.py - [line:252] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:21:15 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:21:21 - sshInstance.py - [line:50] - root - INFO - virsh list --all
2022-04-22 11:21:21 - sshInstance.py - [line:54] - root - INFO -  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


2022-04-22 11:21:26 - test_network_sriov_stress.py - [line:262] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:21:26 - test_network_sriov_stress.py - [line:263] - root - INFO - Failed to create a VM: 
2022-04-22 11:21:26 - test_network_sriov_stress.py - [line:271] - root - ERROR - Failed to create a VM: VMtest1)
F2022-04-22 11:21:26 - test_network_sriov_stress.py - [line:91] - root - INFO - removing VMs: VMtest1, VMtest2
2022-04-22 11:21:29 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest2
2022-04-22 11:21:29 - sshInstance.py - [line:54] - root - INFO - error: Failed to destroy domain VMtest2
error: Requested operation is not valid: domain is not running


2022-04-22 11:21:34 - test_network_sriov_stress.py - [line:316] - root - ERROR - Failed to shut down the VM VMtest2
2022-04-22 11:21:37 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest1
2022-04-22 11:21:37 - sshInstance.py - [line:54] - root - INFO - error: Failed to destroy domain VMtest1
error: Requested operation is not valid: domain is not running


2022-04-22 11:21:42 - test_network_sriov_stress.py - [line:316] - root - ERROR - Failed to shut down the VM VMtest1
2022-04-22 11:21:45 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-22 11:21:48 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:21:56 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-22 11:21:56 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:22:04 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-22 11:22:04 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:22:12 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-22 11:22:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:22:17 - test_network_sriov_stress.py - [line:100] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-22 11:22:17 - test_network_sriov_stress.py - [line:102] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-22/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]_11_16_45
2022-04-22 11:22:20 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-22 11:22:20 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:22:25 - test_network_sriov_stress.py - [line:104] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-22 11:22:28 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/*.txt
2022-04-22 11:22:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:22:33 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-22 11:22:33 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
                  [100%]

=================================== FAILURES ===================================
_ Test_Network_SRIOV_Stress.test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] _

self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f9d4e862358>
vm1_image = 'uvm2.img', vm2_image = 'uvm1.img'

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicGold
    @pytest.mark.nicSriov5times
    @pytest.mark.parametrize('vm1_image, vm2_image', vm_image)
    def test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest(self, vm1_image, vm2_image):
        for j in range(1, 2):
            logging.info("\nStress Disable and Enable for {} time when VF is Assigned VM guest.\n".format(j))
            # get pf id: 0000:xx:xx.x
            pf_id, status = self.get_pf_id(self.client, self.pf_name)
            # transfer pf_id to 0000\:00\:00.0 format
            if not pf_id:
                assert 200 == status
            else:
                pf_id_format = pf_id.replace(":", "\\:", 2)
                logging.info("format_pf_id is {}".format(pf_id_format))
                # get the number key of pf_id
                pf_id_key = pf_id.split(":")[1]
                logging.info("pf_id_key: {}".format(pf_id_key))
                # assign IP to PF in SUT and sut2
                pf_ip = "192.168.10.10"
                sut2_ip = "192.168.10.11"
                logging.info("start to assign ip for {} of SUT1: {}".format(self.pf_name, pf_ip))
                assert 200 == self.assign_ip_ehternet(self.session, pf_ip, self.pf_name)
                logging.info("start to assign ip for {} of SUT2: {}".format(self.pf2_name, sut2_ip))
                assert 200 == self.assign_ip_ehternet(self.session2, sut2_ip, self.pf2_name)
                # virtulize the pf to vfs
                assert 200 == self.virtualize_pf_to_vfs(self.pf_name)
                # get vf ids
                vf_id_list, status = self.get_vf_ids(self.client, pf_id_key)
                vf_id_list = [i.strip() for i in vf_id_list]
                if status == 200:
                    # modprobe vfio-pci
                    assert 200 == self.modprobe("vfio-pci")
                    # bind vf with vfio-pci
                    host_dev_id_list, status = self.bind_vf_to_vfio_pci(self.client, vf_id_list)
                    assert 200 == status
                else:
                    assert 200 == status
                # get vF device ida
                # tmp code
                cmd = "lspci -Dnn | grep %s" % (vf_id_list[1])
                logging.info(cmd)
                vf_device_id = ""
                vf_device_id_rs, error = self.ssh_sut.ssh_exec_cmd(self.client, cmd)
                vf_device_id_rs = vf_device_id_rs.strip()
                if vf_device_id_rs:
                    st = False
                    vf_device_id = None
                    for one in vf_device_id_rs.split(" "):
                        one = " " + one + " "
                        if one.find(" [") > -1 and one.find("] ") > -1 and one.find(":") > -1:
                            vf_device_id = one.replace("[", "").replace("]", "").strip()
                    if not vf_device_id: assert 200 == 400, "vf_device_id is not found"
                    logging.info("Successfully get vf device id: {}".format(vf_device_id))
                    assert 200 == 200
                else:
                    logging.error("Fail to get vf device id.")
                    assert 200 == 400
    
                # set network
                status = self.default_network_isActive(self.client, self.defult_network)
                if status == "no":
                    logging.info("start to check default network status...")
                    assert 200 == self.start_default_network(self.client, self.defult_network)
    
                # start VMs
                logging.info("start to create VMs....")
                if self.sut_info["os"] == "UBUNTU":
                    assert 200 == self.create_vm(vm1_image, host_dev_id_list[0],  self.vm1_name, "ubuntu20.04", "5900")
                    assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "ubuntu20.04", "5901")
                else:
>                   assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "rhel8.2", "5900")
E                   AssertionError: assert 200 == 400
E                    +  where 400 = <bound method Test_Network_SRIOV_Stress.create_vm of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f9d4e862358>>('uvm2.img', 'pci_0000_4b_11_0', 'VMtest1', 'rhel8.2', '5900')
E                    +    where <bound method Test_Network_SRIOV_Stress.create_vm of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f9d4e862358>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f9d4e862358>.create_vm
E                    +    and   'VMtest1' = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f9d4e862358>.vm1_name

npxtester/Tests/testNics/test_network_sriov_stress.py:662: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-04-22 11:16:45 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-22/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]_11_16_45/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img].log, case_logdir: /root/testconfig/testlogs/2022-04-22/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]_11_16_45
2022-04-22 11:16:45 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
2022-04-22 11:16:45 - test_network_sriov_stress.py - [line:32] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-04-22 11:16:45 - test_network_sriov_stress.py - [line:50] - root - INFO - ssh to the sut1
2022-04-22 11:16:45 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-22 11:16:45 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-22 11:16:45 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-22 11:16:45 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-22 11:16:45 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-22 11:16:45 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-22 11:16:45 - test_network_sriov_stress.py - [line:64] - root - INFO - clean up iperf and taskset process...
2022-04-22 11:16:48 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-04-22 11:16:48 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:16:56 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-04-22 11:16:56 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:04 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-04-22 11:17:04 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:12 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-04-22 11:17:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:17 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 3] Opened sftp connection (server version 3)
2022-04-22 11:17:17 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-22 11:17:20 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-22 11:17:20 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-22 11:17:25 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-22 11:17:25 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-22 11:17:28 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-22 11:17:37 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:43 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-22 11:17:43 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-22 11:17:46 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-22 11:17:50 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:17:55 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-22 11:17:58 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-22 11:17:58 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-22 11:18:03 - test_network_sriov_stress.py - [line:72] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-22 11:18:03 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-22 11:18:09 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Apr 22 11:30:44 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (79ee7527-2cc5-44ff-88d0-147dde6b8b0f) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:18:12 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-22 11:18:18 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:18:21 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-22 11:18:27 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (ed375318-dadf-4fa9-8bf8-d0bd5c92cc83) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:18:30 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-22 11:18:36 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:18:39 - test_network_sriov_stress.py - [line:79] - root - INFO - trying to get ipv6 addr for pf1
2022-04-22 11:18:42 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-22 11:18:42 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::7345:8512:8eae:34  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41  bytes 6744 (6.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-22 11:18:50 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-22 11:18:50 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 299905559  bytes 454025351005 (422.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14572949  bytes 963532064 (918.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-04-22 11:18:55 - test_network_sriov_stress.py - [line:597] - root - INFO - 
Stress Disable and Enable for 1 time when VF is Assigned VM guest.

2022-04-22 11:18:58 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
2022-04-22 11:18:58 - sshInstance.py - [line:54] - root - INFO - 0000:4b:00.2

2022-04-22 11:19:04 - test_network_sriov_stress.py - [line:130] - root - INFO - pf_id was found: 0000:4b:00.2

2022-04-22 11:19:04 - test_network_sriov_stress.py - [line:605] - root - INFO - format_pf_id is 0000\:4b\:00.2

2022-04-22 11:19:04 - test_network_sriov_stress.py - [line:608] - root - INFO - pf_id_key: 4b
2022-04-22 11:19:04 - test_network_sriov_stress.py - [line:612] - root - INFO - start to assign ip for ens785f2 of SUT1: 192.168.10.10
2022-04-22 11:19:10 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 192.168.10.10
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:19:13 - test_network_sriov_stress.py - [line:339] - root - INFO - Successfully assigned ip to ethernet: ens785f2
2022-04-22 11:19:13 - test_network_sriov_stress.py - [line:614] - root - INFO - start to assign ip for ens787f2 of SUT2: 192.168.10.11
2022-04-22 11:19:19 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Apr 22 11:29:07 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# ifconfig ens787f2 192.168.10.11
[root@npx-cypsilver1-rel84 ~]# 
2022-04-22 11:19:22 - test_network_sriov_stress.py - [line:339] - root - INFO - Successfully assigned ip to ethernet: ens787f2
2022-04-22 11:19:22 - test_network_sriov_stress.py - [line:136] - root - INFO - virtulize sut1 pf to 4 vfs
2022-04-22 11:19:25 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-22 11:19:25 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:19:30 - test_network_sriov_stress.py - [line:145] - root - INFO - Successfully Virtualized PF to VFs.
2022-04-22 11:19:33 - sshInstance.py - [line:50] - root - INFO - lspci | grep "Virtual" |grep 4b | awk '{print $1;}'list
2022-04-22 11:19:33 - sshInstance.py - [line:54] - root - INFO - 4b:11.0
4b:11.1
4b:11.2
4b:11.3

2022-04-22 11:19:38 - test_network_sriov_stress.py - [line:159] - root - INFO - Succssfully Gotten vf_id list:

2022-04-22 11:19:41 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-04-22 11:19:41 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:19:46 - test_network_sriov_stress.py - [line:179] - root - INFO - start to bind drive in sut1
2022-04-22 11:19:49 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.0
2022-04-22 11:19:50 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:19:55 - test_network_sriov_stress.py - [line:193] - root - INFO - Successfuly bound VF to vfio-pci
2022-04-22 11:19:58 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.1
2022-04-22 11:19:59 - sshInstance.py - [line:54] - root - INFO - 
2022-04-22 11:20:04 - test_network_sriov_stress.py - [line:193] - root - INFO - Successfuly bound VF to vfio-pci
2022-04-22 11:20:04 - test_network_sriov_stress.py - [line:632] - root - INFO - lspci -Dnn | grep 4b:11.1
2022-04-22 11:20:07 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 4b:11.1
2022-04-22 11:20:07 - sshInstance.py - [line:54] - root - INFO - 0000:4b:11.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-04-22 11:20:12 - test_network_sriov_stress.py - [line:644] - root - INFO - Successfully get vf device id: 8086:1889
2022-04-22 11:20:12 - test_network_sriov_stress.py - [line:216] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-04-22 11:20:15 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-04-22 11:20:15 - sshInstance.py - [line:54] - root - INFO - yes

2022-04-22 11:20:20 - test_network_sriov_stress.py - [line:219] - root - INFO - Default network is active? yes

2022-04-22 11:20:20 - test_network_sriov_stress.py - [line:657] - root - INFO - start to create VMs....
2022-04-22 11:20:20 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:20:24 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:27 - test_network_sriov_stress.py - [line:252] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:20:31 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:37 - sshInstance.py - [line:50] - root - INFO - virsh list --all
2022-04-22 11:20:37 - sshInstance.py - [line:54] - root - INFO -  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


2022-04-22 11:20:42 - test_network_sriov_stress.py - [line:262] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:42 - test_network_sriov_stress.py - [line:263] - root - INFO - Failed to create a VM: 
2022-04-22 11:20:42 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:20:46 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:49 - test_network_sriov_stress.py - [line:252] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:20:53 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:20:59 - sshInstance.py - [line:50] - root - INFO - virsh list --all
2022-04-22 11:20:59 - sshInstance.py - [line:54] - root - INFO -  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


2022-04-22 11:21:04 - test_network_sriov_stress.py - [line:262] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:21:04 - test_network_sriov_stress.py - [line:263] - root - INFO - Failed to create a VM: 
2022-04-22 11:21:04 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:21:08 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:21:11 - test_network_sriov_stress.py - [line:252] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-22 11:21:15 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:21:21 - sshInstance.py - [line:50] - root - INFO - virsh list --all
2022-04-22 11:21:21 - sshInstance.py - [line:54] - root - INFO -  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


2022-04-22 11:21:26 - test_network_sriov_stress.py - [line:262] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
2022-04-22 11:21:26 - test_network_sriov_stress.py - [line:263] - root - INFO - Failed to create a VM: 
2022-04-22 11:21:26 - test_network_sriov_stress.py - [line:271] - root - ERROR - Failed to create a VM: VMtest1)
------------------------------ Captured log call -------------------------------
INFO     root:test_network_sriov_stress.py:597 
Stress Disable and Enable for 1 time when VF is Assigned VM guest.

INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
INFO     root:sshInstance.py:54 0000:4b:00.2

INFO     root:test_network_sriov_stress.py:130 pf_id was found: 0000:4b:00.2

INFO     root:test_network_sriov_stress.py:605 format_pf_id is 0000\:4b\:00.2

INFO     root:test_network_sriov_stress.py:608 pf_id_key: 4b
INFO     root:test_network_sriov_stress.py:612 start to assign ip for ens785f2 of SUT1: 192.168.10.10
INFO     root:sshInstance.py:99 ifconfig ens785f2 192.168.10.10
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:339 Successfully assigned ip to ethernet: ens785f2
INFO     root:test_network_sriov_stress.py:614 start to assign ip for ens787f2 of SUT2: 192.168.10.11
INFO     root:sshInstance.py:99 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Apr 22 11:29:07 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# ifconfig ens787f2 192.168.10.11
[root@npx-cypsilver1-rel84 ~]# 
INFO     root:test_network_sriov_stress.py:339 Successfully assigned ip to ethernet: ens787f2
INFO     root:test_network_sriov_stress.py:136 virtulize sut1 pf to 4 vfs
INFO     root:sshInstance.py:50 echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:145 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:50 lspci | grep "Virtual" |grep 4b | awk '{print $1;}'list
INFO     root:sshInstance.py:54 4b:11.0
4b:11.1
4b:11.2
4b:11.3

INFO     root:test_network_sriov_stress.py:159 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:50 modprobe vfio-pci

INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:179 start to bind drive in sut1
INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.0
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:193 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.1
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:193 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:632 lspci -Dnn | grep 4b:11.1
INFO     root:sshInstance.py:50 lspci -Dnn | grep 4b:11.1
INFO     root:sshInstance.py:54 0000:4b:11.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:644 Successfully get vf device id: 8086:1889
INFO     root:test_network_sriov_stress.py:216 get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:54 yes

INFO     root:test_network_sriov_stress.py:219 Default network is active? yes

INFO     root:test_network_sriov_stress.py:657 start to create VMs....
INFO     root:test_network_sriov_stress.py:249 try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:252 cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
INFO     root:sshInstance.py:50 virsh list --all
INFO     root:sshInstance.py:54  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


INFO     root:test_network_sriov_stress.py:262 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:263 Failed to create a VM: 
INFO     root:test_network_sriov_stress.py:249 try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:252 cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
INFO     root:sshInstance.py:50 virsh list --all
INFO     root:sshInstance.py:54  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


INFO     root:test_network_sriov_stress.py:262 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:263 Failed to create a VM: 
INFO     root:test_network_sriov_stress.py:249 try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:252 cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
INFO     root:sshInstance.py:50 virsh list --all
INFO     root:sshInstance.py:54  Id   Name      State
--------------------------
 -    VMtest1   shut off
 -    VMtest2   shut off


INFO     root:test_network_sriov_stress.py:262 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Guest name 'VMtest1' is already in use.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:263 Failed to create a VM: 
ERROR    root:test_network_sriov_stress.py:271 Failed to create a VM: VMtest1)
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:90
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:90: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:143
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:143: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:108
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:108: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:593
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:593: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:720
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:720: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:960
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:960: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_network_sriov_stress.py:1096
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:1096: PytestUnknownMarkWarning: Unknown pytest.mark.nicIperfTcpSUTGuestStress - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicIperfTcpSUTGuestStress

npxtester/Tests/testNics/test_network_sriov_stress.py:1097
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:1097: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:93
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:93: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:132
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:132: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:167
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:167: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:168
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:168: PytestUnknownMarkWarning: Unknown pytest.mark.test - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.test

npxtester/Tests/testNics/test_nics.py:256
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:256: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:282
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:282: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:325
  /root/.jenkins/workspace/cyp-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:325: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]
========== 1 failed, 18 deselected, 16 warnings in 365.16s (0:06:05) ===========
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4AfI3SthhIf/wHKBxkZZVuznCBOLGICd+mTaK5J1XhvpAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMHmfoKzrT+3fkMfZ274AAAA=[0m[Pipeline] }
[8mha:////4O1G14z5oV6C9jl1Q5yIn+pZFQRmsElhyj6JiXyHA8ixAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiBB2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7BpKm1V++AAAA[0m[Pipeline] // stage
[8mha:////4KtBCOpIKS64HlRGbxVDHBnhT4546C6ceKSEgLxKWO63AAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUauVY2WZoPEGEGAOZXUwWofJEXs07yMiMlb/67zXv9cYyRRw5OtVYaj2lyqsu9G56auDYXgMPquGLqpgSB6tKO5Rc29OMJYvFvCzHQmNlqQqcPDnBWjfmYYpgyBVniZM7aOS+vuOJTE9lMVG+MEZsbn2dmH6dvwGMXSfIt3tBtvsA/gVtV70AAAA=[0m[Pipeline] }
[8mha:////4PVa+eOfGCB5ryE2GyokIfyPZOVvh3emQVgJTOuHuCGAAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IMJC7GybVh8Qsq1Fpo3sP2IUx+kb/mP0gkcfJO95zlvN5Yp4gjR6daS52nVHvVh8HNT40cu2vgUbV8UTVT4mBVZceKG3tasGKxWJblWGlsLNWBkycn2OrWPEwRDLniLHF2B43cN3c8kem5LCbKF6aI3W1oEtOv8zeAqe8FebkXZOUHjeqpjr0AAAA=[0m[Pipeline] // node
[8mha:////4OyM7hMK6utvbTfbnNkjhtaoCHWCq3+ZbQ+BNe9AvJHZAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRoKBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Lu9INt+AKvzzsS9AAAA[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
