Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester
ls: cannot access '/root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester': No such file or directory
[8mha:////4MftwC6NxviNjDdpfna9VBlJkoMp8EhRTGL2zcTKdEZ0AAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77aCbP8Brmfz270AAAA=[0m[Pipeline] }
[8mha:////4Kr9K7llyIIfXzIi7fTbyam3A+VyjB0I1hAyH+fEbXLCAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIMlYVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0gL0tBtv8Aj1Msdr0AAAA=[0m[Pipeline] // script
[8mha:////4FI2+bSiptyXTIERd0s3FW0AIUAVzDIQC15QCQE4LYPvAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRFDSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPyRmLRr0AAAA=[0m[Pipeline] }
[8mha:////4EIF7pCgSAhTUJ+YeVF144RCQBElcAy/oq5IQm3P5r/FAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRQlSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPw2Hi4r0AAAA=[0m[Pipeline] // stage
[8mha:////4O65h0jm98EO51SGQmOdf6FpfngMUfFS1Hkxj+qIATCfAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjpHSIitZywwtMYowT6y7YF5KKF/E1/oAhEhVb7ay0mucLyhThQNHJzmLvMTVeDmF0ucmJYn8JNMmOzrIhTBSs1HbS1NrjgprYwhJRwErB2mITKHl0DBvVmbupgkFXnTjmba+g8O0NHiBUNrOJ/IU5wvY6tonw5/krgHlgEDVDsas/x/INoKa7ysEAAAA=[0m[Pipeline] stage
[8mha:////4Cwh2bfnyXtsNeYvUrnMhkgZn3DOCE3ZIocZCmHhDj1kAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUSDAhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD5WQ+PfCAAAA[0m[Pipeline] { (clone)
[8mha:////4CFOXQFtiiA+7tA4CXv18jhcFszpIgsA6m3wBj5vXwoxAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiCmgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHN7LjSKW+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/Jiz1028/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4JxnGUheoVbdA4jH7w1zuxcsCY2poKXOhDnLMn7NKJYFAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiCkSBqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGOY4V7vgAAAA==[0m[Pipeline] }
[8mha:////4D4+5H4RzROPZTW0wBHD+XjMhoO5mPw9EWUJAbCIJpuGAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiJAokRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g3N4dT9vgAAAA==[0m[Pipeline] // stage
[8mha:////4AJAGqZwaYqyNNZtbc8g6ZE112gHcOMJEUqcQ3uLTkOfAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJBqEqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A361JXbBAAAA[0m[Pipeline] stage
[8mha:////4PP68w9I/uoPNBdRzp82S+tTLGAqcpDjYGyOG/BwZs8HAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycogU2BDqxBp14QShCSFp9H9JUtKJE3E17kCgEhMeLNuS9Z4vqIKHhrxmVmFvMHSGDW7UObFEvr84SszSmXWEgZxirUotSXWca0tRwayihAWHpcLOUTCoI6y4FXdRO4G6PkWftwOH0sgbPKDgmRyFj98yeVhfRxkIf5y/AJiGCOV2n223+TyrN7xWSV3CAAAA[0m[Pipeline] { (set args)
[8mha:////4BsNiMtY/8UtmXAIxp6NV4VtqKiaHUkJeJGRvFkfJcU+AAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICtIgqreWGF5jYGCfWnbEdkooX8TX+QCASFVusdraZ5wuWKcKRo8XWUOcoNQ6D7+20cODYXTwP2PIZG6bE3qA0g2Rt6hklZwNzihIWAlaGGs/Jkc2wFq26q8orstUpx+k7CCidvsEDCjGZs4r5C2OEzbXXienn+SuAMWQo99tP7cIbaOP4NL4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/conf/change_args.py '{"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","run_time":"600","pf1":"ens2f0","os":"rehat"},"sut2_conf":{"host":"10.112.97.60","pf1":"ens2f1"},"run_type":"ipv4"}'
[8mha:////4AyFPX+UZcZf/6aTNXdj+lWE0Z2b4chbTZ9e7eCHFoeRAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKC0iIqWisNLzCJMXasO8d2cCpexNf4A4FIVGyx2tlmni9YxwBHDhqtot5QbA16N+p5YebQXx1ntHzBlimyU9io3HCnTgs2nBQsKUpYCdgoah1HQzrBVlh5l5WTpKtzCvN3EFCaboAHFGI2JxnSF6YAu9vYRaaf568AJu8TlHX9qf0b7E/nQb4AAAA=[0m[Pipeline] }
[8mha:////4AFg/aWh/jHSmrlH6sy1kKjz0TFBfVRN+miPQW2LyX/uAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIioEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcrdPtf28AEud0rYvgAAAA==[0m[Pipeline] // stage
[8mha:////4Bhd+KV1EsVM3bnXBHnMClLv0EnBj/3vPQbr+7HWEbmAAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjoXSIitZywwtMYowT6y7YF5KKF/E1/oAhEhVb7ay0mucLyhThQNHJzmLvMTVeDmF0ucmJYn8JNMmOzrIhTBSs1HbS1NrjgprYwhJRwErB2mITKHl0DBvVmbupgkFXnTjmba+g8O0NHiBUNrOJ/IU5wvY6tonw5/krgHlgEDVDsas/x/INPbxT+8EAAAA=[0m[Pipeline] stage
[8mha:////4P13TIuP26wSoF8WyLGiU1qV0Q6Z+QylTska1uSfBb7mAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUQjAhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD/hYjrHCAAAA[0m[Pipeline] { (run nic case)
[8mha:////4FM3oozjxgRBqafqHchkdSyZ1a7wU/MTBVKRbtZrSwmtAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiIUGDqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAEIWoEpvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics -s -m SriovVfIperf --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/sriov_iperfvf_2hours_ipv4.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 16 items / 15 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-02-24 10:39:32 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] case ============================
2022-02-24 10:39:32 - test_network_sriov_stress.py - [line:31] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-02-24 10:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-02-24 10:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-02-24 10:39:32 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-02-24 10:39:32 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-02-24 10:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-02-24 10:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-02-24 10:39:32 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-02-24 10:39:35 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-02-24 10:39:43 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:39:51 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-02-24 10:39:57 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:40:05 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-02-24 10:40:05 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-02-24 10:40:13 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-24 10:40:13 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-02-24 10:40:18 - test_network_sriov_stress.py - [line:103] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-24 10:40:18 - test_network_sriov_stress.py - [line:803] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-24 10:40:18 - test_network_sriov_stress.py - [line:806] - root - INFO - pf_id_key: 4b
2022-02-24 10:40:24 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Thu Feb 24 10:45:41 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-02-24 10:40:27 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-24 10:40:33 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Thu Feb 24 10:34:52 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f1 192.168.10.11
[root@localhost ~]# 
2022-02-24 10:40:36 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f1
2022-02-24 10:40:39 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-24 10:40:39 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:40:44 - test_network_sriov_stress.py - [line:117] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-24 10:40:47 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-24 10:40:47 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-24 10:40:52 - test_network_sriov_stress.py - [line:131] - root - INFO - Succssfully Gotten vf_id list:

2022-02-24 10:40:55 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-02-24 10:40:55 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:41:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-24 10:41:04 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:41:09 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-24 10:41:12 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-24 10:41:12 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:41:17 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-24 10:41:17 - test_network_sriov_stress.py - [line:831] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-24 10:41:20 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-24 10:41:20 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-24 10:41:25 - test_network_sriov_stress.py - [line:842] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-24 10:41:28 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-24 10:41:29 - sshInstance.py - [line:50] - root - INFO - yes

2022-02-24 10:41:34 - test_network_sriov_stress.py - [line:191] - root - INFO - Default network is active? yes

2022-02-24 10:41:38 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:195509): [1;33mWARNING[0m **: [34m10:49:24.163[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-24 10:41:39 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-24 10:41:42 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest1
2022-02-24 10:41:46 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:195581): [1;33mWARNING[0m **: [34m10:49:32.192[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-24 10:41:47 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
2022-02-24 10:41:48 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-02-24 10:41:51 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest2
2022-02-24 10:41:54 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-24 10:41:54 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:41:59 - test_network_sriov_stress.py - [line:243] - root - ERROR - not found IP of VMtest1
2022-02-24 10:43:02 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-24 10:43:02 - sshInstance.py - [line:50] - root - INFO - 192.168.122.114/24

2022-02-24 10:43:07 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest1 IP: 192.168.122.114/24

2022-02-24 10:43:10 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-24 10:43:10 - sshInstance.py - [line:50] - root - INFO - 192.168.122.9/24

2022-02-24 10:43:15 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest2 IP: 192.168.122.9/24

2022-02-24 10:43:19 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.114
PING 192.168.122.114 (192.168.122.114) 56(84) bytes of data.
64 bytes from 192.168.122.114: icmp_seq=1 ttl=64 time=0.280 ms
2022-02-24 10:43:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=2 ttl=64 time=0.481 ms
2022-02-24 10:43:21 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=3 ttl=64 time=0.261 ms
2022-02-24 10:43:22 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=4 ttl=64 time=0.467 ms
2022-02-24 10:43:23 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=5 ttl=64 time=0.494 ms

--- 192.168.122.114 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4135ms
rtt min/avg/max/mdev = 0.261/0.396/0.494/0.105 ms
[root@WW25ICX2 ~]# 
2022-02-24 10:43:32 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.114
The authenticity of host '192.168.122.114 (192.168.122.114)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-02-24 10:43:41 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.114' (ECDSA) to the list of known hosts.
root@192.168.122.114's password: 
2022-02-24 10:43:50 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:51:33 PM EST
  System load:  0.0                Processes:             136
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.114
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Feb 22 22:05:38 2022 from 192.168.122.1
root@localhost:~# 
2022-02-24 10:43:59 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-24 10:44:05 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-24 10:44:11 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-24 10:44:16 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-24 10:44:22 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-02-24 10:44:25 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-24 10:44:31 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-24 10:44:41 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-24 10:44:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-24 10:44:59 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-24 10:45:08 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-24 10:45:17 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.114 closed.
[root@WW25ICX2 ~]# 
2022-02-24 10:45:24 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.9
PING 192.168.122.9 (192.168.122.9) 56(84) bytes of data.
64 bytes from 192.168.122.9: icmp_seq=1 ttl=64 time=0.317 ms
2022-02-24 10:45:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=2 ttl=64 time=0.266 ms
2022-02-24 10:45:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=3 ttl=64 time=0.392 ms
2022-02-24 10:45:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=4 ttl=64 time=0.488 ms
2022-02-24 10:45:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=5 ttl=64 time=0.259 ms

--- 192.168.122.9 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4117ms
rtt min/avg/max/mdev = 0.259/0.344/0.488/0.087 ms
[root@WW25ICX2 ~]# 
2022-02-24 10:45:37 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.9
The authenticity of host '192.168.122.9 (192.168.122.9)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-02-24 10:45:46 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.9' (ECDSA) to the list of known hosts.
root@192.168.122.9's password: 
2022-02-24 10:45:55 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:53:38 PM EST
  System load:  0.0                Processes:             140
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.9
  Swap usage:   0%

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 22 22:07:34 2022 from 192.168.122.1
root@localhost:~# 
2022-02-24 10:46:04 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-24 10:46:10 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-24 10:46:16 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-24 10:46:21 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-24 10:46:27 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-24 10:46:30 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-24 10:46:36 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-24 10:46:46 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-24 10:46:55 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-24 10:47:04 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-24 10:47:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-24 10:47:22 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.9 closed.
[root@WW25ICX2 ~]# 
2022-02-24 10:47:29 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.9
PING 192.168.122.9 (192.168.122.9) 56(84) bytes of data.
64 bytes from 192.168.122.9: icmp_seq=1 ttl=64 time=0.328 ms
2022-02-24 10:47:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=2 ttl=64 time=0.479 ms
2022-02-24 10:47:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=3 ttl=64 time=0.170 ms
2022-02-24 10:47:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=4 ttl=64 time=0.491 ms
2022-02-24 10:47:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=5 ttl=64 time=0.475 ms

--- 192.168.122.9 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.170/0.388/0.491/0.126 ms
[root@WW25ICX2 ~]# 
2022-02-24 10:47:42 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.9
root@192.168.122.9's password: 
2022-02-24 10:47:51 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:55:34 PM EST
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.9
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 23 21:53:39 2022 from 192.168.122.1
root@localhost:~# 
2022-02-24 10:48:00 - sshInstance.py - [line:94] - root - INFO - nohup iperf -s -V&
[1] 1086
root@localhost:~# 
root@localhost:~# nohup: ignoring input and appending output to 'nohup.out'

2022-02-24 10:48:09 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.9 closed.
[root@WW25ICX2 ~]# 
2022-02-24 10:48:18 - sshInstance.py - [line:94] - root - INFO - nohup iperf -s -V&
[1] 155707
[root@localhost ~]# 
[root@localhost ~]# nohup: ignoring input and appending output to 'nohup.out'

2022-02-24 10:48:25 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.114
PING 192.168.122.114 (192.168.122.114) 56(84) bytes of data.
64 bytes from 192.168.122.114: icmp_seq=1 ttl=64 time=0.465 ms
2022-02-24 10:48:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=2 ttl=64 time=0.350 ms
2022-02-24 10:48:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=3 ttl=64 time=0.269 ms
2022-02-24 10:48:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=4 ttl=64 time=0.503 ms
2022-02-24 10:48:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=5 ttl=64 time=0.466 ms

--- 192.168.122.114 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.269/0.410/0.503/0.090 ms
[root@WW25ICX2 ~]# 
2022-02-24 10:48:38 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.114
root@192.168.122.114's password: 
2022-02-24 10:48:47 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:56:31 PM EST
  System load:  0.0                Processes:             131
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.114
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Wed Feb 23 21:51:34 2022 from 192.168.122.1
root@localhost:~# 
2022-02-24 10:48:56 - sshInstance.py - [line:94] - root - INFO - rm -rf /tmp/*.txt
root@localhost:~# 
2022-02-24 10:59:16 - sshInstance.py - [line:94] - root - INFO - iperf -c 192.168.10.13 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_vm2.txt
root@localhost:~# 
2022-02-24 11:09:36 - sshInstance.py - [line:94] - root - INFO - iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_sut2.txt
root@localhost:~# 
2022-02-24 11:09:45 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.114 closed.
[root@WW25ICX2 ~]# 
2022-02-24 11:09:54 - sshInstance.py - [line:94] - root - INFO - rm -rf /tmp/*.txt
[root@WW25ICX2 ~]# 
2022-02-24 11:20:13 - sshInstance.py - [line:94] - root - INFO - iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv44_sut1_sut2.txt
[root@WW25ICX2 ~]# 
2022-02-24 11:20:22 - sshInstance.py - [line:94] - root - INFO - scp root@192.168.122.114:/tmp/*.txt /tmp
root@192.168.122.114's password: 
2022-02-24 11:20:31 - sshInstance.py - [line:94] - root - INFO - 
iperf_ipv4_vm1_sut2.txt                         0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_sut2.txt                       100%  298KB 128.7MB/s   00:00    
iperf_ipv4_vm1_vm2.txt                          0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_vm2.txt                        100%  298KB 162.3MB/s   00:00    
[root@WW25ICX2 ~]# 
2022-02-24 11:20:34 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: rm -rf /tmp/*.txt....
2022-02-24 11:20:34 - commonFunc.py - [line:30] - root - INFO - 
2022-02-24 11:20:34 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: rm -rf /tmp/*.txt
2022-02-24 11:20:34 - test_network_sriov_stress.py - [line:789] - root - INFO - Successfully iperf ipv4 vm1 vm2
2022-02-24 11:20:34 - test_network_sriov_stress.py - [line:789] - root - INFO - Successfully iperf ipv4 vm1 sut2
2022-02-24 11:20:34 - test_network_sriov_stress.py - [line:789] - root - INFO - Successfully iperf ipv4 sut1 sut2
2022-02-24 11:20:34 - test_network_sriov_stress.py - [line:790] - root - INFO - check ---end---
.2022-02-24 11:20:37 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-02-24 11:20:38 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-02-24 11:20:43 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-24 11:20:46 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-02-24 11:20:46 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-02-24 11:20:51 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest2
2022-02-24 11:20:54 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-02-24 11:20:54 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-02-24 11:20:59 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-24 11:21:02 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-02-24 11:21:02 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-02-24 11:21:07 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest1
2022-02-24 11:21:10 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-24 11:21:12 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 11:21:20 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 0
2022-02-24 11:21:20 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 11:21:25 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] case ============================
E                 [100%]

==================================== ERRORS ====================================
_ ERROR at teardown of Test_Network_SRIOV_Stress.test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] _
self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f93079efac8>

    def teardown(self):
        # status = self.remove_vf_from_pf()
        status = self.remove_vm(self.vm2_name)
        status = self.remove_vm(self.vm1_name)
        cmd = "echo 0 > /sys/class/net/{}/device/sriov_numvfs".format(self.sut_info["pf1"])
        self.ssh_sut.ssh_exec_cmd(self.client, cmd)
        self.ssh_sut.ssh_exec_cmd(self.client, "ifconfig {} 0".format(self.sut_info["pf1"]))
        #dmesg log
>       self.cn_test_sut.ssh_exec_cmd(self.client, "dmesg > /tmp/dmesg.log")
E       AttributeError: 'Test_Network_SRIOV_Stress' object has no attribute 'cn_test_sut'

npxtester/Tests/testNics/test_network_sriov_stress.py:76: AttributeError
---------------------------- Captured stdout setup -----------------------------
2022-02-24 10:39:32 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] case ============================
2022-02-24 10:39:32 - test_network_sriov_stress.py - [line:31] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-02-24 10:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-02-24 10:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-02-24 10:39:32 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-02-24 10:39:32 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-02-24 10:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-02-24 10:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-02-24 10:39:32 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-02-24 10:39:35 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-02-24 10:39:43 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:39:51 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-02-24 10:39:57 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:40:05 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-02-24 10:40:05 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

----------------------------- Captured stdout call -----------------------------
2022-02-24 10:40:13 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-24 10:40:13 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-02-24 10:40:18 - test_network_sriov_stress.py - [line:103] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-24 10:40:18 - test_network_sriov_stress.py - [line:803] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-24 10:40:18 - test_network_sriov_stress.py - [line:806] - root - INFO - pf_id_key: 4b
2022-02-24 10:40:24 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Thu Feb 24 10:45:41 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-02-24 10:40:27 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-24 10:40:33 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Thu Feb 24 10:34:52 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f1 192.168.10.11
[root@localhost ~]# 
2022-02-24 10:40:36 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f1
2022-02-24 10:40:39 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-24 10:40:39 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:40:44 - test_network_sriov_stress.py - [line:117] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-24 10:40:47 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-24 10:40:47 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-24 10:40:52 - test_network_sriov_stress.py - [line:131] - root - INFO - Succssfully Gotten vf_id list:

2022-02-24 10:40:55 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-02-24 10:40:55 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:41:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-24 10:41:04 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:41:09 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-24 10:41:12 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-24 10:41:12 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:41:17 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-24 10:41:17 - test_network_sriov_stress.py - [line:831] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-24 10:41:20 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-24 10:41:20 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-24 10:41:25 - test_network_sriov_stress.py - [line:842] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-24 10:41:28 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-24 10:41:29 - sshInstance.py - [line:50] - root - INFO - yes

2022-02-24 10:41:34 - test_network_sriov_stress.py - [line:191] - root - INFO - Default network is active? yes

2022-02-24 10:41:38 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:195509): [1;33mWARNING[0m **: [34m10:49:24.163[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-24 10:41:39 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-24 10:41:42 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest1
2022-02-24 10:41:46 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:195581): [1;33mWARNING[0m **: [34m10:49:32.192[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-24 10:41:47 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
2022-02-24 10:41:48 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-02-24 10:41:51 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest2
2022-02-24 10:41:54 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-24 10:41:54 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 10:41:59 - test_network_sriov_stress.py - [line:243] - root - ERROR - not found IP of VMtest1
2022-02-24 10:43:02 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-24 10:43:02 - sshInstance.py - [line:50] - root - INFO - 192.168.122.114/24

2022-02-24 10:43:07 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest1 IP: 192.168.122.114/24

2022-02-24 10:43:10 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-24 10:43:10 - sshInstance.py - [line:50] - root - INFO - 192.168.122.9/24

2022-02-24 10:43:15 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest2 IP: 192.168.122.9/24

2022-02-24 10:43:19 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.114
PING 192.168.122.114 (192.168.122.114) 56(84) bytes of data.
64 bytes from 192.168.122.114: icmp_seq=1 ttl=64 time=0.280 ms
2022-02-24 10:43:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=2 ttl=64 time=0.481 ms
2022-02-24 10:43:21 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=3 ttl=64 time=0.261 ms
2022-02-24 10:43:22 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=4 ttl=64 time=0.467 ms
2022-02-24 10:43:23 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=5 ttl=64 time=0.494 ms

--- 192.168.122.114 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4135ms
rtt min/avg/max/mdev = 0.261/0.396/0.494/0.105 ms
[root@WW25ICX2 ~]# 
2022-02-24 10:43:32 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.114
The authenticity of host '192.168.122.114 (192.168.122.114)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-02-24 10:43:41 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.114' (ECDSA) to the list of known hosts.
root@192.168.122.114's password: 
2022-02-24 10:43:50 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:51:33 PM EST
  System load:  0.0                Processes:             136
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.114
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Feb 22 22:05:38 2022 from 192.168.122.1
root@localhost:~# 
2022-02-24 10:43:59 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-24 10:44:05 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-24 10:44:11 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-24 10:44:16 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-24 10:44:22 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-02-24 10:44:25 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-24 10:44:31 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-24 10:44:41 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-24 10:44:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-24 10:44:59 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-24 10:45:08 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-24 10:45:17 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.114 closed.
[root@WW25ICX2 ~]# 
2022-02-24 10:45:24 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.9
PING 192.168.122.9 (192.168.122.9) 56(84) bytes of data.
64 bytes from 192.168.122.9: icmp_seq=1 ttl=64 time=0.317 ms
2022-02-24 10:45:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=2 ttl=64 time=0.266 ms
2022-02-24 10:45:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=3 ttl=64 time=0.392 ms
2022-02-24 10:45:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=4 ttl=64 time=0.488 ms
2022-02-24 10:45:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=5 ttl=64 time=0.259 ms

--- 192.168.122.9 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4117ms
rtt min/avg/max/mdev = 0.259/0.344/0.488/0.087 ms
[root@WW25ICX2 ~]# 
2022-02-24 10:45:37 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.9
The authenticity of host '192.168.122.9 (192.168.122.9)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-02-24 10:45:46 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.9' (ECDSA) to the list of known hosts.
root@192.168.122.9's password: 
2022-02-24 10:45:55 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:53:38 PM EST
  System load:  0.0                Processes:             140
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.9
  Swap usage:   0%

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 22 22:07:34 2022 from 192.168.122.1
root@localhost:~# 
2022-02-24 10:46:04 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-24 10:46:10 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-24 10:46:16 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-24 10:46:21 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-24 10:46:27 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-24 10:46:30 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-24 10:46:36 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-24 10:46:46 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-24 10:46:55 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-24 10:47:04 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-24 10:47:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-24 10:47:22 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.9 closed.
[root@WW25ICX2 ~]# 
2022-02-24 10:47:29 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.9
PING 192.168.122.9 (192.168.122.9) 56(84) bytes of data.
64 bytes from 192.168.122.9: icmp_seq=1 ttl=64 time=0.328 ms
2022-02-24 10:47:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=2 ttl=64 time=0.479 ms
2022-02-24 10:47:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=3 ttl=64 time=0.170 ms
2022-02-24 10:47:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=4 ttl=64 time=0.491 ms
2022-02-24 10:47:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.9: icmp_seq=5 ttl=64 time=0.475 ms

--- 192.168.122.9 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.170/0.388/0.491/0.126 ms
[root@WW25ICX2 ~]# 
2022-02-24 10:47:42 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.9
root@192.168.122.9's password: 
2022-02-24 10:47:51 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:55:34 PM EST
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.9
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 23 21:53:39 2022 from 192.168.122.1
root@localhost:~# 
2022-02-24 10:48:00 - sshInstance.py - [line:94] - root - INFO - nohup iperf -s -V&
[1] 1086
root@localhost:~# 
root@localhost:~# nohup: ignoring input and appending output to 'nohup.out'

2022-02-24 10:48:09 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.9 closed.
[root@WW25ICX2 ~]# 
2022-02-24 10:48:18 - sshInstance.py - [line:94] - root - INFO - nohup iperf -s -V&
[1] 155707
[root@localhost ~]# 
[root@localhost ~]# nohup: ignoring input and appending output to 'nohup.out'

2022-02-24 10:48:25 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.114
PING 192.168.122.114 (192.168.122.114) 56(84) bytes of data.
64 bytes from 192.168.122.114: icmp_seq=1 ttl=64 time=0.465 ms
2022-02-24 10:48:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=2 ttl=64 time=0.350 ms
2022-02-24 10:48:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=3 ttl=64 time=0.269 ms
2022-02-24 10:48:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=4 ttl=64 time=0.503 ms
2022-02-24 10:48:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.114: icmp_seq=5 ttl=64 time=0.466 ms

--- 192.168.122.114 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.269/0.410/0.503/0.090 ms
[root@WW25ICX2 ~]# 
2022-02-24 10:48:38 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.114
root@192.168.122.114's password: 
2022-02-24 10:48:47 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:56:31 PM EST
  System load:  0.0                Processes:             131
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.114
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Wed Feb 23 21:51:34 2022 from 192.168.122.1
root@localhost:~# 
2022-02-24 10:48:56 - sshInstance.py - [line:94] - root - INFO - rm -rf /tmp/*.txt
root@localhost:~# 
2022-02-24 10:59:16 - sshInstance.py - [line:94] - root - INFO - iperf -c 192.168.10.13 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_vm2.txt
root@localhost:~# 
2022-02-24 11:09:36 - sshInstance.py - [line:94] - root - INFO - iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_sut2.txt
root@localhost:~# 
2022-02-24 11:09:45 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.114 closed.
[root@WW25ICX2 ~]# 
2022-02-24 11:09:54 - sshInstance.py - [line:94] - root - INFO - rm -rf /tmp/*.txt
[root@WW25ICX2 ~]# 
2022-02-24 11:20:13 - sshInstance.py - [line:94] - root - INFO - iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv44_sut1_sut2.txt
[root@WW25ICX2 ~]# 
2022-02-24 11:20:22 - sshInstance.py - [line:94] - root - INFO - scp root@192.168.122.114:/tmp/*.txt /tmp
root@192.168.122.114's password: 
2022-02-24 11:20:31 - sshInstance.py - [line:94] - root - INFO - 
iperf_ipv4_vm1_sut2.txt                         0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_sut2.txt                       100%  298KB 128.7MB/s   00:00    
iperf_ipv4_vm1_vm2.txt                          0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_vm2.txt                        100%  298KB 162.3MB/s   00:00    
[root@WW25ICX2 ~]# 
2022-02-24 11:20:34 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: rm -rf /tmp/*.txt....
2022-02-24 11:20:34 - commonFunc.py - [line:30] - root - INFO - 
2022-02-24 11:20:34 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: rm -rf /tmp/*.txt
2022-02-24 11:20:34 - test_network_sriov_stress.py - [line:789] - root - INFO - Successfully iperf ipv4 vm1 vm2
2022-02-24 11:20:34 - test_network_sriov_stress.py - [line:789] - root - INFO - Successfully iperf ipv4 vm1 sut2
2022-02-24 11:20:34 - test_network_sriov_stress.py - [line:789] - root - INFO - Successfully iperf ipv4 sut1 sut2
2022-02-24 11:20:34 - test_network_sriov_stress.py - [line:790] - root - INFO - check ---end---
------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
INFO     root:sshInstance.py:50 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:103 pf_id was found: 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:803 format_pf_id is 0000\:4b\:00.0

INFO     root:test_network_sriov_stress.py:806 pf_id_key: 4b
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Thu Feb 24 10:45:41 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:297 Successfully assigned ip to ethernet: ens2f0
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Thu Feb 24 10:34:52 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f1 192.168.10.11
[root@localhost ~]# 
INFO     root:test_network_sriov_stress.py:297 Successfully assigned ip to ethernet: ens2f1
INFO     root:sshInstance.py:46 echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:117 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:46  lspci | grep "Virtual" | awk '{print $1;}'list
INFO     root:sshInstance.py:50 4b:01.0
4b:01.1
4b:01.2
4b:01.3

INFO     root:test_network_sriov_stress.py:131 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:46 modprobe vfio-pci

INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:164 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:164 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:831 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:46 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:50 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:842 Successfully get vf device id: 8086:1889
INFO     root:sshInstance.py:46 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 yes

INFO     root:test_network_sriov_stress.py:191 Default network is active? yes

INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:195509): [1;33mWARNING[0m **: [34m10:49:24.163[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:226 Successfully created a VM: VMtest1
INFO     root:sshInstance.py:71 virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:195581): [1;33mWARNING[0m **: [34m10:49:32.192[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
INFO     root:sshInstance.py:71 [root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:226 Successfully created a VM: VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:243 not found IP of VMtest1
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 192.168.122.114/24

INFO     root:test_network_sriov_stress.py:238 Successfully got VMtest1 IP: 192.168.122.114/24

INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 192.168.122.9/24

INFO     root:test_network_sriov_stress.py:238 Successfully got VMtest2 IP: 192.168.122.9/24

INFO     root:sshInstance.py:71 ping -c 5 192.168.122.114
PING 192.168.122.114 (192.168.122.114) 56(84) bytes of data.
64 bytes from 192.168.122.114: icmp_seq=1 ttl=64 time=0.280 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.114: icmp_seq=2 ttl=64 time=0.481 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.114: icmp_seq=3 ttl=64 time=0.261 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.114: icmp_seq=4 ttl=64 time=0.467 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.114: icmp_seq=5 ttl=64 time=0.494 ms

--- 192.168.122.114 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4135ms
rtt min/avg/max/mdev = 0.261/0.396/0.494/0.105 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.114
The authenticity of host '192.168.122.114 (192.168.122.114)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
INFO     root:sshInstance.py:94 yes
Warning: Permanently added '192.168.122.114' (ECDSA) to the list of known hosts.
root@192.168.122.114's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:51:33 PM EST
  System load:  0.0                Processes:             136
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.114
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Feb 22 22:05:38 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:94 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:336 successfully got vf pci id of vm1: 0000:00:05.0
INFO     root:sshInstance.py:94 ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:350 Successfully got vf device name of vm1: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 192.168.10.12
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:297 Successfully assigned ip to ethernet: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 down
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 up
root@localhost:~# 
INFO     root:sshInstance.py:94 nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.114 closed.
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.9
PING 192.168.122.9 (192.168.122.9) 56(84) bytes of data.
64 bytes from 192.168.122.9: icmp_seq=1 ttl=64 time=0.317 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.9: icmp_seq=2 ttl=64 time=0.266 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.9: icmp_seq=3 ttl=64 time=0.392 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.9: icmp_seq=4 ttl=64 time=0.488 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.9: icmp_seq=5 ttl=64 time=0.259 ms

--- 192.168.122.9 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4117ms
rtt min/avg/max/mdev = 0.259/0.344/0.488/0.087 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.9
The authenticity of host '192.168.122.9 (192.168.122.9)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
INFO     root:sshInstance.py:94 yes
Warning: Permanently added '192.168.122.9' (ECDSA) to the list of known hosts.
root@192.168.122.9's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:53:38 PM EST
  System load:  0.0                Processes:             140
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.9
  Swap usage:   0%

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Feb 22 22:07:34 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:94 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:336 successfully got vf pci id of vm1: 0000:00:05.0
INFO     root:sshInstance.py:94 ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:350 Successfully got vf device name of vm1: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 192.168.10.13
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:297 Successfully assigned ip to ethernet: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 down
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 up
root@localhost:~# 
INFO     root:sshInstance.py:94 nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.9 closed.
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.9
PING 192.168.122.9 (192.168.122.9) 56(84) bytes of data.
64 bytes from 192.168.122.9: icmp_seq=1 ttl=64 time=0.328 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.9: icmp_seq=2 ttl=64 time=0.479 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.9: icmp_seq=3 ttl=64 time=0.170 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.9: icmp_seq=4 ttl=64 time=0.491 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.9: icmp_seq=5 ttl=64 time=0.475 ms

--- 192.168.122.9 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.170/0.388/0.491/0.126 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.9
root@192.168.122.9's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:55:34 PM EST
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.9
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 23 21:53:39 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:94 nohup iperf -s -V&
[1] 1086
root@localhost:~# 
root@localhost:~# nohup: ignoring input and appending output to 'nohup.out'

INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.9 closed.
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 nohup iperf -s -V&
[1] 155707
[root@localhost ~]# 
[root@localhost ~]# nohup: ignoring input and appending output to 'nohup.out'

INFO     root:sshInstance.py:71 ping -c 5 192.168.122.114
PING 192.168.122.114 (192.168.122.114) 56(84) bytes of data.
64 bytes from 192.168.122.114: icmp_seq=1 ttl=64 time=0.465 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.114: icmp_seq=2 ttl=64 time=0.350 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.114: icmp_seq=3 ttl=64 time=0.269 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.114: icmp_seq=4 ttl=64 time=0.503 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.114: icmp_seq=5 ttl=64 time=0.466 ms

--- 192.168.122.114 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.269/0.410/0.503/0.090 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.114
root@192.168.122.114's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 23 Feb 2022 09:56:31 PM EST
  System load:  0.0                Processes:             131
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.114
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Wed Feb 23 21:51:34 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:94 rm -rf /tmp/*.txt
root@localhost:~# 
INFO     root:sshInstance.py:94 iperf -c 192.168.10.13 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_vm2.txt
root@localhost:~# 
INFO     root:sshInstance.py:94 iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_sut2.txt
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.114 closed.
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 rm -rf /tmp/*.txt
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv44_sut1_sut2.txt
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 scp root@192.168.122.114:/tmp/*.txt /tmp
root@192.168.122.114's password: 
INFO     root:sshInstance.py:94 
iperf_ipv4_vm1_sut2.txt                         0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_sut2.txt                       100%  298KB 128.7MB/s   00:00    
iperf_ipv4_vm1_vm2.txt                          0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_vm2.txt                        100%  298KB 162.3MB/s   00:00    
[root@WW25ICX2 ~]# 
INFO     root:commonFunc.py:16 starting to execute the cmd: rm -rf /tmp/*.txt....
INFO     root:commonFunc.py:30 
INFO     root:commonFunc.py:31 finished exeucting the cmd: rm -rf /tmp/*.txt
INFO     root:test_network_sriov_stress.py:789 Successfully iperf ipv4 vm1 vm2
INFO     root:test_network_sriov_stress.py:789 Successfully iperf ipv4 vm1 sut2
INFO     root:test_network_sriov_stress.py:789 Successfully iperf ipv4 sut1 sut2
INFO     root:test_network_sriov_stress.py:790 check ---end---
--------------------------- Captured stdout teardown ---------------------------
2022-02-24 11:20:37 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-02-24 11:20:38 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-02-24 11:20:43 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-24 11:20:46 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-02-24 11:20:46 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-02-24 11:20:51 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest2
2022-02-24 11:20:54 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-02-24 11:20:54 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-02-24 11:20:59 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-24 11:21:02 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-02-24 11:21:02 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-02-24 11:21:07 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest1
2022-02-24 11:21:10 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-24 11:21:12 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 11:21:20 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 0
2022-02-24 11:21:20 - sshInstance.py - [line:50] - root - INFO - 
2022-02-24 11:21:25 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] case ============================
---------------------------- Captured log teardown -----------------------------
INFO     root:sshInstance.py:46 virsh destroy VMtest2
INFO     root:sshInstance.py:50 Domain VMtest2 destroyed


INFO     root:test_network_sriov_stress.py:272 Successfully shut down the VM: VMtest2
INFO     root:sshInstance.py:46 virsh undefine VMtest2
INFO     root:sshInstance.py:50 Domain VMtest2 has been undefined


INFO     root:test_network_sriov_stress.py:282 Successfully removed the VM: VMtest2
INFO     root:sshInstance.py:46 virsh destroy VMtest1
INFO     root:sshInstance.py:50 Domain VMtest1 destroyed


INFO     root:test_network_sriov_stress.py:272 Successfully shut down the VM: VMtest1
INFO     root:sshInstance.py:46 virsh undefine VMtest1
INFO     root:sshInstance.py:50 Domain VMtest1 has been undefined


INFO     root:test_network_sriov_stress.py:282 Successfully removed the VM: VMtest1
INFO     root:sshInstance.py:46 echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 ifconfig ens2f0 0
INFO     root:sshInstance.py:50 
INFO     root:NicTestFixture.py:32 ============================ end of run test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] case ============================
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:57
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_iperf_client_4hour.py:57: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:91
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_iperf_client_4hour.py:91: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:66
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_mtu.py:66: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:105
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_mtu.py:105: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:376
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_network_sriov_stress.py:376: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:493
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_network_sriov_stress.py:493: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:792
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_network_sriov_stress.py:792: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:75
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_nics.py:75: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:99
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_nics.py:99: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:121
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_nics.py:121: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:147
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_nics.py:147: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:185
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_nics.py:185: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:209
  /root/.jenkins/workspace/test-test-iperf-SRIOV-ipv4-stress-2hours/npxtester/Tests/testNics/test_nics.py:209: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/sriov_iperfvf_2hours_ipv4.html -
=========================== short test summary info ============================
ERROR npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img]
===== 1 passed, 15 deselected, 13 warnings, 1 error in 2512.93s (0:41:52) ======
[8mha:////4JadWPtzQEFx9CzixTlssp2D6uuorSv3wnTa6h1wuGrmAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiISEKRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g3QKkBhvgAAAA==[0m[Pipeline] }
[8mha:////4Goa9rseL6gCK8+j51lIjOVJAeE64BF71YmRtb4KtKxFAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiIQokRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g2TqBHnvgAAAA==[0m[Pipeline] // stage
[8mha:////4AK444efjkykafC1HGbgxn6nPSQkL/HNauaXETS7R91oAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIRqEqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A+OvzUfBAAAA[0m[Pipeline] stage
[8mha:////4EqpMgzslAWPDRl1bp4feAKRfPoiBNazp8uDBURuqJGsAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycogUwYRQJ9aoCycITQhJo/9LkpJOnIircQcClZjwYNmWrPd8QRU8NOQ1swp7g6EzbHCjzokl8v3FUWKWzqwjDOQUa1VqSarjXFuKCmYVJSw4LBV2joJBHWHFrbiL2gnU9Sn6vB04lEbe4AEFz+QofPyWycP6OspA+OP8BcA0RCi3+2y7zedZvQH4j6CMwgAAAA==[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4M0P44+7KKMsBaEAgOPFTC6kJ9gOLfRk2xH1/27GZQUTAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICokRUaS03vMDExjix7oztkFS8iK/xBwKRqNhitbPNPF+wTBGOHC22hjpHqXEYfG+nhQPH7uJ5wJbP2DAl9galGSRrU88oORuYU5SwELAy1HhOjmyGtWjVXVVeka1OOU7fQUDp9A0eUIjJnFXMXxgjbK69Tkw/z18BjCFkKPe7T23ftwcfeL4AAAA=[0m[Pipeline] }
[8mha:////4ME5TlbHmzr5qdpFH/mkGWKP7XmPx2rIKtfLHFMqug00AAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIihQohqrRWGl5gYmOcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThwM9poGS7Gz6N1o8sKJw3B1PGHPF+yYIjuNrZ5aVrpZsOWkYUlRwkrARlPnOFoyCbailw9ZOUmmOqeQv6OA0qo7PKEQ2ZxkSF+YA+xuo4pMP89fAczeJyj3da768AH8/EyevgAAAA==[0m[Pipeline] // stage
[8mha:////4Fe3eqQpZrcpnjrK1jN1d/MbMZ7ufuA8IOyekGcoBhh7AAAAoh+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIU2DlWthkaTxAhxkBmF5NFqDyRV/MOMjJj5a/+e817vbFOEUeOTrWWOk+p9qoPg5ufGjl218CjavmiaqbEwarKjhU39rRgxWKxLMux0thYqgMnT06w1a15mCIYcsVZ4uwOGrlv7ngi03NZTJQvTBG729Akpl/nbwBT3wvyshRk+w9e8C3YvQAAAA==[0m[Pipeline] }
[8mha:////4Fl8XDDe7BXdXsXj7uDbwTY/cDAcq+nOEdlmagh5XH3DAAAAoh+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIU2DlWthkaTxAhxkBmF5NFqDyRV/MOMjJj5a/+e817vbFOEUeOTrWWOk+p9qoPg5ufGjl218CjavmiaqbEwarKjhU39rRgxWKxLMux0thYqgMnT06w1a15mCIYcsVZ4uwOGrlv7ngi03NZTJQvTBG729Akpl/nbwBT3wvyci/Iyg/tuWn0vQAAAA==[0m[Pipeline] // node
[8mha:////4Oc/DLR66YI1esGEMsMY02BciEZxcpD10WBUR6yLP96pAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRQFSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLcXZNsPy6AOvr0AAAA=[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
