Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/spr-test-nicGold
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/spr-test-nicGold/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/spr-test-nicGold/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/spr-test-nicGold/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"5.15.0-1003-realtime"},"dpdk_dir":"/root/dpdk-stable-20.11.3/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.239.183.130","pf1":"enp111s0f0","os":"RHEL"},"pkg_generator":{"host":"10.239.182.88","pf1":"ens785f0"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4Dqouna/UALz1cds/DYDIib12lRO4R4U9QQgmUx/wyv5AAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYgEJMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAnLfKUwgAAAA==[0m[Pipeline] script
[8mha:////4JUhH4fIWh5icAEY6zBr3HRHHu0lnMalVyM2fPsu3/3sAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYgIhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD0QKVszCAAAA[0m[Pipeline] {
[8mha:////4PJRxj8hD/CuSHgtWDRwAQ67XTdBRcldvWih24U4ysBWAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCoEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDREKHeHXPvt8AHN/bm5vgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics -s -m nicGold --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nicGold_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 17 items / 13 deselected / 4 selected

npxtester/Tests/testNics/test_mtu.py 2022-03-20 03:30:23 - NicTestFixture.py - [line:30] - root - INFO - ============================ Starting to run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-20 03:30:23 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-03-20 03:30:23 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-20 03:30:23 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:30:23 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-20 03:30:24 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-20 03:30:24 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:30:24 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-20 03:30:24 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-20 03:30:27 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-20 03:30:27 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:30:35 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-20 03:30:35 - sshInstance.py - [line:50] - root - INFO - rmmod: ERROR: Module ice is in use by: irdma

2022-03-20 03:30:43 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-20 03:30:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:30:51 - sshInstance.py - [line:46] - root - INFO - ethtool -i enp111s0f0
2022-03-20 03:30:51 - sshInstance.py - [line:50] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-20 03:30:59 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 mtu 1500
2022-03-20 03:30:59 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:31:07 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0 mtu 1500
2022-03-20 03:31:07 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:31:15 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0
2022-03-20 03:31:15 - sshInstance.py - [line:50] - root - INFO - enp111s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 100  bytes 34200 (34.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 120  bytes 36992 (36.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-20 03:31:24 - sshInstance.py - [line:71] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Sun Mar 20 01:52:43 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption. (Dot11)[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | Craft packets before they craft[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   | you.[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |                      -- Socrate[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m[34m[1m   |[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-03-20 03:31:24 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:31:31 - sshInstance.py - [line:71] - root - INFO - sendp([Ether(dst="b4:96:91:a0:21:40")/IP(len=46)/Raw(load='X'*14480)],iface="ens785f0")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-03-20 03:31:31 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:31:34 - test_mtu.py - [line:92] - root - INFO - success to send package to network
2022-03-20 03:31:38 - sshInstance.py - [line:71] - root - INFO - sendp([Ether(dst="b4:96:91:a0:21:40")/IP(len=46)/Raw(load='X'*15500)],iface="ens785f0")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-03-20 03:31:38 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:31:41 - test_mtu.py - [line:102] - root - INFO - result is right
.2022-03-20 03:31:44 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 mtu 1500
2022-03-20 03:31:44 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:31:52 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0 mtu 1500
2022-03-20 03:31:52 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:32:00 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/enp111s0f0/device/sriov_numvfs
2022-03-20 03:32:00 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:32:08 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-20 03:32:08 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:32:13 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-20 03:32:13 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-20/test_PI_Networking_Jumbo_Packet_CVL_03_30_23
2022-03-20 03:32:16 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-20 03:32:16 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:32:21 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-20 03:32:21 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-03-20 03:32:21 - NicTestFixture.py - [line:34] - root - INFO - ============================ end of run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-20 03:32:21 - NicTestFixture.py - [line:30] - root - INFO - ============================ Starting to run test_PI_Networking_MTU_set_CVL case ============================
2022-03-20 03:32:21 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-03-20 03:32:21 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-20 03:32:21 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:32:21 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-20 03:32:21 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-20 03:32:22 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:32:22 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-20 03:32:22 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-20 03:32:25 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-20 03:32:25 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:32:33 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-20 03:32:33 - sshInstance.py - [line:50] - root - INFO - rmmod: ERROR: Module ice is in use by: irdma

2022-03-20 03:32:41 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-20 03:32:41 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:32:49 - sshInstance.py - [line:46] - root - INFO - ethtool -i enp111s0f0
2022-03-20 03:32:49 - sshInstance.py - [line:50] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-20 03:32:57 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 mtu 1500
2022-03-20 03:32:57 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:33:05 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0 mtu 2000
2022-03-20 03:33:08 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:33:16 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0
2022-03-20 03:33:16 - sshInstance.py - [line:50] - root - INFO - enp111s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 101  bytes 35714 (35.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 122  bytes 37680 (37.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-20 03:33:25 - sshInstance.py - [line:71] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Sun Mar 20 03:42:59 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption. (Dot11)[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | Wanna support scapy? Star us on[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   | GitHub![0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |             -- Satoshi Nakamoto[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m[34m[1m   |[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-03-20 03:33:25 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:33:32 - sshInstance.py - [line:71] - root - INFO - sendp([Ether(dst="b4:96:91:a0:21:40")/IP(len=46)/Raw(load='X'*18890)],iface="ens785f0")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-03-20 03:33:32 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:33:35 - test_mtu.py - [line:132] - root - INFO - success to send package to network
2022-03-20 03:33:39 - sshInstance.py - [line:71] - root - INFO - sendp([Ether(dst="b4:96:91:a0:21:40")/IP(len=46)/Raw(load='X'*20010)],iface="ens785f0")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-03-20 03:33:39 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:33:42 - test_mtu.py - [line:142] - root - INFO - result is right
.2022-03-20 03:33:45 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 mtu 1500
2022-03-20 03:33:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:33:53 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0 mtu 1500
2022-03-20 03:33:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:34:04 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/enp111s0f0/device/sriov_numvfs
2022-03-20 03:34:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:34:12 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-20 03:34:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:34:17 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-20 03:34:17 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-20/test_PI_Networking_MTU_set_CVL_03_32_21
2022-03-20 03:34:20 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-20 03:34:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:34:25 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-20 03:34:25 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-03-20 03:34:25 - NicTestFixture.py - [line:34] - root - INFO - ============================ end of run test_PI_Networking_MTU_set_CVL case ============================
                                  [ 50%]
npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-20 03:34:25 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-03-20 03:34:25 - NicTestFixture.py - [line:30] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-03-20 03:34:25 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-20 03:34:25 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-20 03:34:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:34:26 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-20 03:34:26 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-20 03:34:26 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-20 03:34:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:34:26 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-20 03:34:29 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-20 03:34:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:34:37 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-20 03:34:37 - sshInstance.py - [line:50] - root - INFO - rmmod: ERROR: Module ice is in use by: irdma

2022-03-20 03:34:45 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-20 03:34:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:34:53 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 up
2022-03-20 03:34:53 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:35:01 - sshInstance.py - [line:46] - root - INFO - ethtool -i enp111s0f0
2022-03-20 03:35:01 - sshInstance.py - [line:50] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-20 03:35:09 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0
2022-03-20 03:35:09 - sshInstance.py - [line:50] - root - INFO - enp111s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 106  bytes 37424 (37.4 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 123  bytes 38024 (38.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-20 03:35:17 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0
2022-03-20 03:35:17 - sshInstance.py - [line:50] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.11  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 6777514749  bytes 10230469285659 (9.3 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 113762991  bytes 7510224772 (6.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-20 03:35:22 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-20 03:35:25 - sshInstance.py - [line:46] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -s | grep enp111s0f0 | awk '{print $1;}'
2022-03-20 03:35:26 - sshInstance.py - [line:50] - root - INFO - 0000:6f:00.0

2022-03-20 03:35:31 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:6f:00.0

2022-03-20 03:35:31 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:6f\:00.0

2022-03-20 03:35:31 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 6f
2022-03-20 03:35:37 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:35:37 - sshInstance.py - [line:96] - root - INFO - Last login: Sat Mar 19 19:43:45 2022 from 10.112.97.60
[?2004hroot@npx-SPR-automation:~# ifconfig enp111s0f0 192.168.10.10
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:35:40 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: enp111s0f0
2022-03-20 03:35:46 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:35:46 - sshInstance.py - [line:96] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Mar 20 03:45:01 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
2022-03-20 03:35:49 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens785f0
2022-03-20 03:35:52 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/enp111s0f0/device/sriov_numvfs
2022-03-20 03:35:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:36:01 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-20 03:36:04 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-20 03:36:04 - sshInstance.py - [line:50] - root - INFO - 6f:01.0
6f:01.1
6f:01.2
6f:01.3

2022-03-20 03:36:09 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-20 03:36:12 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-20 03:36:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:36:20 - sshInstance.py - [line:46] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.0
2022-03-20 03:36:22 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:36:27 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-20 03:36:30 - sshInstance.py - [line:46] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.1
2022-03-20 03:36:32 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:36:37 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-20 03:36:37 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-20 03:36:40 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-20 03:36:40 - sshInstance.py - [line:50] - root - INFO - 0000:6f:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-20 03:36:45 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-20 03:36:48 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-20 03:36:48 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-20 03:36:53 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-20 03:36:57 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-20 03:36:59 - sshInstance.py - [line:71] - root - INFO - ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:37:29 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:37:32 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:37:32 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-20 03:37:36 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-20 03:37:37 - sshInstance.py - [line:71] - root - INFO - ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:38:08 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:38:11 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:38:11 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-20 03:38:15 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-20 03:38:16 - sshInstance.py - [line:71] - root - INFO - ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:38:47 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:38:50 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:38:50 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
F2022-03-20 03:38:53 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-20 03:38:53 - sshInstance.py - [line:50] - root - INFO - error: Failed to destroy domain 'VMtest2'
error: Requested operation is not valid: domain is not running


2022-03-20 03:38:58 - test_network_sriov_stress.py - [line:279] - root - ERROR - Failed to shut down the VM VMtest2
2022-03-20 03:39:01 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-20 03:39:01 - sshInstance.py - [line:50] - root - INFO - error: Failed to destroy domain 'VMtest1'
error: Requested operation is not valid: domain is not running


2022-03-20 03:39:06 - test_network_sriov_stress.py - [line:279] - root - ERROR - Failed to shut down the VM VMtest1
2022-03-20 03:39:09 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/enp111s0f0/device/sriov_numvfs
2022-03-20 03:39:13 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:39:21 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 0
2022-03-20 03:39:21 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:39:29 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0 0
2022-03-20 03:39:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:39:37 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-20 03:39:37 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:39:42 - test_network_sriov_stress.py - [line:82] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-20 03:39:42 - test_network_sriov_stress.py - [line:84] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-20/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img]_03_34_25
2022-03-20 03:39:45 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-20 03:39:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:39:50 - test_network_sriov_stress.py - [line:86] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-20 03:39:50 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-20 03:39:50 - NicTestFixture.py - [line:34] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
                  [ 75%]
npxtester/Tests/testNics/test_nics.py 2022-03-20 03:39:50 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-03-20 03:39:50 - NicTestFixture.py - [line:30] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-03-20 03:39:50 - test_nics.py - [line:20] - root - INFO - this is Test_Nics setup.
2022-03-20 03:39:50 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-20 03:39:50 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:39:51 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-20 03:39:51 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-20 03:39:51 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:39:51 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-20 03:39:51 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-20 03:39:54 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-20 03:39:54 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:40:02 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-20 03:40:02 - sshInstance.py - [line:50] - root - INFO - rmmod: ERROR: Module ice is in use by: irdma

2022-03-20 03:40:10 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-20 03:40:10 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:40:18 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 up
2022-03-20 03:40:18 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:40:26 - sshInstance.py - [line:46] - root - INFO - ethtool -i enp111s0f0 | grep ^version:
2022-03-20 03:40:26 - sshInstance.py - [line:50] - root - INFO - version: 5.15.0-1003-realtime

2022-03-20 03:40:34 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0
2022-03-20 03:40:34 - sshInstance.py - [line:50] - root - INFO - enp111s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 111  bytes 39134 (39.1 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 128  bytes 39744 (39.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-20 03:40:42 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0
2022-03-20 03:40:42 - sshInstance.py - [line:50] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 6777514755  bytes 10230469287723 (9.3 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 113762998  bytes 7510226602 (6.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-20 03:40:50 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/enp111s0f0/device/sriov_numvfs
2022-03-20 03:40:54 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:41:02 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0 192.168.10.11

2022-03-20 03:41:02 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:41:10 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0v0 192.168.10.11
2022-03-20 03:41:10 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:41:18 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0v1 192.168.10.12
2022-03-20 03:41:18 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:41:26 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0v2 192.168.10.13
2022-03-20 03:41:26 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:41:34 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0v3 192.168.10.14
2022-03-20 03:41:34 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:41:42 - sshInstance.py - [line:46] - root - INFO - ping -c 5 192.168.10.11
2022-03-20 03:41:46 - sshInstance.py - [line:50] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.023 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.015 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.006 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.011 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.007 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4114ms
rtt min/avg/max/mdev = 0.006/0.012/0.023/0.006 ms

2022-03-20 03:41:54 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0v0 up
2022-03-20 03:41:54 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:42:02 - sshInstance.py - [line:46] - root - INFO - nmcli device connect enp111s0f0v0
2022-03-20 03:42:02 - sshInstance.py - [line:50] - root - INFO - bash: line 1: nmcli: command not found

2022-03-20 03:42:10 - sshInstance.py - [line:46] - root - INFO - ping6 -c 5 -I enp111s0f0v0 fe80::b696:91ff:fea0:2170
2022-03-20 03:42:15 - sshInstance.py - [line:50] - root - INFO - ping6: Warning: source address might be selected on device other than: enp111s0f0v0
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: enp111s0f0v0: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v0: icmp_seq=1 ttl=64 time=0.345 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v0: icmp_seq=2 ttl=64 time=0.139 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v0: icmp_seq=3 ttl=64 time=0.134 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v0: icmp_seq=4 ttl=64 time=0.136 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v0: icmp_seq=5 ttl=64 time=0.136 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4108ms
rtt min/avg/max/mdev = 0.134/0.178/0.345/0.083 ms

2022-03-20 03:42:23 - sshInstance.py - [line:46] - root - INFO - ping -c 5 192.168.10.11
2022-03-20 03:42:27 - sshInstance.py - [line:50] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.019 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.016 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.007 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.005 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.006 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4078ms
rtt min/avg/max/mdev = 0.005/0.010/0.019/0.005 ms

2022-03-20 03:42:35 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0v1 up
2022-03-20 03:42:35 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:42:43 - sshInstance.py - [line:46] - root - INFO - nmcli device connect enp111s0f0v1
2022-03-20 03:42:43 - sshInstance.py - [line:50] - root - INFO - bash: line 1: nmcli: command not found

2022-03-20 03:42:51 - sshInstance.py - [line:46] - root - INFO - ping6 -c 5 -I enp111s0f0v1 fe80::b696:91ff:fea0:2170
2022-03-20 03:42:55 - sshInstance.py - [line:50] - root - INFO - ping6: Warning: source address might be selected on device other than: enp111s0f0v1
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: enp111s0f0v1: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v1: icmp_seq=1 ttl=64 time=0.347 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v1: icmp_seq=2 ttl=64 time=0.138 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v1: icmp_seq=3 ttl=64 time=0.136 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v1: icmp_seq=4 ttl=64 time=0.143 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v1: icmp_seq=5 ttl=64 time=0.135 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4108ms
rtt min/avg/max/mdev = 0.135/0.179/0.347/0.083 ms

2022-03-20 03:43:03 - sshInstance.py - [line:46] - root - INFO - ping -c 5 192.168.10.11
2022-03-20 03:43:07 - sshInstance.py - [line:50] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.019 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.014 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.006 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.006 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.005 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4078ms
rtt min/avg/max/mdev = 0.005/0.010/0.019/0.005 ms

2022-03-20 03:43:15 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0v2 up
2022-03-20 03:43:15 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:43:23 - sshInstance.py - [line:46] - root - INFO - nmcli device connect enp111s0f0v2
2022-03-20 03:43:23 - sshInstance.py - [line:50] - root - INFO - bash: line 1: nmcli: command not found

2022-03-20 03:43:31 - sshInstance.py - [line:46] - root - INFO - ping6 -c 5 -I enp111s0f0v2 fe80::b696:91ff:fea0:2170
2022-03-20 03:43:35 - sshInstance.py - [line:50] - root - INFO - ping6: Warning: source address might be selected on device other than: enp111s0f0v2
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: enp111s0f0v2: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v2: icmp_seq=1 ttl=64 time=0.346 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v2: icmp_seq=2 ttl=64 time=0.138 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v2: icmp_seq=3 ttl=64 time=0.142 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v2: icmp_seq=4 ttl=64 time=0.135 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v2: icmp_seq=5 ttl=64 time=0.133 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4111ms
rtt min/avg/max/mdev = 0.133/0.178/0.346/0.083 ms

2022-03-20 03:43:43 - sshInstance.py - [line:46] - root - INFO - ping -c 5 192.168.10.11
2022-03-20 03:43:47 - sshInstance.py - [line:50] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.018 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.007 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.006 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.005 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.004 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4078ms
rtt min/avg/max/mdev = 0.004/0.008/0.018/0.005 ms

2022-03-20 03:43:55 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0v3 up
2022-03-20 03:43:55 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:44:03 - sshInstance.py - [line:46] - root - INFO - nmcli device connect enp111s0f0v3
2022-03-20 03:44:03 - sshInstance.py - [line:50] - root - INFO - bash: line 1: nmcli: command not found

2022-03-20 03:44:11 - sshInstance.py - [line:46] - root - INFO - ping6 -c 5 -I enp111s0f0v3 fe80::b696:91ff:fea0:2170
2022-03-20 03:44:15 - sshInstance.py - [line:50] - root - INFO - ping6: Warning: source address might be selected on device other than: enp111s0f0v3
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: enp111s0f0v3: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v3: icmp_seq=1 ttl=64 time=0.376 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v3: icmp_seq=2 ttl=64 time=0.136 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v3: icmp_seq=3 ttl=64 time=0.131 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v3: icmp_seq=4 ttl=64 time=0.137 ms
64 bytes from fe80::b696:91ff:fea0:2170%enp111s0f0v3: icmp_seq=5 ttl=64 time=0.133 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4110ms
rtt min/avg/max/mdev = 0.131/0.182/0.376/0.096 ms

.2022-03-20 03:44:23 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/enp111s0f0/device/sriov_numvfs
2022-03-20 03:44:31 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:44:39 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/enp111s0f0/device/sriov_numvfs
2022-03-20 03:44:39 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:44:47 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 0
2022-03-20 03:44:47 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:44:55 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0 0
2022-03-20 03:44:55 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:45:03 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-20 03:45:03 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:45:08 - test_nics.py - [line:78] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-20 03:45:08 - test_nics.py - [line:80] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-20/test_gold_PI_Networking_SRIOV_CheckDevice_03_39_50
2022-03-20 03:45:11 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-20 03:45:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:45:16 - test_nics.py - [line:82] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-20 03:45:16 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-20 03:45:16 - test_nics.py - [line:84] - root - INFO - this is Test_Nics teardown
2022-03-20 03:45:16 - NicTestFixture.py - [line:34] - root - INFO - ============================ end of run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
                                  [100%]

=================================== FAILURES ===================================
_ Test_Network_SRIOV_Stress.test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] _

self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7fa27450af98>
vm1_image = 'uvm1.img', vm2_image = 'uvm2.img'

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicGold
    @pytest.mark.nicSriov5times
    @pytest.mark.parametrize('vm1_image, vm2_image', vm_image)
    def test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest(self, vm1_image, vm2_image):
        for j in range(1, 6):
            logging.info(
                "\n\n********************************************************Stress Disable and Enable for {} time when VF is Assigned VM guest.*************************************************************\n\n".format(
                    j))
            # get pf id: 0000:xx:xx.x
            pf_id, status = self.get_pf_id(self.pf_name)
            # transfer pf_id to 0000\:00\:00.0 format
            if not pf_id:
                assert 200 == status
            else:
                pf_id_format = pf_id.replace(":", "\\:", 2)
                logging.info("format_pf_id is {}".format(pf_id_format))
                # get the number key of pf_id
                pf_id_key = pf_id.split(":")[1]
                logging.info("pf_id_key: {}".format(pf_id_key))
                # assign IP to PF in SUT and sut2
                pf_ip = "192.168.10.10"
                sut2_ip = "192.168.10.11"
                assert 200 == self.assign_ip_ehternet(self.session, pf_ip, self.pf_name)
                assert 200 == self.assign_ip_ehternet(self.session2, sut2_ip, self.sut2_info["pf1"])
                # virtulize the pf to vfs
                assert 200 == self.virtualize_pf_to_vfs(self.pf_name)
                # get vf ids
                vf_id_list, status = self.get_vf_ids(pf_id_key)
                vf_id_list = [i.strip() for i in vf_id_list]
                if status == 200:
                    # modprobe vfio-pci
                    assert 200 == self.modprobe("vfio-pci")
                    # bind vf with vfio-pci
                    host_dev_id_list, status = self.bind_vf_to_vfio_pci(vf_id_list)
                    assert 200 == status
                else:
                    assert 200 == status
                # get vF device ida
                # tmp code
                cmd = "lspci -Dnn | grep %s" % (vf_id_list[1])
                logging.info(cmd)
                vf_device_id = ""
                vf_device_id_rs, error = self.ssh_sut.ssh_exec_cmd(self.client, cmd)
                if vf_device_id_rs:
                    st = False
                    vf_device_id = None
                    for one in vf_device_id_rs.split(" "):
                        one = " " + one + " "
                        if one.find(" [") > -1 and one.find("] ") > -1 and one.find(":") > -1:
                            vf_device_id = one.replace("[", "").replace("]", "").strip()
                    if not vf_device_id: assert 200 == 400, "vf_device_id is not found"
                    logging.info("Successfully get vf device id: {}".format(vf_device_id))
                    assert 200 == 200
                else:
                    logging.error("Fail to get vf device id.")
                    assert 200 == 400
    
                # set network
                status = self.default_network_isActive(self.defult_network)
                if status == "no":
                    assert 200 == self.start_default_network(self.defult_network)
    
                # start VMs
>               assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "5900")
E               AssertionError: assert 200 == 400
E                +  where 400 = <bound method Test_Network_SRIOV_Stress.create_vm of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7fa27450af98>>('uvm1.img', 'pci_0000_6f_01_0', 'VMtest1', '5900')
E                +    where <bound method Test_Network_SRIOV_Stress.create_vm of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7fa27450af98>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7fa27450af98>.create_vm
E                +    and   'VMtest1' = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7fa27450af98>.vm1_name

npxtester/Tests/testNics/test_network_sriov_stress.py:444: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-03-20 03:34:25 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-03-20 03:34:25 - NicTestFixture.py - [line:30] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-03-20 03:34:25 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-20 03:34:25 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-20 03:34:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:34:26 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-20 03:34:26 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-20 03:34:26 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-20 03:34:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-20 03:34:26 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-20 03:34:29 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-20 03:34:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:34:37 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-20 03:34:37 - sshInstance.py - [line:50] - root - INFO - rmmod: ERROR: Module ice is in use by: irdma

2022-03-20 03:34:45 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-20 03:34:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:34:53 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0 up
2022-03-20 03:34:53 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:35:01 - sshInstance.py - [line:46] - root - INFO - ethtool -i enp111s0f0
2022-03-20 03:35:01 - sshInstance.py - [line:50] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-20 03:35:09 - sshInstance.py - [line:46] - root - INFO - ifconfig enp111s0f0
2022-03-20 03:35:09 - sshInstance.py - [line:50] - root - INFO - enp111s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 106  bytes 37424 (37.4 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 123  bytes 38024 (38.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-20 03:35:17 - sshInstance.py - [line:46] - root - INFO - ifconfig ens785f0
2022-03-20 03:35:17 - sshInstance.py - [line:50] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.11  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 6777514749  bytes 10230469285659 (9.3 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 113762991  bytes 7510224772 (6.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


------------------------------ Captured log setup ------------------------------
INFO     root:NicTestFixture.py:20 test -------
----------------------------- Captured stdout call -----------------------------
2022-03-20 03:35:22 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-20 03:35:25 - sshInstance.py - [line:46] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -s | grep enp111s0f0 | awk '{print $1;}'
2022-03-20 03:35:26 - sshInstance.py - [line:50] - root - INFO - 0000:6f:00.0

2022-03-20 03:35:31 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:6f:00.0

2022-03-20 03:35:31 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:6f\:00.0

2022-03-20 03:35:31 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 6f
2022-03-20 03:35:37 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:35:37 - sshInstance.py - [line:96] - root - INFO - Last login: Sat Mar 19 19:43:45 2022 from 10.112.97.60
[?2004hroot@npx-SPR-automation:~# ifconfig enp111s0f0 192.168.10.10
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:35:40 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: enp111s0f0
2022-03-20 03:35:46 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:35:46 - sshInstance.py - [line:96] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Mar 20 03:45:01 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
2022-03-20 03:35:49 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens785f0
2022-03-20 03:35:52 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/enp111s0f0/device/sriov_numvfs
2022-03-20 03:35:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:36:01 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-20 03:36:04 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-20 03:36:04 - sshInstance.py - [line:50] - root - INFO - 6f:01.0
6f:01.1
6f:01.2
6f:01.3

2022-03-20 03:36:09 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-20 03:36:12 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-20 03:36:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:36:20 - sshInstance.py - [line:46] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.0
2022-03-20 03:36:22 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:36:27 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-20 03:36:30 - sshInstance.py - [line:46] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.1
2022-03-20 03:36:32 - sshInstance.py - [line:50] - root - INFO - 
2022-03-20 03:36:37 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-20 03:36:37 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-20 03:36:40 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-20 03:36:40 - sshInstance.py - [line:50] - root - INFO - 0000:6f:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-20 03:36:45 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-20 03:36:48 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-20 03:36:48 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-20 03:36:53 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-20 03:36:57 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-20 03:36:59 - sshInstance.py - [line:71] - root - INFO - ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:37:29 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:37:32 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:37:32 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-20 03:37:36 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-20 03:37:37 - sshInstance.py - [line:71] - root - INFO - ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:38:08 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:38:11 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:38:11 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-20 03:38:15 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-20 03:38:16 - sshInstance.py - [line:71] - root - INFO - ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:38:47 - sshInstance.py - [line:94] - root - INFO - --cmd is end--
2022-03-20 03:38:50 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
2022-03-20 03:38:50 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
------------------------------ Captured log call -------------------------------
INFO     root:test_network_sriov_stress.py:388 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


INFO     root:sshInstance.py:46 /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -s | grep enp111s0f0 | awk '{print $1;}'
INFO     root:sshInstance.py:50 0000:6f:00.0

INFO     root:test_network_sriov_stress.py:111 pf_id was found: 0000:6f:00.0

INFO     root:test_network_sriov_stress.py:396 format_pf_id is 0000\:6f\:00.0

INFO     root:test_network_sriov_stress.py:399 pf_id_key: 6f
INFO     root:sshInstance.py:94 --cmd is end--
INFO     root:sshInstance.py:96 Last login: Sat Mar 19 19:43:45 2022 from 10.112.97.60
[?2004hroot@npx-SPR-automation:~# ifconfig enp111s0f0 192.168.10.10
[?2004l[?2004hroot@npx-SPR-automation:~# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: enp111s0f0
INFO     root:sshInstance.py:94 --cmd is end--
INFO     root:sshInstance.py:96 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Mar 20 03:45:01 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens785f0
INFO     root:sshInstance.py:46 echo 4 > /sys/class/net/enp111s0f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:125 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:46  lspci | grep "Virtual" | awk '{print $1;}'list
INFO     root:sshInstance.py:50 6f:01.0
6f:01.1
6f:01.2
6f:01.3

INFO     root:test_network_sriov_stress.py:139 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:46 modprobe vfio-pci

INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.0
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:46 /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.1
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:421 lspci -Dnn | grep 6f:01.1
INFO     root:sshInstance.py:46 lspci -Dnn | grep 6f:01.1
INFO     root:sshInstance.py:50 0000:6f:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:432 Successfully get vf device id: 8086:1889
INFO     root:sshInstance.py:46 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 yes

INFO     root:test_network_sriov_stress.py:198 Default network is active? yes

INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
INFO     root:sshInstance.py:71 ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:94 --cmd is end--
ERROR    root:test_network_sriov_stress.py:230 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
ERROR    root:test_network_sriov_stress.py:231 Failed to create a VM: 
INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
INFO     root:sshInstance.py:71 ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:94 --cmd is end--
ERROR    root:test_network_sriov_stress.py:230 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
ERROR    root:test_network_sriov_stress.py:231 Failed to create a VM: 
INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
INFO     root:sshInstance.py:71 ERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:94 --cmd is end--
ERROR    root:test_network_sriov_stress.py:230 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004lERROR    
--os-variant/--osinfo OS name is required, but no value was
set or detected.

This is now a fatal error. Specifying an OS name is required
for modern, performant, and secure virtual machine defaults.

You can see a full list of possible OS name values with:

   virt-install --osinfo list

If your Linux distro is not listed, try one of generic values
such as: linux2020, linux2018, linux2016

If you just need to get the old behavior back, you can use:

  --osinfo detect=on,require=off

Or export VIRTINSTALL_OSINFO_DISABLE_REQUIRE=1

[?2004hroot@npx-SPR-automation:~# 
ERROR    root:test_network_sriov_stress.py:231 Failed to create a VM:
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:70
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_iperf_client_4hour.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:108
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_iperf_client_4hour.py:108: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:70
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:109
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:109: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:382
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:382: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:500
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:500: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:799
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:799: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:91
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:91: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:118
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:118: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:150
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:150: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:221
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:221: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:247
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:247: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nicGold_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img]
===== 1 failed, 3 passed, 13 deselected, 14 warnings in 893.49s (0:14:53) ======
[8mha:////4DDaF6xD1n97fCJC17HEPtC4MvFSxjBMoUPdpyGs71EZAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIioEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDREKHeHXPvt8AGMzKKgvgAAAA==[0m[Pipeline] echo
1
[8mha:////4JdwCG2vyNU1vR63Cq0h1I9fweuZdBzoUYFbNZMa07ZpAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIihQohqrRWGl5gYmOcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThwM9poGS7Gz6N1o8sKJw3B1PGHPF+yYIjuNrZ5aVrpZsOWkYUlRwkrARlPnOFoyCbailw9ZOUmmOqeQv6OA0qo7PKEQ2ZxkSF+YA+xuo4pMP89fAcw+QVkfcu1r/wFPn4+LvgAAAA==[0m[Pipeline] sh
+ sed -i $'s/\r//g' /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4J0lAWMm8HuBR5s3oE3lokuIt9KB2+AHQUkjEiJ+aQGpAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPMKRSIUQVVorDS8w8WGcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThyM6JEGS7GzwrvR5CUmDsPV8SR6voiOKbJD0eLUssZmwZYTwpKihJWEDVLnOFoyCbayVw9VOUWmOqeQv6OE0uo7PKGQ2ZxUSF+YA+xuo45MP89fAcw+Qbk/5Kpr/wEOrpSSvgAAAA==[0m[Pipeline] sh
+ chmod a+x /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4Mt0DSsxkJzZfVcF7hGhEOllvDy/ttdaA/Rf0YiZvcahAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiAQ1CqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKYhQrk95Nrthw/JONXdvgAAAA==[0m[Pipeline] sh
+ sh /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
/root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh: line 7: [: too many arguments
[8mha:////4BJ3niM699yfMaO4XlYckMNVxHBxF/A/6tXrT01aXGOTAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigSgQSkVrueEFJjHGiXUXbAen4kV8jT9gEYmKLVY728zrDcvgoWZvsNPUWwqNxcGNJi9M7Pur44QdX7BhCuw0Sp0kt/o0o+SoYU5RwkLASlPjOFgyEdaiUw9VOUWmOkefv6OA0rZ3eEIhsjkqH78wedjcxjYw/Tx/BTANQ4Ryt8+1PXwARMxJg74AAAA=[0m[Pipeline] }
[8mha:////4KLOGR+83vgrLFidGueNeEu4h+87+yS5qW1q0kigPKEkAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigYSQUCpayw0vMIkxTqy7YDs4FS/ia/wBi0hUbLHa2WZeb1gGDzV7g52m3lJoLA5uNHlhYt9fHSfs+IINU2CnUeokudWnGSVHDXOKEhYCVpoax8GSibAWnXqoyiky1Tn6/B0FlLa9wxMKkc1R+fiFycPmNraB6ef5K4BpGCKUu32u7eEDfI7acr4AAAA=[0m[Pipeline] // script
[8mha:////4B/bjeg5xruNbbx3kITLupXWvVAJcKllvbrOrw34K5MTAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiQZECUaW10vACExvjxLoztkNS8SK+xh+wiETFFqudbeb1hnUMcOJgsNc0WIqdRe9GkxdOHIar4wl7vmDHFNlpbPXUstLNgi0nDUuKElYCNpo6x9GSSbAVvXzIykky1TmF/B0FlFbd4QmFyOYkQ/rCHGB3G1Vk+nn+CmD2PkF5qHPt6w9IQDkpvgAAAA==[0m[Pipeline] }
[8mha:////4Pysn2p6Cuaw38A5WKCzX3hZbaQrVsudvseeZZRTcVjBAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigYSQUCpayw0vMIkxTqy7YDs4FS/ia/wBi0hUbLHa2WZeb1gGDzV7g52m3lJoLA5uNHlhYt9fHSfs+IINU2CnUeokudWnGSVHDXOKEhYCVpoax8GSibAWnXqoyiky1Tn6/B0FlLa9wxMKkc1R+fiFycPmNraB6ef5K4BpGCKUu0Ou7f4DC8Jor74AAAA=[0m[Pipeline] // stage
[8mha:////4AtNwyaW/AZqBd3OKxZrkWfAC6zB3HxngMFQ9sJmqFs1AAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIpoEGIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsXZLsP/+idkr0AAAA=[0m[Pipeline] }
[8mha:////4I5dJP3UyABwbWbQZBRGWAtgfXC/GfHsQ3SW1rlV0+rIAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMJBgg5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBlS/sHL0AAAA=[0m[Pipeline] // node
[8mha:////4OCxxHdXTRYePL6pNSOSjI/nVmiKF6Ardumg4UkWHzykAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRiA5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBszaLVr0AAAA=[0m[Pipeline] End of Pipeline
Finished: FAILURE
