Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/cyp-test-nic-simple
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/cyp-test-nic-simple/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/cyp-test-nic-simple/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (set args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/conf/change_args.py '{"bmc_conf":{"user":"debuguser","password":"0penBmc1"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-21.02/","sut_conf":{"bmc_ip":"10.239.183.128","board_type":"commercial","host":"10.239.182.209","pf1":"ens785f2","os":"RHEL","PF1_NIC_type":"4*25"},"pkg_generator":{"host":"10.239.182.79","pf1":"ens787f2"},"drive_info":{"drive_version":"1.6.4"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics -s -m nicSimple --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_simple_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 19 items / 11 deselected / 8 selected

npxtester/Tests/testNics/test_mtu.py 2022-04-24 00:26:22 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_Jumbo_Packet_CVL_00_26_22/test_PI_Networking_Jumbo_Packet_CVL.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_Jumbo_Packet_CVL_00_26_22
2022-04-24 00:26:22 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-04-24 00:26:22 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-04-24 00:26:22 - test_mtu.py - [line:22] - root - INFO - ssh to the sut1
2022-04-24 00:26:22 - test_mtu.py - [line:24] - root - INFO - ssh to the sut1
2022-04-24 00:26:22 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:26:22 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:26:22 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:26:22 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:26:22 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:26:22 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:26:22 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:26:22 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:26:25 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:26:25 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:26:30 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:26:30 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:26:33 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:26:44 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:26:49 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:26:49 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:26:52 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:26:57 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:27:02 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:27:05 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:27:05 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:27:13 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 mtu 1500
2022-04-24 00:27:13 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:27:21 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 mtu 1500
2022-04-24 00:27:21 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:27:29 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:27:29 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a7c8:9536:dc19:92a  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 127 (127.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19  bytes 3301 (3.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:27:38 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Sun Apr 24 00:38:54 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | Craft packets like it is your last[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   | day on earth.[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |                      -- Lao-Tze[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m[34m[1m   |[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-04-24 00:27:45 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="40:a6:b7:72:cc:ca")/IP(len=46)/Raw(load='X'*14480)],iface="ens787f2")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-04-24 00:27:48 - test_mtu.py - [line:91] - root - INFO - success to send package to network
2022-04-24 00:27:52 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="40:a6:b7:72:cc:ca")/IP(len=46)/Raw(load='X'*15500)],iface="ens787f2")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-04-24 00:27:55 - test_mtu.py - [line:101] - root - INFO - result is right
.2022-04-24 00:27:58 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 mtu 1500
2022-04-24 00:27:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:28:06 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 mtu 1500
2022-04-24 00:28:06 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:28:14 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:28:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:28:22 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-24 00:28:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:28:27 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-24 00:28:27 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-24/test_PI_Networking_Jumbo_Packet_CVL_00_26_22
2022-04-24 00:28:30 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-24 00:28:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:28:35 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-24 00:28:35 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-04-24 00:28:35 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-04-24 00:28:35 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_MTU_set_CVL_00_28_35/test_PI_Networking_MTU_set_CVL.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_MTU_set_CVL_00_28_35
2022-04-24 00:28:35 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_MTU_set_CVL case ============================
2022-04-24 00:28:35 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-04-24 00:28:35 - test_mtu.py - [line:22] - root - INFO - ssh to the sut1
2022-04-24 00:28:35 - test_mtu.py - [line:24] - root - INFO - ssh to the sut1
2022-04-24 00:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:28:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:28:36 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:28:36 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:28:36 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:28:39 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:28:39 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:28:44 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:28:44 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:28:47 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:28:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:29:03 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:29:03 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:29:06 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:29:10 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:29:15 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:29:18 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:29:19 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:29:27 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 mtu 1500
2022-04-24 00:29:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:29:35 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 mtu 2000
2022-04-24 00:29:35 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:29:43 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:29:43 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a7c8:9536:dc19:92a  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 4  bytes 1153 (1.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 3094 (3.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:29:52 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Sun Apr 24 00:40:43 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | Craft packets like I craft my beer.[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   |               -- Jean De Clerck[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-04-24 00:29:59 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="40:a6:b7:72:cc:ca")/IP(len=46)/Raw(load='X'*18890)],iface="ens787f2")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-04-24 00:30:02 - test_mtu.py - [line:130] - root - INFO - success to send package to network
2022-04-24 00:30:06 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="40:a6:b7:72:cc:ca")/IP(len=46)/Raw(load='X'*20010)],iface="ens787f2")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-04-24 00:30:09 - test_mtu.py - [line:140] - root - INFO - result is right
.2022-04-24 00:30:12 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 mtu 1500
2022-04-24 00:30:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:30:20 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 mtu 1500
2022-04-24 00:30:21 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:30:29 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:30:29 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:30:37 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-24 00:30:37 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:30:42 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-24 00:30:42 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-24/test_PI_Networking_MTU_set_CVL_00_28_35
2022-04-24 00:30:45 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-24 00:30:45 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:30:50 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-24 00:30:50 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-04-24 00:30:50 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_MTU_set_CVL case ============================
                                  [ 25%]
npxtester/Tests/testNics/test_nics.py 2022-04-24 00:30:50 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-04-24 00:30:50 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_silver_Networking_ConnectivityEnableDisable_00_30_50/test_silver_Networking_ConnectivityEnableDisable.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_silver_Networking_ConnectivityEnableDisable_00_30_50
2022-04-24 00:30:50 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-04-24 00:30:50 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-24 00:30:50 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-24 00:30:50 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:30:50 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:30:50 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:30:50 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:30:50 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:30:50 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:30:50 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:30:50 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-24 00:30:50 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:30:53 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:30:53 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:30:58 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:30:58 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:31:01 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:31:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:31:17 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:31:17 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:31:20 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:31:24 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:31:29 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:31:32 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:31:32 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:31:37 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-24 00:31:37 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-24 00:31:44 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Apr 24 00:45:06 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (a96b1cf9-a7f7-4ab0-8875-a91e28f60788) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:31:47 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:31:53 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:31:56 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-24 00:32:02 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (85522100-4e81-4873-8d0c-2dc50b4fa500) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:32:05 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:32:11 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:32:14 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-24 00:32:17 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:32:17 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::f745:e4f8:b486:3fde  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21  bytes 3626 (3.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:32:25 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-24 00:32:25 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::cb92:5c5e:d1c7:f283  prefixlen 64  scopeid 0x20<link>
        inet6 2001:db8:1::12  prefixlen 64  scopeid 0x0<global>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 1519045908  bytes 2299795826247 (2.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59577593  bytes 3934614399 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:32:33 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:32:33 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:32:41 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-24 00:32:41 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:32:50 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.052 ms
2022-04-24 00:32:51 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.029 ms
2022-04-24 00:32:52 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.021 ms
2022-04-24 00:32:53 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.024 ms
2022-04-24 00:32:54 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.023 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 111ms
rtt min/avg/max/mdev = 0.021/0.029/0.052/0.013 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:33:00 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens785f2

2022-04-24 00:33:00 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (85522100-4e81-4873-8d0c-2dc50b4fa500) successfully deleted.

2022-04-24 00:33:08 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:33:08 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:33:19 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifname ens785f2

2022-04-24 00:33:19 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (362dc832-10a4-460b-9d80-a12c6414b009) successfully added.

2022-04-24 00:33:27 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:33:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:33:38 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:33:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:33:47 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.054 ms
2022-04-24 00:33:48 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.010 ms
2022-04-24 00:33:49 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.020 ms
2022-04-24 00:33:50 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.032 ms
2022-04-24 00:33:51 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.024 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 98ms
rtt min/avg/max/mdev = 0.010/0.028/0.054/0.014 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:33:57 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens785f2

2022-04-24 00:33:57 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (362dc832-10a4-460b-9d80-a12c6414b009) successfully deleted.

2022-04-24 00:34:05 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:34:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:34:16 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifname ens785f2

2022-04-24 00:34:16 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (eb51ef91-005a-4214-be8d-abb6988927db) successfully added.

2022-04-24 00:34:24 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:34:25 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:34:36 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:34:36 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:34:45 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.054 ms
2022-04-24 00:34:46 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.027 ms
2022-04-24 00:34:47 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.021 ms
2022-04-24 00:34:48 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.049 ms
2022-04-24 00:34:49 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.023 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 112ms
rtt min/avg/max/mdev = 0.021/0.034/0.054/0.015 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:34:55 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens785f2

2022-04-24 00:34:55 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (eb51ef91-005a-4214-be8d-abb6988927db) successfully deleted.

2022-04-24 00:35:03 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:35:03 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:35:14 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifname ens785f2

2022-04-24 00:35:14 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (2f04619e-7128-42c0-8a49-605c7cfb7999) successfully added.

2022-04-24 00:35:22 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:35:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:35:33 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:35:33 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:35:42 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.055 ms
2022-04-24 00:35:43 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.023 ms
2022-04-24 00:35:44 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.018 ms
2022-04-24 00:35:45 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.022 ms
2022-04-24 00:35:46 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.023 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 105ms
rtt min/avg/max/mdev = 0.018/0.028/0.055/0.013 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:35:52 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens785f2

2022-04-24 00:35:52 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (2f04619e-7128-42c0-8a49-605c7cfb7999) successfully deleted.

2022-04-24 00:36:00 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:36:00 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:36:11 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifname ens785f2

2022-04-24 00:36:11 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (bd72f9c9-8b10-402a-b1d1-42f1f8a6a872) successfully added.

2022-04-24 00:36:19 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:36:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:36:30 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:36:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:36:39 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.045 ms
2022-04-24 00:36:40 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.023 ms
2022-04-24 00:36:41 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.011 ms
2022-04-24 00:36:42 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.046 ms
2022-04-24 00:36:43 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.027 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 94ms
rtt min/avg/max/mdev = 0.011/0.030/0.046/0.014 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:36:49 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens785f2

2022-04-24 00:36:49 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (bd72f9c9-8b10-402a-b1d1-42f1f8a6a872) successfully deleted.

2022-04-24 00:36:57 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:36:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:37:09 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifname ens785f2

2022-04-24 00:37:09 - sshInstance.py - [line:54] - root - INFO - Connection 'ens785f2' (4688e46f-4a40-4d4b-bb2d-9479fe7467d8) successfully added.

2022-04-24 00:37:17 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-24 00:37:17 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:37:28 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:37:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:37:37 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.058 ms
2022-04-24 00:37:38 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.025 ms
2022-04-24 00:37:39 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.028 ms
2022-04-24 00:37:40 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.025 ms
2022-04-24 00:37:41 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.024 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 82ms
rtt min/avg/max/mdev = 0.024/0.032/0.058/0.013 ms
[root@npx-cyp7-rh82 ~]# 
.2022-04-24 00:37:47 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:37:47 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:37:55 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:37:55 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:38:03 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-24 00:38:03 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:38:11 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-24 00:38:11 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:38:19 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-24 00:38:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:38:24 - test_nics.py - [line:80] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-24 00:38:24 - test_nics.py - [line:82] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-24/test_silver_Networking_ConnectivityEnableDisable_00_30_50
2022-04-24 00:38:27 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-24 00:38:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:38:32 - test_nics.py - [line:84] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-24 00:38:32 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-24 00:38:32 - test_nics.py - [line:86] - root - INFO - this is Test_Nics teardown
2022-04-24 00:38:32 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-04-24 00:38:32 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_silver_ConnectivityReboot_00_38_32/test_silver_ConnectivityReboot.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_silver_ConnectivityReboot_00_38_32
2022-04-24 00:38:32 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_silver_ConnectivityReboot case ============================
2022-04-24 00:38:32 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-24 00:38:32 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-24 00:38:32 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:38:33 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:38:33 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:38:33 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:38:33 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:38:33 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:38:33 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:38:33 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-24 00:38:33 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:38:36 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:38:36 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:38:41 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:38:41 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:38:44 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:38:55 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:39:00 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:39:00 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:39:03 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:39:07 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:39:12 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:39:15 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:39:15 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:39:20 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-24 00:39:20 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-24 00:39:26 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Apr 24 00:52:49 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (4688e46f-4a40-4d4b-bb2d-9479fe7467d8) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:39:29 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:39:35 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:39:38 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-24 00:39:44 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (15cfb8dc-c4c5-4526-84a1-376956131e76) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:39:47 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:39:53 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:39:56 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-24 00:39:59 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:39:59 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::4a6a:dfdc:d3da:adc8  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1026 (1.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 42  bytes 6806 (6.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:40:07 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-24 00:40:07 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::cb92:5c5e:d1c7:f283  prefixlen 64  scopeid 0x20<link>
        inet6 2001:db8:1::12  prefixlen 64  scopeid 0x0<global>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 1519046149  bytes 2299795867766 (2.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59577622  bytes 3934621391 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:40:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-24 00:40:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:40:24 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:40:24 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:40:29 - test_nics.py - [line:142] - root - INFO - -- check sut connectivity by rebooting for 1 times --
2022-04-24 00:40:33 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.11
PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.403 ms
2022-04-24 00:40:34 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.221 ms
2022-04-24 00:40:35 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.230 ms
2022-04-24 00:40:36 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.226 ms
2022-04-24 00:40:37 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.213 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 82ms
rtt min/avg/max/mdev = 0.213/0.258/0.403/0.074 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:40:44 - sshInstance.py - [line:75] - root - INFO - ping6 -c 5 -I ens785f2 2001:db8:1::12
connect: Network is unreachable
[root@npx-cyp7-rh82 ~]# 
F2022-04-24 00:40:50 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:40:50 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:40:58 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:40:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:41:06 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-24 00:41:06 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:41:14 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-24 00:41:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:41:22 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-24 00:41:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:41:27 - test_nics.py - [line:80] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-24 00:41:27 - test_nics.py - [line:82] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-24/test_silver_ConnectivityReboot_00_38_32
2022-04-24 00:41:30 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-24 00:41:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:41:35 - test_nics.py - [line:84] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-24 00:41:35 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-24 00:41:35 - test_nics.py - [line:86] - root - INFO - this is Test_Nics teardown
2022-04-24 00:41:35 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_silver_ConnectivityReboot case ============================
2022-04-24 00:41:35 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_gold_PI_Networking_SRIOV_CheckDevice_00_41_35/test_gold_PI_Networking_SRIOV_CheckDevice.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_gold_PI_Networking_SRIOV_CheckDevice_00_41_35
2022-04-24 00:41:35 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-04-24 00:41:35 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-24 00:41:35 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-24 00:41:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:41:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:41:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:41:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:41:36 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:41:36 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:41:36 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:41:36 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-24 00:41:36 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:41:39 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:41:39 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:41:44 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:41:44 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:41:47 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:41:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:42:03 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:42:03 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:42:06 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:42:10 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:42:15 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:42:18 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:42:18 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:42:23 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-24 00:42:23 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-24 00:42:29 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Apr 24 00:55:52 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (15cfb8dc-c4c5-4526-84a1-376956131e76) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:42:32 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:42:38 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:42:41 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-24 00:42:47 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (609142a9-a6fe-4a73-be26-8593e215434b) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:42:50 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:42:56 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:42:59 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-24 00:43:02 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:43:02 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::83c0:d8ae:e2fa:e133  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 127 (127.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41  bytes 6669 (6.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:43:10 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-24 00:43:10 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::cb92:5c5e:d1c7:f283  prefixlen 64  scopeid 0x20<link>
        inet6 2001:db8:1::12  prefixlen 64  scopeid 0x0<global>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 1519046213  bytes 2299795878292 (2.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59577647  bytes 3934625641 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:43:18 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:43:18 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:43:31 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11

2022-04-24 00:43:31 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:43:36 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2v0:
2022-04-24 00:43:42 - sshInstance.py - [line:99] - root - INFO - nmcli connection delete ens785f2v0
Connection 'ens785f2v0' (84719a1c-6188-4038-98d3-b10f62c157d3) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:43:45 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:43:52 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:43:55 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2v0:
2022-04-24 00:44:01 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2v0 iffname ens785f2v0
Connection 'ens785f2v0' (c8c1acfc-a7d5-4140-8bf0-b4cbb2b6e246) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:44:04 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:44:10 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:44:16 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v0 192.168.10.12
2022-04-24 00:44:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:44:27 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.12
2022-04-24 00:44:31 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.434 ms
64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.244 ms
64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.207 ms
64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.251 ms
64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.230 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4093ms
rtt min/avg/max/mdev = 0.207/0.273/0.434/0.082 ms

2022-04-24 00:44:39 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v0 | grep inet6
2022-04-24 00:44:39 - sshInstance.py - [line:54] - root - INFO -         inet6 fe80::6713:e477:b449:3b47  prefixlen 64  scopeid 0x20<link>

2022-04-24 00:44:47 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens785f2v0 2001:db8:1::12
2022-04-24 00:44:47 - sshInstance.py - [line:54] - root - INFO - connect: Network is unreachable

2022-04-24 00:44:52 - test_nics.py - [line:206] - root - INFO - packet lost during ping.
F2022-04-24 00:44:55 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:44:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:45:06 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:45:06 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:45:14 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-24 00:45:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:45:22 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-24 00:45:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:45:30 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-24 00:45:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:45:35 - test_nics.py - [line:80] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-24 00:45:35 - test_nics.py - [line:82] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-24/test_gold_PI_Networking_SRIOV_CheckDevice_00_41_35
2022-04-24 00:45:38 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-24 00:45:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:45:43 - test_nics.py - [line:84] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-24 00:45:43 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-24 00:45:43 - test_nics.py - [line:86] - root - INFO - this is Test_Nics teardown
2022-04-24 00:45:43 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-04-24 00:45:43 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_InternetProtocolv4v6_00_45_43/test_PI_Networking_InternetProtocolv4v6.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_InternetProtocolv4v6_00_45_43
2022-04-24 00:45:43 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_InternetProtocolv4v6 case ============================
2022-04-24 00:45:43 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-24 00:45:43 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-24 00:45:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:45:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:45:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:45:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:45:44 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:45:44 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:45:44 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:45:44 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-24 00:45:44 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:45:47 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:45:47 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:45:52 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:45:52 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:45:55 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:46:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:46:10 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:46:10 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:46:13 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:46:18 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:46:23 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:46:26 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:46:26 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:46:31 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-24 00:46:31 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-24 00:46:37 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Apr 24 01:00:00 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (609142a9-a6fe-4a73-be26-8593e215434b) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:46:40 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:46:46 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:46:49 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-24 00:46:55 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (4db61adf-10e8-4c86-9403-ff4119f90a67) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:46:58 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:47:04 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:47:07 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-24 00:47:10 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:47:10 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::6de9:1bec:cad3:57ff  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 469 (469.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41  bytes 6814 (6.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:47:18 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-24 00:47:18 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::cb92:5c5e:d1c7:f283  prefixlen 64  scopeid 0x20<link>
        inet6 2001:db8:1::12  prefixlen 64  scopeid 0x0<global>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 1519046339  bytes 2299795900299 (2.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59577677  bytes 3934631386 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:47:26 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:47:26 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:47:34 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-24 00:47:34 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:47:42 - sshInstance.py - [line:50] - root - INFO - ping -w 5 192.168.10.11
2022-04-24 00:47:47 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.478 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.234 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.211 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.203 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.200 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 65ms
rtt min/avg/max/mdev = 0.200/0.265/0.478/0.107 ms

2022-04-24 00:47:55 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens785f2 2001:db8:1::12
2022-04-24 00:47:55 - sshInstance.py - [line:54] - root - INFO - connect: Network is unreachable

.2022-04-24 00:48:03 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:48:03 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:48:11 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:48:11 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:48:19 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-24 00:48:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:48:27 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-24 00:48:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:48:35 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-24 00:48:36 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:48:41 - test_nics.py - [line:80] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-24 00:48:41 - test_nics.py - [line:82] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-24/test_PI_Networking_InternetProtocolv4v6_00_45_43
2022-04-24 00:48:44 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-24 00:48:44 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:48:49 - test_nics.py - [line:84] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-24 00:48:49 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-24 00:48:49 - test_nics.py - [line:86] - root - INFO - this is Test_Nics teardown
2022-04-24 00:48:49 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_InternetProtocolv4v6 case ============================
2022-04-24 00:48:49 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_Link_State_Check_00_48_49/test_PI_Networking_Link_State_Check.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_Link_State_Check_00_48_49
2022-04-24 00:48:49 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_Link_State_Check case ============================
2022-04-24 00:48:49 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-24 00:48:49 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-24 00:48:49 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:48:49 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:48:49 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:48:49 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:48:49 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:48:49 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:48:49 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:48:49 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-24 00:48:49 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:48:52 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:48:52 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:48:57 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:48:57 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:49:00 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:49:10 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:49:15 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:49:15 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:49:18 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:49:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:49:28 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:49:31 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:49:31 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:49:36 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-24 00:49:36 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-24 00:49:42 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Apr 24 01:03:05 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (4db61adf-10e8-4c86-9403-ff4119f90a67) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:49:45 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:49:51 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:49:54 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-24 00:50:00 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (c185a2bd-3f13-4e1e-8a27-d7093cdeb97c) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:50:03 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:50:09 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:50:12 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-24 00:50:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:50:15 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::3161:b0c5:d70e:d570  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 811 (811.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41  bytes 6814 (6.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:50:23 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-24 00:50:23 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::cb92:5c5e:d1c7:f283  prefixlen 64  scopeid 0x20<link>
        inet6 2001:db8:1::12  prefixlen 64  scopeid 0x0<global>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 1519046404  bytes 2299795911032 (2.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59577704  bytes 3934636395 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:50:31 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
2022-04-24 00:50:31 - sshInstance.py - [line:54] - root - INFO - 0000:4b:00.2

2022-04-24 00:50:39 - sshInstance.py - [line:50] - root - INFO - lspci -vvs 00:4b:00.2 | grep LnkCap:
2022-04-24 00:50:39 - sshInstance.py - [line:54] - root - INFO - 		LnkCap:	Port #0, Speed 16GT/s, Width x16, ASPM not supported

2022-04-24 00:50:47 - sshInstance.py - [line:50] - root - INFO - lspci -vvs 00:4b:00.2 | grep LnkSta:
2022-04-24 00:50:47 - sshInstance.py - [line:54] - root - INFO - 		LnkSta:	Speed 16GT/s, Width x16, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-

2022-04-24 00:50:52 - test_nics.py - [line:295] - root - INFO - --check the speed and width of the ethernet ens785f2
2022-04-24 00:50:52 - test_nics.py - [line:299] - root - INFO - the linkCap and LnkSta value are matched. The speed and width value are: 16GT/s and Width x16.
.2022-04-24 00:50:55 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:50:55 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:51:03 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:51:03 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:51:11 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-24 00:51:11 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:51:19 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-24 00:51:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:51:27 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-24 00:51:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:51:33 - test_nics.py - [line:80] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-24 00:51:33 - test_nics.py - [line:82] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-24/test_PI_Networking_Link_State_Check_00_48_49
2022-04-24 00:51:36 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-24 00:51:36 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:51:41 - test_nics.py - [line:84] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-24 00:51:41 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-24 00:51:41 - test_nics.py - [line:86] - root - INFO - this is Test_Nics teardown
2022-04-24 00:51:41 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_Link_State_Check case ============================
2022-04-24 00:51:41 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_ConnectivityShutdown_00_51_41/test_PI_Networking_ConnectivityShutdown.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_PI_Networking_ConnectivityShutdown_00_51_41
2022-04-24 00:51:41 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_ConnectivityShutdown case ============================
2022-04-24 00:51:41 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-24 00:51:41 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-24 00:51:41 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:51:41 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:51:41 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:51:41 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:51:41 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:51:41 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:51:41 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:51:41 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-24 00:51:41 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:51:44 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:51:44 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:51:49 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:51:49 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:51:52 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:52:03 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:52:08 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:52:08 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:52:11 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:52:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:52:21 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:52:24 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:52:24 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:52:29 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-24 00:52:29 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-24 00:52:35 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Apr 24 01:05:57 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (c185a2bd-3f13-4e1e-8a27-d7093cdeb97c) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:52:38 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:52:44 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:52:47 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-24 00:52:53 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (cd56aacb-e1ca-41bd-bc1c-5797b2963775) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:52:56 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:53:02 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:53:05 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-24 00:53:08 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:53:08 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::3167:ddea:9a20:ea28  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 127 (127.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 43  bytes 6986 (6.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:53:16 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-24 00:53:16 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::cb92:5c5e:d1c7:f283  prefixlen 64  scopeid 0x20<link>
        inet6 2001:db8:1::12  prefixlen 64  scopeid 0x0<global>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 1519046453  bytes 2299795919559 (2.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59577709  bytes 3934637460 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:53:24 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-24 00:53:24 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:53:32 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:53:32 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:53:40 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11

2022-04-24 00:53:44 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.523 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.216 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.217 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.216 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.225 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 139ms
rtt min/avg/max/mdev = 0.216/0.279/0.523/0.122 ms

2022-04-24 00:53:49 - power.py - [line:18] - root - INFO - checking the machine status
2022-04-24 00:53:49 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power status
....
2022-04-24 00:53:49 - commonFunc.py - [line:30] - root - INFO - Chassis Power is on
2022-04-24 00:53:49 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:53:49 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power status

2022-04-24 00:53:49 - power.py - [line:22] - root - INFO - Chassis Power is on

2022-04-24 00:53:49 - test_nics.py - [line:340] - root - INFO - Chassis Power is on

2022-04-24 00:53:49 - sshInstance.py - [line:143] - root - INFO - ping sut, please wait ......
2022-04-24 00:54:49 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.371 ms
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.347 ms
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.343 ms
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.341 ms
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.342 ms
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 80ms
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.341/0.348/0.371/0.026 ms
2022-04-24 00:54:54 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:54:54 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:54:54 - power.py - [line:39] - root - INFO - starting to power off the machine....
2022-04-24 00:54:54 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power off
....
2022-04-24 00:54:55 - commonFunc.py - [line:30] - root - INFO - Chassis Power Control: Down/Off
2022-04-24 00:54:55 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:54:55 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power off

2022-04-24 00:54:55 - power.py - [line:44] - root - INFO - Chassis Power Control: Down/Off

2022-04-24 00:54:55 - test_nics.py - [line:343] - root - INFO - Chassis Power Control: Down/Off

2022-04-24 00:55:05 - power.py - [line:18] - root - INFO - checking the machine status
2022-04-24 00:55:05 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power status
....
2022-04-24 00:55:05 - commonFunc.py - [line:30] - root - INFO - Chassis Power is off
2022-04-24 00:55:05 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:55:05 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power status

2022-04-24 00:55:05 - power.py - [line:22] - root - INFO - Chassis Power is off

2022-04-24 00:55:05 - test_nics.py - [line:347] - root - INFO - the machine is powering off....
2022-04-24 00:55:05 - power.py - [line:27] - root - INFO - starting to power on the machine....
2022-04-24 00:55:05 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power on
....
2022-04-24 00:55:05 - commonFunc.py - [line:30] - root - INFO - Chassis Power Control: Up/On
2022-04-24 00:55:05 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:55:05 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power on

2022-04-24 00:55:05 - power.py - [line:32] - root - INFO - Chassis Power Control: Up/On

2022-04-24 00:55:05 - test_nics.py - [line:353] - root - INFO - Chassis Power Control: Up/On

2022-04-24 00:55:15 - sshInstance.py - [line:143] - root - INFO - ping sut, please wait ......
2022-04-24 00:56:15 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:56:20 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:56:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:20 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:56:20 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 97ms
2022-04-24 00:56:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:20 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:56:25 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:56:30 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:56:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:30 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:56:30 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 133ms
2022-04-24 00:56:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:30 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:56:35 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:56:40 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:56:40 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:40 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:56:40 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 107ms
2022-04-24 00:56:40 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:40 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:40 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:56:45 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:56:50 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:56:50 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:50 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:56:50 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 82ms
2022-04-24 00:56:50 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:50 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:56:50 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:56:55 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:57:00 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:57:00 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:00 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:57:00 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 120ms
2022-04-24 00:57:00 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:00 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:00 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:57:05 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:57:10 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:57:10 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:10 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:57:10 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 94ms
2022-04-24 00:57:10 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:10 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:10 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:57:15 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:57:20 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:57:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:20 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:57:20 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 132ms
2022-04-24 00:57:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:20 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:57:25 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:57:30 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:57:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:30 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:57:30 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 107ms
2022-04-24 00:57:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:30 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:57:35 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:57:40 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:57:40 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:40 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:57:40 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 81ms
2022-04-24 00:57:40 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:40 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:40 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:57:45 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:57:50 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:57:50 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:50 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:57:50 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 122ms
2022-04-24 00:57:50 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:50 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:57:50 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:57:55 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:58:00 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:58:00 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:00 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:58:00 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 92ms
2022-04-24 00:58:00 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:00 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:00 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:58:05 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:58:10 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:58:10 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:10 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:58:10 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 129ms
2022-04-24 00:58:10 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:10 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:10 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:58:15 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:58:20 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:58:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:20 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:58:20 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 103ms
2022-04-24 00:58:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:20 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:20 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 00:58:25 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.358 ms
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.326 ms
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.355 ms
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.338 ms
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.269 ms
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 78ms
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.269/0.329/0.358/0.034 ms
2022-04-24 00:58:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 00:58:30 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-24 01:03:30 - power.py - [line:18] - root - INFO - checking the machine status
2022-04-24 01:03:30 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power status
....
2022-04-24 01:03:30 - commonFunc.py - [line:30] - root - INFO - Chassis Power is on
2022-04-24 01:03:30 - commonFunc.py - [line:30] - root - INFO - 
2022-04-24 01:03:30 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ipmitool -I lanplus -H 10.239.183.128 -U debuguser -P 0penBmc1 power status

2022-04-24 01:03:30 - power.py - [line:22] - root - INFO - Chassis Power is on

2022-04-24 01:03:30 - test_nics.py - [line:359] - root - INFO - the machine is powering on....
2022-04-24 01:03:30 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 01:03:30 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 01:03:30 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 01:03:33 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 01:03:33 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 01:03:41 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11

2022-04-24 01:03:46 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.509 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.174 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.220 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.220 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.213 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 90ms
rtt min/avg/max/mdev = 0.174/0.267/0.509/0.122 ms

.2022-04-24 01:03:54 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 01:03:54 - transport.py - [line:1819] - paramiko.transport - ERROR - Socket exception: Connection reset by peer (104)
2022-04-24 01:03:54 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 01:03:54 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 01:03:54 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 01:03:54 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 01:03:57 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 01:03:57 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 01:04:05 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-24 01:04:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 01:04:13 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-24 01:04:13 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 01:04:21 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-24 01:04:21 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 01:04:26 - test_nics.py - [line:80] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-24 01:04:26 - test_nics.py - [line:82] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-24/test_PI_Networking_ConnectivityShutdown_00_51_41
2022-04-24 01:04:29 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-24 01:04:29 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 01:04:34 - test_nics.py - [line:84] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-24 01:04:34 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-24 01:04:34 - test_nics.py - [line:86] - root - INFO - this is Test_Nics teardown
2022-04-24 01:04:34 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_ConnectivityShutdown case ============================
                             [100%]

=================================== FAILURES ===================================
___________________ Test_Nics.test_silver_ConnectivityReboot ___________________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7f85d59dcb70>

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicSilver
    @pytest.mark.nicSimple
    def test_silver_ConnectivityReboot(self):
        sut1_ip = "192.168.10.10"
        sut2_ip = "192.168.10.11"
        self.cn_test_sut.ssh_exec_cmd(self.client2, "ifconfig {} {}".format(self.pkg_generator["pf1"], sut2_ip))
        self.cn_test_sut.ssh_exec_cmd(self.client, "ifconfig {} {}".format(self.sut_conf["pf1"], sut1_ip))
        rs = 0
        cmdip = "ping -c 5 {}\n".format(sut2_ip)
        cmdipv6 = "ping6 -c 5 -I {} {}\n".format(self.sut_conf["pf1"],self.sut2_pf1_ipv6)
        for num in range(2):
            logging.info("-- check sut connectivity by rebooting for {} times --".format(str(num + 1)))
            if num > 0:
                self.cn_test_sut = sshInstance()
                self.client, self.session = self.cn_test_sut.get_ssh_instance(self.sut_conf["host"], self.sut_conf["user"], self.sut_conf["password"], self.sut_conf["port"])
                if self.sut_conf["os"] == "RHEL":
                    self.cn_test_sut.delete_network(self.session, self.sut_conf["pf1"])
                    self.cn_test_sut.add_network(self.session, self.sut_conf["pf1"])
                else:
                    self.cn_test_sut.ssh_exec_cmd(self.client, "ifconfig {} down".format(self.sut_conf["pf1"]))
                    self.cn_test_sut.ssh_exec_cmd(self.client, "ifconfig {} up".format(self.sut_conf["pf1"]))
                self.cn_test_sut.ssh_exec_cmd(self.client, "ifconfig {} {}".format(self.sut_conf["pf1"], sut1_ip))
            output, stderr = self.cn_test_sut.run_ssh_cmd(self.session, cmdip, self.check_str)
            assert 200 == self.cn_test_sut.commond_rs_check(output, "received, 0% packet loss", True)
            output, stderr = self.cn_test_sut.run_ssh_cmd(self.session, cmdipv6, self.check_str)
>           assert 200 == self.cn_test_sut.commond_rs_check(output, "received, 0% packet loss", True)
E           AssertionError: assert 200 == 400
E            +  where 400 = <bound method sshInstance.commond_rs_check of <libs.commons.sshInstance.sshInstance object at 0x7f85d5a24e80>>('ping6 -c 5 -I ens785f2 2001:db8:1::12\r\nconnect: Network is unreachable\r\n[root@npx-cyp7-rh82 ~]# ', 'received, 0% packet loss', True)
E            +    where <bound method sshInstance.commond_rs_check of <libs.commons.sshInstance.sshInstance object at 0x7f85d5a24e80>> = <libs.commons.sshInstance.sshInstance object at 0x7f85d5a24e80>.commond_rs_check
E            +      where <libs.commons.sshInstance.sshInstance object at 0x7f85d5a24e80> = <Tests.testNics.test_nics.Test_Nics object at 0x7f85d59dcb70>.cn_test_sut

npxtester/Tests/testNics/test_nics.py:156: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-04-24 00:38:32 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_silver_ConnectivityReboot_00_38_32/test_silver_ConnectivityReboot.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_silver_ConnectivityReboot_00_38_32
2022-04-24 00:38:32 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_silver_ConnectivityReboot case ============================
2022-04-24 00:38:32 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-24 00:38:32 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-24 00:38:32 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:38:33 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:38:33 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:38:33 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:38:33 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:38:33 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:38:33 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:38:33 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-24 00:38:33 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:38:36 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:38:36 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:38:41 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:38:41 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:38:44 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:38:55 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:39:00 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:39:00 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:39:03 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:39:07 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:39:12 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:39:15 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:39:15 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:39:20 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-24 00:39:20 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-24 00:39:26 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Apr 24 00:52:49 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (4688e46f-4a40-4d4b-bb2d-9479fe7467d8) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:39:29 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:39:35 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:39:38 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-24 00:39:44 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (15cfb8dc-c4c5-4526-84a1-376956131e76) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:39:47 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:39:53 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:39:56 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-24 00:39:59 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:39:59 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::4a6a:dfdc:d3da:adc8  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1026 (1.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 42  bytes 6806 (6.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:40:07 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-24 00:40:07 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::cb92:5c5e:d1c7:f283  prefixlen 64  scopeid 0x20<link>
        inet6 2001:db8:1::12  prefixlen 64  scopeid 0x0<global>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 1519046149  bytes 2299795867766 (2.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59577622  bytes 3934621391 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-04-24 00:40:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-24 00:40:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:40:24 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-24 00:40:24 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:40:29 - test_nics.py - [line:142] - root - INFO - -- check sut connectivity by rebooting for 1 times --
2022-04-24 00:40:33 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.11
PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.403 ms
2022-04-24 00:40:34 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.221 ms
2022-04-24 00:40:35 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.230 ms
2022-04-24 00:40:36 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.226 ms
2022-04-24 00:40:37 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.213 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 82ms
rtt min/avg/max/mdev = 0.213/0.258/0.403/0.074 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:40:44 - sshInstance.py - [line:75] - root - INFO - ping6 -c 5 -I ens785f2 2001:db8:1::12
connect: Network is unreachable
[root@npx-cyp7-rh82 ~]# 
------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:50 ifconfig ens787f2 192.168.10.11
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ifconfig ens785f2 192.168.10.10
INFO     root:sshInstance.py:54 
INFO     root:test_nics.py:142 -- check sut connectivity by rebooting for 1 times --
INFO     root:sshInstance.py:75 ping -c 5 192.168.10.11
PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.403 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.221 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.230 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.226 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.213 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 82ms
rtt min/avg/max/mdev = 0.213/0.258/0.403/0.074 ms
[root@npx-cyp7-rh82 ~]# 
INFO     root:sshInstance.py:75 ping6 -c 5 -I ens785f2 2001:db8:1::12
connect: Network is unreachable
[root@npx-cyp7-rh82 ~]#
_____________ Test_Nics.test_gold_PI_Networking_SRIOV_CheckDevice ______________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7f85d5a47a58>

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicGold
    @pytest.mark.nicSilver
    @pytest.mark.nicSimple
    @pytest.mark.test
    def test_gold_PI_Networking_SRIOV_CheckDevice(self):
        cmd = "echo 4 > /sys/class/net/{}/device/sriov_numvfs".format(self.sut_conf["pf1"])
        stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, cmd)
        time.sleep(5)
        if stdout or stderr:
            assert 200 == 400
        sut2_ip = "192.168.10.11"
        self.cn_test_sut.ssh_exec_cmd(self.client2, "ifconfig {} {}\n".format(self.pkg_generator["pf1"], sut2_ip))
        port_up_cmd = "ifconfig {} up"
        #manual_ip_cmd = "ifconfig {}{} 192.168.{}.{}"
        manual_ip_cmd = "ifconfig {}{} 192.168.{}.{}"
        ping_ipv4_cmd = "ping -c 5 192.168.{}.{}"
        ping_ipv6_cmd = "ping6 -c 5 -I {}{} {}"
        for i in range(4):
            vf = "v"+str(i)
            ip_part = str(int(sut2_ip.split(".")[3])+i+1)
            vf_name = "{}{}".format(self.sut_conf["pf1"], vf)
            if self.sut_conf["os"] == "RHEL":
                self.cn_test_sut.delete_network(self.session, vf_name)
                self.cn_test_sut.add_network(self.session, vf_name)
            else:
                stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, "ifconfig {} down".format(vf_name))
                stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, "ifconfig {} up".format(vf_name))
    
            stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, manual_ip_cmd.format(self.sut_conf["pf1"], vf,sut2_ip.split(".")[2] ,ip_part))
            time.sleep(3)
            if stdout or stderr:
                assert 200 == 400
            stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client2, ping_ipv4_cmd.format(sut2_ip.split(".")[2], ip_part))
            if stdout.find("received, 0% packet loss") == -1:
                assert 200 == 400
            output, err = self.cn_test_sut.ssh_exec_cmd(self.client, "ifconfig {} | grep inet6".format(vf_name))
            if output.find("inet6") == -1:
                self.cn_test_sut.add_network(self.session, vf_name)
            else:
                stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, ping_ipv6_cmd.format(self.sut_conf["pf1"], vf, self.sut2_pf1_ipv6))
            if stdout.find("received, 0% packet loss") == -1:
                logging.info("packet lost during ping.")
>               assert 200 == 400
E               assert 200 == 400

npxtester/Tests/testNics/test_nics.py:207: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-04-24 00:41:35 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-24/test_gold_PI_Networking_SRIOV_CheckDevice_00_41_35/test_gold_PI_Networking_SRIOV_CheckDevice.log, case_logdir: /root/testconfig/testlogs/2022-04-24/test_gold_PI_Networking_SRIOV_CheckDevice_00_41_35
2022-04-24 00:41:35 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-04-24 00:41:35 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-24 00:41:35 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-24 00:41:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:41:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:41:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-24 00:41:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-24 00:41:36 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-24 00:41:36 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-24 00:41:36 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-24 00:41:36 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-24 00:41:36 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-24 00:41:39 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-24 00:41:39 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-24 00:41:44 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-24 00:41:44 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-24 00:41:47 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-24 00:41:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:42:03 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-24 00:42:03 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-24 00:42:06 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-24 00:42:10 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:42:15 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-24 00:42:18 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-24 00:42:18 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-24 00:42:23 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-24 00:42:23 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2:
2022-04-24 00:42:29 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Sun Apr 24 00:55:52 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (15cfb8dc-c4c5-4526-84a1-376956131e76) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:42:32 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:42:38 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:42:41 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2:
2022-04-24 00:42:47 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (609142a9-a6fe-4a73-be26-8593e215434b) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:42:50 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:42:56 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:42:59 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-24 00:43:02 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-24 00:43:02 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::83c0:d8ae:e2fa:e133  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 127 (127.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41  bytes 6669 (6.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-24 00:43:10 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-24 00:43:10 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::cb92:5c5e:d1c7:f283  prefixlen 64  scopeid 0x20<link>
        inet6 2001:db8:1::12  prefixlen 64  scopeid 0x0<global>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 1519046213  bytes 2299795878292 (2.0 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59577647  bytes 3934625641 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-04-24 00:43:18 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-24 00:43:18 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:43:31 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11

2022-04-24 00:43:31 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:43:36 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens785f2v0:
2022-04-24 00:43:42 - sshInstance.py - [line:99] - root - INFO - nmcli connection delete ens785f2v0
Connection 'ens785f2v0' (84719a1c-6188-4038-98d3-b10f62c157d3) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:43:45 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:43:52 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:43:55 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens785f2v0:
2022-04-24 00:44:01 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2v0 iffname ens785f2v0
Connection 'ens785f2v0' (c8c1acfc-a7d5-4140-8bf0-b4cbb2b6e246) successfully added.
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:44:04 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-24 00:44:10 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
2022-04-24 00:44:16 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v0 192.168.10.12
2022-04-24 00:44:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-24 00:44:27 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.12
2022-04-24 00:44:31 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.434 ms
64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.244 ms
64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.207 ms
64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.251 ms
64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.230 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4093ms
rtt min/avg/max/mdev = 0.207/0.273/0.434/0.082 ms

2022-04-24 00:44:39 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v0 | grep inet6
2022-04-24 00:44:39 - sshInstance.py - [line:54] - root - INFO -         inet6 fe80::6713:e477:b449:3b47  prefixlen 64  scopeid 0x20<link>

2022-04-24 00:44:47 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens785f2v0 2001:db8:1::12
2022-04-24 00:44:47 - sshInstance.py - [line:54] - root - INFO - connect: Network is unreachable

2022-04-24 00:44:52 - test_nics.py - [line:206] - root - INFO - packet lost during ping.
------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:50 echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ifconfig ens787f2 192.168.10.11

INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:187 starting to delete network of ens785f2v0:
INFO     root:sshInstance.py:99 nmcli connection delete ens785f2v0
Connection 'ens785f2v0' (84719a1c-6188-4038-98d3-b10f62c157d3) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
INFO     root:sshInstance.py:189 restart networkManager to make setting valid
INFO     root:sshInstance.py:99 systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
INFO     root:sshInstance.py:192 starting to add network of ens785f2v0:
INFO     root:sshInstance.py:99 nmcli connection add type ethernet con-name ens785f2v0 iffname ens785f2v0
Connection 'ens785f2v0' (c8c1acfc-a7d5-4140-8bf0-b4cbb2b6e246) successfully added.
[root@npx-cyp7-rh82 ~]# 
INFO     root:sshInstance.py:195 restart networkManager to make setting valid
INFO     root:sshInstance.py:99 systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
INFO     root:sshInstance.py:50 ifconfig ens785f2v0 192.168.10.12
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ping -c 5 192.168.10.12
INFO     root:sshInstance.py:54 PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.434 ms
64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.244 ms
64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.207 ms
64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.251 ms
64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.230 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4093ms
rtt min/avg/max/mdev = 0.207/0.273/0.434/0.082 ms

INFO     root:sshInstance.py:50 ifconfig ens785f2v0 | grep inet6
INFO     root:sshInstance.py:54         inet6 fe80::6713:e477:b449:3b47  prefixlen 64  scopeid 0x20<link>

INFO     root:sshInstance.py:50 ping6 -c 5 -I ens785f2v0 2001:db8:1::12
INFO     root:sshInstance.py:54 connect: Network is unreachable

INFO     root:test_nics.py:206 packet lost during ping.
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:90
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_iperf_client_4hour.py:90: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:143
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_iperf_client_4hour.py:143: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:108
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:108: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:593
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:593: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:720
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:720: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:960
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:960: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_network_sriov_stress.py:1096
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:1096: PytestUnknownMarkWarning: Unknown pytest.mark.nicIperfTcpSUTGuestStress - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicIperfTcpSUTGuestStress

npxtester/Tests/testNics/test_network_sriov_stress.py:1097
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:1097: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:93
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:93: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:132
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:132: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:167
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:167: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:168
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:168: PytestUnknownMarkWarning: Unknown pytest.mark.test - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.test

npxtester/Tests/testNics/test_nics.py:256
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:256: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:282
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:282: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:325
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:325: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_simple_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_nics.py::Test_Nics::test_silver_ConnectivityReboot
FAILED npxtester/Tests/testNics/test_nics.py::Test_Nics::test_gold_PI_Networking_SRIOV_CheckDevice
===== 2 failed, 6 passed, 11 deselected, 16 warnings in 2308.86s (0:38:28) =====
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4Ix6O+hSs/J+WYhicXoVNFsq2LY7NwaGm8aSejP8W5cDAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRgg5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77aCbP8BPqPtor0AAAA=[0m[Pipeline] }
[8mha:////4GHchb786wl688erDJjASqsmJ9Hr4hPtHO8ytwYHX0MzAAAAoh+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IkMhon14bFL6hQa6F5D9uHMPlF/pr/IJHEyTvdc5bzemOdIo4cnWotdZ5S7VUfBjc/NXLsroFH1fJF1UyJg1WVHStu7GnBisViWZZjpbGxVAdOnpxgq1vzMEUw5IqzxNkdNHLf3PFEpueymChfmCJ2t6FJTL/O3wCmvhfk5V6QlR9NTCl7vQAAAA==[0m[Pipeline] // node
[8mha:////4N3Zwv+i78+NyT5x5Iut/zlc/vu2cqXlCZqUPy9nGyYaAAAAoh+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IkMhon14bFL6hQa6F5D9uHMPlF/pr/IJHEyTvdc5bzemOdIo4cnWotdZ5S7VUfBjc/NXLsroFH1fJF1UyJg1WVHStu7GnBisViWZZjpbGxVAdOnpxgq1vzMEUw5IqzxNkdNHLf3PFEpueymChfmCJ2t6FJTL/O3wCmvhfkZSnI9h9rVU4xvQAAAA==[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
