Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/cyp-test-nic-simple
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/cyp-test-nic-simple/npxtester
ls: cannot access '/root/.jenkins/workspace/cyp-test-nic-simple/npxtester': No such file or directory
[8mha:////4MftwC6NxviNjDdpfna9VBlJkoMp8EhRTGL2zcTKdEZ0AAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77aCbP8Brmfz270AAAA=[0m[Pipeline] }
[8mha:////4Kr9K7llyIIfXzIi7fTbyam3A+VyjB0I1hAyH+fEbXLCAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIMlYVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0gL0tBtv8Aj1Msdr0AAAA=[0m[Pipeline] // script
[8mha:////4FI2+bSiptyXTIERd0s3FW0AIUAVzDIQC15QCQE4LYPvAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRFDSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPyRmLRr0AAAA=[0m[Pipeline] }
[8mha:////4EIF7pCgSAhTUJ+YeVF144RCQBElcAy/oq5IQm3P5r/FAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRQlSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPw2Hi4r0AAAA=[0m[Pipeline] // stage
[8mha:////4O65h0jm98EO51SGQmOdf6FpfngMUfFS1Hkxj+qIATCfAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjpHSIitZywwtMYowT6y7YF5KKF/E1/oAhEhVb7ay0mucLyhThQNHJzmLvMTVeDmF0ucmJYn8JNMmOzrIhTBSs1HbS1NrjgprYwhJRwErB2mITKHl0DBvVmbupgkFXnTjmba+g8O0NHiBUNrOJ/IU5wvY6tonw5/krgHlgEDVDsas/x/INoKa7ysEAAAA=[0m[Pipeline] stage
[8mha:////4Cwh2bfnyXtsNeYvUrnMhkgZn3DOCE3ZIocZCmHhDj1kAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUSDAhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD5WQ+PfCAAAA[0m[Pipeline] { (clone)
[8mha:////4CFOXQFtiiA+7tA4CXv18jhcFszpIgsA6m3wBj5vXwoxAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiCmgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHN7LjSKW+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4JxnGUheoVbdA4jH7w1zuxcsCY2poKXOhDnLMn7NKJYFAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiCkSBqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGOY4V7vgAAAA==[0m[Pipeline] }
[8mha:////4D4+5H4RzROPZTW0wBHD+XjMhoO5mPw9EWUJAbCIJpuGAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiJAokRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g3N4dT9vgAAAA==[0m[Pipeline] // stage
[8mha:////4AJAGqZwaYqyNNZtbc8g6ZE112gHcOMJEUqcQ3uLTkOfAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJBqEqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A361JXbBAAAA[0m[Pipeline] stage
[8mha:////4PP68w9I/uoPNBdRzp82S+tTLGAqcpDjYGyOG/BwZs8HAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycogU2BDqxBp14QShCSFp9H9JUtKJE3E17kCgEhMeLNuS9Z4vqIKHhrxmVmFvMHSGDW7UObFEvr84SszSmXWEgZxirUotSXWca0tRwayihAWHpcLOUTCoI6y4FXdRO4G6PkWftwOH0sgbPKDgmRyFj98yeVhfRxkIf5y/AJiGCOV2n223+TyrN7xWSV3CAAAA[0m[Pipeline] { (set args)
[8mha:////4BsNiMtY/8UtmXAIxp6NV4VtqKiaHUkJeJGRvFkfJcU+AAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICtIgqreWGF5jYGCfWnbEdkooX8TX+QCASFVusdraZ5wuWKcKRo8XWUOcoNQ6D7+20cODYXTwP2PIZG6bE3qA0g2Rt6hklZwNzihIWAlaGGs/Jkc2wFq26q8orstUpx+k7CCidvsEDCjGZs4r5C2OEzbXXienn+SuAMWQo99tP7cIbaOP4NL4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/conf/change_args.py '{"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-21.02/","sut_conf":{"board_type":"commercial","host":"10.239.182.209","pf1":"ens785f2","os":"RHEL","PF1_NIC_type":"4*25"},"pkg_generator":{"host":"10.239.182.79","pf1":"ens787f2"},"drive_info":{"drive_version":"1.6.4"}}'
[8mha:////4AyFPX+UZcZf/6aTNXdj+lWE0Z2b4chbTZ9e7eCHFoeRAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKC0iIqWisNLzCJMXasO8d2cCpexNf4A4FIVGyx2tlmni9YxwBHDhqtot5QbA16N+p5YebQXx1ntHzBlimyU9io3HCnTgs2nBQsKUpYCdgoah1HQzrBVlh5l5WTpKtzCvN3EFCaboAHFGI2JxnSF6YAu9vYRaaf568AJu8TlHX9qf0b7E/nQb4AAAA=[0m[Pipeline] }
[8mha:////4AFg/aWh/jHSmrlH6sy1kKjz0TFBfVRN+miPQW2LyX/uAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIioEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcrdPtf28AEud0rYvgAAAA==[0m[Pipeline] // stage
[8mha:////4Bhd+KV1EsVM3bnXBHnMClLv0EnBj/3vPQbr+7HWEbmAAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjoXSIitZywwtMYowT6y7YF5KKF/E1/oAhEhVb7ay0mucLyhThQNHJzmLvMTVeDmF0ucmJYn8JNMmOzrIhTBSs1HbS1NrjgprYwhJRwErB2mITKHl0DBvVmbupgkFXnTjmba+g8O0NHiBUNrOJ/IU5wvY6tonw5/krgHlgEDVDsas/x/INPbxT+8EAAAA=[0m[Pipeline] stage
[8mha:////4P13TIuP26wSoF8WyLGiU1qV0Q6Z+QylTska1uSfBb7mAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUQjAhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD/hYjrHCAAAA[0m[Pipeline] { (run nic case)
[8mha:////4FM3oozjxgRBqafqHchkdSyZ1a7wU/MTBVKRbtZrSwmtAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiIUGDqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAEIWoEpvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics -s -m nicSimple --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_simple_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 19 items / 11 deselected / 8 selected

npxtester/Tests/testNics/test_mtu.py 2022-04-06 13:20:31 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_Jumbo_Packet_CVL_13_20_31/test_PI_Networking_Jumbo_Packet_CVL.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_Jumbo_Packet_CVL_13_20_31
2022-04-06 13:20:31 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-04-06 13:20:31 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-04-06 13:20:31 - test_mtu.py - [line:22] - root - INFO - ssh to the sut1
2022-04-06 13:20:31 - test_mtu.py - [line:24] - root - INFO - ssh to the sut1
2022-04-06 13:20:31 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:20:31 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:20:31 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 13:20:31 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:20:31 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:20:31 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 13:20:31 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 13:20:31 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 13:20:34 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 13:20:34 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 13:20:39 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 13:20:39 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 13:20:42 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 13:20:52 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:20:57 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 13:20:57 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 13:21:00 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 13:21:04 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:21:09 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 13:21:12 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:21:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:21:20 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 13:21:20 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 13:21:28 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 mtu 1500
2022-04-06 13:21:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:21:36 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 mtu 1500
2022-04-06 13:21:36 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:21:44 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 13:21:44 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 684 (684.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 17  bytes 2204 (2.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 13:21:53 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Apr  6 12:37:32 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | We are in France, we say Skappee.[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   | OK? Merci.[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |             -- Sebastien Chabal[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m[34m[1m   |[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-04-06 13:22:00 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="40:a6:b7:72:cc:ca")/IP(len=46)/Raw(load='X'*14480)],iface="ens787f2")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-04-06 13:22:03 - test_mtu.py - [line:92] - root - INFO - success to send package to network
2022-04-06 13:22:07 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="40:a6:b7:72:cc:ca")/IP(len=46)/Raw(load='X'*15500)],iface="ens787f2")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-04-06 13:22:10 - test_mtu.py - [line:102] - root - INFO - result is right
.2022-04-06 13:22:13 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 mtu 1500
2022-04-06 13:22:13 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:22:21 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 mtu 1500
2022-04-06 13:22:21 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:22:29 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 13:22:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:22:38 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-06 13:22:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:22:43 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-06 13:22:43 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-06/test_PI_Networking_Jumbo_Packet_CVL_13_20_31
2022-04-06 13:22:46 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-06 13:22:46 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:22:51 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-06 13:22:51 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-04-06 13:22:51 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-04-06 13:22:51 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_MTU_set_CVL_13_22_51/test_PI_Networking_MTU_set_CVL.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_MTU_set_CVL_13_22_51
2022-04-06 13:22:51 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_MTU_set_CVL case ============================
2022-04-06 13:22:51 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-04-06 13:22:51 - test_mtu.py - [line:22] - root - INFO - ssh to the sut1
2022-04-06 13:22:51 - test_mtu.py - [line:24] - root - INFO - ssh to the sut1
2022-04-06 13:22:51 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:22:51 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:22:51 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 13:22:51 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:22:51 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:22:51 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 13:22:51 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 13:22:51 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 13:22:54 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 13:22:54 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 13:22:59 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 13:22:59 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 13:23:02 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 13:23:13 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:23:18 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 13:23:18 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 13:23:21 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 13:23:25 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:23:30 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 13:23:33 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:23:33 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:23:41 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 13:23:41 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 13:23:49 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 mtu 1500
2022-04-06 13:23:49 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:23:57 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 mtu 2000
2022-04-06 13:23:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:24:06 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 13:24:06 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 127 (127.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 2384 (2.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 13:24:15 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Apr  6 13:33:09 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | Wanna support scapy? Star us on[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   | GitHub![0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |             -- Satoshi Nakamoto[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m[34m[1m   |[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-04-06 13:24:22 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="40:a6:b7:72:cc:ca")/IP(len=46)/Raw(load='X'*18890)],iface="ens787f2")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-04-06 13:24:25 - test_mtu.py - [line:132] - root - INFO - success to send package to network
2022-04-06 13:24:29 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="40:a6:b7:72:cc:ca")/IP(len=46)/Raw(load='X'*20010)],iface="ens787f2")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-04-06 13:24:32 - test_mtu.py - [line:142] - root - INFO - result is right
.2022-04-06 13:24:35 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 mtu 1500
2022-04-06 13:24:35 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:24:43 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 mtu 1500
2022-04-06 13:24:43 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:24:51 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 13:24:51 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:24:59 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-06 13:24:59 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:25:04 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-06 13:25:04 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-06/test_PI_Networking_MTU_set_CVL_13_22_51
2022-04-06 13:25:07 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-06 13:25:07 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:25:12 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-06 13:25:12 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-04-06 13:25:12 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_MTU_set_CVL case ============================
                                  [ 25%]
npxtester/Tests/testNics/test_nics.py 2022-04-06 13:25:12 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-04-06 13:25:12 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_silver_Networking_ConnectivityEnableDisable_13_25_12/test_silver_Networking_ConnectivityEnableDisable.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_silver_Networking_ConnectivityEnableDisable_13_25_12
2022-04-06 13:25:12 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-04-06 13:25:12 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-06 13:25:12 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-06 13:25:12 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:25:13 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:25:13 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 13:25:13 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:25:13 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:25:13 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 13:25:13 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 13:25:13 - test_nics.py - [line:44] - root - INFO - --Start rmmod irdma --
2022-04-06 13:25:16 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 13:25:16 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 13:25:21 - test_nics.py - [line:46] - root - INFO - --Finish rmmod irdma --
2022-04-06 13:25:21 - test_nics.py - [line:47] - root - INFO - --Start rmmod ice --
2022-04-06 13:25:24 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 13:25:35 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:25:40 - test_nics.py - [line:49] - root - INFO - --Finish rmmod ice --
2022-04-06 13:25:40 - test_nics.py - [line:50] - root - INFO - --Start modprobe ice --
2022-04-06 13:25:43 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 13:25:47 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:25:52 - test_nics.py - [line:52] - root - INFO - --Finish modprobe ice --
2022-04-06 13:25:55 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:25:55 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:26:03 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2 | grep ^version:
2022-04-06 13:26:03 - sshInstance.py - [line:54] - root - INFO - version: 1.6.4

2022-04-06 13:26:08 - test_nics.py - [line:58] - root - INFO - Passed: driver version is what expected.
2022-04-06 13:26:08 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 13:26:11 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 13:26:11 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 13:26:16 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 13:26:16 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 13:26:19 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 13:26:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:26:35 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 13:26:35 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 13:26:38 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 13:26:43 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:26:48 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 13:26:51 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:26:51 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:26:59 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 13:26:59 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 13:27:07 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 13:27:07 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 811 (811.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 17  bytes 2314 (2.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 13:27:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-06 13:27:15 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 5376330096  bytes 8139740964750 (7.4 TiB)
        RX errors 1  dropped 0  overruns 0  frame 1
        TX packets 259833728  bytes 17262614370 (16.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 13:27:23 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:27:23 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:27:31 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-06 13:27:31 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:27:40 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Apr  6 13:37:28 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.052 ms
2022-04-06 13:27:41 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.022 ms
2022-04-06 13:27:42 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.024 ms
2022-04-06 13:27:43 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.028 ms
2022-04-06 13:27:44 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.025 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 93ms
rtt min/avg/max/mdev = 0.022/0.030/0.052/0.011 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:27:53 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 down
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:28:02 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 up
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:28:08 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:28:08 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:28:17 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.046 ms
2022-04-06 13:28:18 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.024 ms
2022-04-06 13:28:19 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.010 ms
2022-04-06 13:28:20 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.048 ms
2022-04-06 13:28:21 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.032 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 87ms
rtt min/avg/max/mdev = 0.010/0.032/0.048/0.014 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:28:30 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 down
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:28:39 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 up
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:28:45 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:28:45 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:28:54 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.052 ms
2022-04-06 13:28:55 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.023 ms
2022-04-06 13:28:56 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.025 ms
2022-04-06 13:28:57 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.025 ms
2022-04-06 13:28:58 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.027 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 113ms
rtt min/avg/max/mdev = 0.023/0.030/0.052/0.011 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:29:07 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 down
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:29:16 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 up
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:29:22 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:29:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:29:31 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.061 ms
2022-04-06 13:29:32 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.031 ms
2022-04-06 13:29:33 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.024 ms
2022-04-06 13:29:34 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.032 ms
2022-04-06 13:29:35 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.022 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 90ms
rtt min/avg/max/mdev = 0.022/0.034/0.061/0.014 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:29:44 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 down
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:29:53 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 up
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:29:59 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:29:59 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:30:08 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.048 ms
2022-04-06 13:30:09 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.010 ms
2022-04-06 13:30:10 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.029 ms
2022-04-06 13:30:11 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.025 ms
2022-04-06 13:30:12 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.029 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 131ms
rtt min/avg/max/mdev = 0.010/0.028/0.048/0.012 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:30:21 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 down
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:30:31 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 up
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:30:37 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:30:37 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:30:46 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.057 ms
2022-04-06 13:30:47 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.025 ms
2022-04-06 13:30:48 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.017 ms
2022-04-06 13:30:49 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.023 ms
2022-04-06 13:30:50 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.029 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 108ms
rtt min/avg/max/mdev = 0.017/0.030/0.057/0.014 ms
[root@npx-cyp7-rh82 ~]# 
.2022-04-06 13:30:56 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 13:30:56 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:31:04 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 13:31:04 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:31:12 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-06 13:31:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:31:20 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-06 13:31:20 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:31:28 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-06 13:31:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:31:33 - test_nics.py - [line:87] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-06 13:31:33 - test_nics.py - [line:89] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-06/test_silver_Networking_ConnectivityEnableDisable_13_25_12
2022-04-06 13:31:36 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-06 13:31:36 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:31:41 - test_nics.py - [line:91] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-06 13:31:41 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 13:31:41 - test_nics.py - [line:93] - root - INFO - this is Test_Nics teardown
2022-04-06 13:31:41 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-04-06 13:31:41 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_silver_ConnectivityReboot_13_31_41/test_silver_ConnectivityReboot.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_silver_ConnectivityReboot_13_31_41
2022-04-06 13:31:41 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_silver_ConnectivityReboot case ============================
2022-04-06 13:31:41 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-06 13:31:41 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-06 13:31:41 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:31:41 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:31:41 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 13:31:41 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:31:41 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:31:42 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 13:31:42 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 13:31:42 - test_nics.py - [line:44] - root - INFO - --Start rmmod irdma --
2022-04-06 13:31:45 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 13:31:45 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 13:31:50 - test_nics.py - [line:46] - root - INFO - --Finish rmmod irdma --
2022-04-06 13:31:50 - test_nics.py - [line:47] - root - INFO - --Start rmmod ice --
2022-04-06 13:31:53 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 13:32:03 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:32:08 - test_nics.py - [line:49] - root - INFO - --Finish rmmod ice --
2022-04-06 13:32:08 - test_nics.py - [line:50] - root - INFO - --Start modprobe ice --
2022-04-06 13:32:11 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 13:32:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:32:21 - test_nics.py - [line:52] - root - INFO - --Finish modprobe ice --
2022-04-06 13:32:24 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:32:24 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:32:32 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2 | grep ^version:
2022-04-06 13:32:32 - sshInstance.py - [line:54] - root - INFO - version: 1.6.4

2022-04-06 13:32:37 - test_nics.py - [line:58] - root - INFO - Passed: driver version is what expected.
2022-04-06 13:32:37 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 13:32:40 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 13:32:40 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 13:32:45 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 13:32:45 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 13:32:48 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 13:33:00 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:33:05 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 13:33:05 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 13:33:08 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 13:33:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:33:17 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 13:33:20 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:33:21 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:33:29 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 13:33:29 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 13:33:37 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 13:33:37 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 2134 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 13:33:45 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-06 13:33:45 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 5376330310  bytes 8139740994177 (7.4 TiB)
        RX errors 1  dropped 0  overruns 0  frame 1
        TX packets 259833754  bytes 17262620139 (16.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 13:33:53 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-06 13:33:53 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:34:01 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:34:01 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:34:06 - test_nics.py - [line:136] - root - INFO - -- reboot 1 times --
2022-04-06 13:34:10 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Apr  6 13:43:57 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# ping -c 5 192.168.10.11
PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.478 ms
2022-04-06 13:34:11 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.201 ms
2022-04-06 13:34:12 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.188 ms
2022-04-06 13:34:13 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.227 ms
2022-04-06 13:34:14 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.191 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 89ms
rtt min/avg/max/mdev = 0.188/0.257/0.478/0.111 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:34:21 - sshInstance.py - [line:75] - root - INFO - ping6 -c 5 -I ens785f2 fe80::42a6:b7ff:fe82:eb6
ping6: Warning: source address might be selected on device other than ens785f2.
PING fe80::42a6:b7ff:fe82:eb6(fe80::42a6:b7ff:fe82:eb6) from :: ens785f2: 56 data bytes
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=1 ttl=64 time=0.479 ms
2022-04-06 13:34:22 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=2 ttl=64 time=0.236 ms
2022-04-06 13:34:23 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=3 ttl=64 time=0.244 ms
2022-04-06 13:34:24 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=4 ttl=64 time=0.230 ms
2022-04-06 13:34:25 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=5 ttl=64 time=0.204 ms

--- fe80::42a6:b7ff:fe82:eb6 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 83ms
rtt min/avg/max/mdev = 0.204/0.278/0.479/0.102 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:34:34 - sshInstance.py - [line:99] - root - INFO - reboot

2022-04-06 13:34:37 - sshInstance.py - [line:159] - root - INFO - sut server reboot, please wait ......
2022-04-06 13:35:37 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:35:42 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:35:42 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:35:42 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:35:42 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 135ms
2022-04-06 13:35:42 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:35:42 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:35:42 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:35:47 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:35:52 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:35:52 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:35:52 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:35:52 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 109ms
2022-04-06 13:35:52 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:35:52 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:35:52 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:35:57 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:36:02 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:36:02 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:02 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:36:02 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 84ms
2022-04-06 13:36:02 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:02 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:02 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:36:07 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:36:12 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:36:12 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:12 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:36:12 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 123ms
2022-04-06 13:36:12 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:12 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:12 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:36:17 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:36:22 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:36:22 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:22 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:36:22 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 97ms
2022-04-06 13:36:22 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:22 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:22 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:36:27 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.354 ms
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.372 ms
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.322 ms
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.369 ms
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.360 ms
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 135ms
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.322/0.355/0.372/0.024 ms
2022-04-06 13:36:32 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:36:32 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:36:32 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 13:39:32 - test_nics.py - [line:136] - root - INFO - -- reboot 2 times --
2022-04-06 13:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:39:32 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:39:32 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 13:39:35 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:39:35 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:39:43 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:39:43 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:39:52 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Apr  6 13:48:55 2022
[root@npx-cyp7-rh82 ~]# ping -c 5 192.168.10.11
PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.442 ms
2022-04-06 13:39:53 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.199 ms
2022-04-06 13:39:54 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.201 ms
2022-04-06 13:39:55 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.188 ms
2022-04-06 13:39:56 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.181 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 92ms
rtt min/avg/max/mdev = 0.181/0.242/0.442/0.100 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:40:03 - sshInstance.py - [line:75] - root - INFO - ping6 -c 5 -I ens785f2 fe80::42a6:b7ff:fe82:eb6
ping6: Warning: source address might be selected on device other than ens785f2.
PING fe80::42a6:b7ff:fe82:eb6(fe80::42a6:b7ff:fe82:eb6) from :: ens785f2: 56 data bytes
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=1 ttl=64 time=0.449 ms
2022-04-06 13:40:04 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=2 ttl=64 time=0.217 ms
2022-04-06 13:40:05 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=3 ttl=64 time=0.190 ms
2022-04-06 13:40:06 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=4 ttl=64 time=0.208 ms
2022-04-06 13:40:07 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=5 ttl=64 time=0.192 ms

--- fe80::42a6:b7ff:fe82:eb6 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 85ms
rtt min/avg/max/mdev = 0.190/0.251/0.449/0.099 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:40:16 - sshInstance.py - [line:99] - root - INFO - reboot

2022-04-06 13:40:19 - sshInstance.py - [line:159] - root - INFO - sut server reboot, please wait ......
2022-04-06 13:41:19 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:41:24 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:41:24 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:24 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:41:24 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 128ms
2022-04-06 13:41:24 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:24 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:24 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:41:29 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:41:34 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:41:34 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:34 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:41:34 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 101ms
2022-04-06 13:41:34 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:34 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:34 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:41:39 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:41:44 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:41:44 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:44 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:41:44 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 139ms
2022-04-06 13:41:44 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:44 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:44 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:41:49 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:41:54 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:41:54 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:54 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:41:54 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 114ms
2022-04-06 13:41:54 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:54 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:41:54 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:41:59 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:42:04 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:42:04 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:04 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:42:04 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 88ms
2022-04-06 13:42:04 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:04 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:04 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:42:09 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:42:14 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:42:14 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:14 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:42:14 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 127ms
2022-04-06 13:42:14 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:14 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:14 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:42:19 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:42:24 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:42:24 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:24 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:42:24 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 101ms
2022-04-06 13:42:24 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:24 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:24 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:42:29 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.340 ms
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.376 ms
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.390 ms
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.403 ms
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.373 ms
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 140ms
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.340/0.376/0.403/0.027 ms
2022-04-06 13:42:34 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:42:34 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:42:34 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 13:45:34 - test_nics.py - [line:136] - root - INFO - -- reboot 3 times --
2022-04-06 13:45:34 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:45:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:45:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 13:45:38 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:45:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:45:46 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:45:46 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:45:55 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Apr  6 13:54:54 2022
[root@npx-cyp7-rh82 ~]# ping -c 5 192.168.10.11
PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.452 ms
2022-04-06 13:45:56 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.197 ms
2022-04-06 13:45:57 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.189 ms
2022-04-06 13:45:58 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.196 ms
2022-04-06 13:45:59 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.195 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 83ms
rtt min/avg/max/mdev = 0.189/0.245/0.452/0.105 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:46:06 - sshInstance.py - [line:75] - root - INFO - ping6 -c 5 -I ens785f2 fe80::42a6:b7ff:fe82:eb6
ping6: Warning: source address might be selected on device other than ens785f2.
PING fe80::42a6:b7ff:fe82:eb6(fe80::42a6:b7ff:fe82:eb6) from :: ens785f2: 56 data bytes
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=1 ttl=64 time=0.475 ms
2022-04-06 13:46:07 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=2 ttl=64 time=0.208 ms
2022-04-06 13:46:08 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=3 ttl=64 time=0.190 ms
2022-04-06 13:46:09 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=4 ttl=64 time=0.196 ms
2022-04-06 13:46:10 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=5 ttl=64 time=0.184 ms

--- fe80::42a6:b7ff:fe82:eb6 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 77ms
rtt min/avg/max/mdev = 0.184/0.250/0.475/0.113 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:46:19 - sshInstance.py - [line:99] - root - INFO - reboot

2022-04-06 13:46:22 - sshInstance.py - [line:159] - root - INFO - sut server reboot, please wait ......
2022-04-06 13:47:22 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:47:27 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:47:27 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:27 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:47:27 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 130ms
2022-04-06 13:47:27 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:27 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:27 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:47:32 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:47:37 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:47:37 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:37 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:47:37 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 104ms
2022-04-06 13:47:37 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:37 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:37 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:47:42 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:47:47 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:47:47 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:47 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:47:47 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 79ms
2022-04-06 13:47:47 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:47 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:47 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:47:52 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:47:57 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:47:57 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:57 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:47:57 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 117ms
2022-04-06 13:47:57 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:57 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:47:57 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:48:02 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:48:07 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:48:07 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:48:07 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:48:07 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 92ms
2022-04-06 13:48:07 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:48:07 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:48:07 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:48:12 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.329 ms
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.401 ms
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.389 ms
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.373 ms
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.382 ms
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 130ms
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.329/0.374/0.401/0.034 ms
2022-04-06 13:48:17 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:48:17 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:48:17 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 13:51:17 - test_nics.py - [line:136] - root - INFO - -- reboot 4 times --
2022-04-06 13:51:17 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:51:17 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:51:17 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 13:51:20 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:51:20 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:51:28 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:51:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:51:37 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Apr  6 14:00:40 2022
[root@npx-cyp7-rh82 ~]# ping -c 5 192.168.10.11
PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.445 ms
2022-04-06 13:51:38 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.206 ms
2022-04-06 13:51:39 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.196 ms
2022-04-06 13:51:40 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.194 ms
2022-04-06 13:51:41 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.192 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 131ms
rtt min/avg/max/mdev = 0.192/0.246/0.445/0.100 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:51:48 - sshInstance.py - [line:75] - root - INFO - ping6 -c 5 -I ens785f2 fe80::42a6:b7ff:fe82:eb6
ping6: Warning: source address might be selected on device other than ens785f2.
PING fe80::42a6:b7ff:fe82:eb6(fe80::42a6:b7ff:fe82:eb6) from :: ens785f2: 56 data bytes
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=1 ttl=64 time=0.494 ms
2022-04-06 13:51:49 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=2 ttl=64 time=0.240 ms
2022-04-06 13:51:50 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=3 ttl=64 time=0.219 ms
2022-04-06 13:51:51 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=4 ttl=64 time=0.231 ms
2022-04-06 13:51:52 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=5 ttl=64 time=0.217 ms

--- fe80::42a6:b7ff:fe82:eb6 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 125ms
rtt min/avg/max/mdev = 0.217/0.280/0.494/0.107 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:52:01 - sshInstance.py - [line:99] - root - INFO - reboot

2022-04-06 13:52:04 - sshInstance.py - [line:159] - root - INFO - sut server reboot, please wait ......
2022-04-06 13:53:04 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:53:09 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:53:09 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:09 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:53:09 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 97ms
2022-04-06 13:53:09 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:09 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:09 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:53:14 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:53:19 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:53:19 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:19 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:53:19 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 134ms
2022-04-06 13:53:19 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:19 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:19 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:53:24 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:53:29 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:53:29 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:29 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:53:29 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 109ms
2022-04-06 13:53:29 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:29 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:29 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:53:34 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:53:39 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:53:39 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:39 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:53:39 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 82ms
2022-04-06 13:53:39 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:39 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:39 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:53:44 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:53:49 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:53:49 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:49 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:53:49 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 121ms
2022-04-06 13:53:49 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:49 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:49 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:53:54 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.366 ms
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.319 ms
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.430 ms
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 3 received, 40% packet loss, time 96ms
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.319/0.371/0.430/0.050 ms
2022-04-06 13:53:59 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:53:59 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:54:04 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.326 ms
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.377 ms
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.379 ms
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.380 ms
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.380 ms
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 134ms
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.326/0.368/0.380/0.027 ms
2022-04-06 13:54:09 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:54:09 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:54:09 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 13:57:09 - test_nics.py - [line:136] - root - INFO - -- reboot 5 times --
2022-04-06 13:57:09 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 13:57:09 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 13:57:10 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 13:57:13 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 13:57:13 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:57:21 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 13:57:21 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 13:57:30 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Apr  6 14:06:25 2022
[root@npx-cyp7-rh82 ~]# ping -c 5 192.168.10.11
PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.424 ms
2022-04-06 13:57:31 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.197 ms
2022-04-06 13:57:32 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.193 ms
2022-04-06 13:57:33 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.193 ms
2022-04-06 13:57:34 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.190 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 131ms
rtt min/avg/max/mdev = 0.190/0.239/0.424/0.093 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:57:41 - sshInstance.py - [line:75] - root - INFO - ping6 -c 5 -I ens785f2 fe80::42a6:b7ff:fe82:eb6
ping6: Warning: source address might be selected on device other than ens785f2.
PING fe80::42a6:b7ff:fe82:eb6(fe80::42a6:b7ff:fe82:eb6) from :: ens785f2: 56 data bytes
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=1 ttl=64 time=0.461 ms
2022-04-06 13:57:42 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=2 ttl=64 time=0.215 ms
2022-04-06 13:57:43 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=3 ttl=64 time=0.199 ms
2022-04-06 13:57:44 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=4 ttl=64 time=0.198 ms
2022-04-06 13:57:45 - sshInstance.py - [line:75] - root - INFO - 64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=5 ttl=64 time=0.146 ms

--- fe80::42a6:b7ff:fe82:eb6 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 126ms
rtt min/avg/max/mdev = 0.146/0.243/0.461/0.112 ms
[root@npx-cyp7-rh82 ~]# 
2022-04-06 13:57:54 - sshInstance.py - [line:99] - root - INFO - reboot

2022-04-06 13:57:57 - sshInstance.py - [line:159] - root - INFO - sut server reboot, please wait ......
2022-04-06 13:58:57 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:59:02 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:59:02 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:02 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:59:02 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 102ms
2022-04-06 13:59:02 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:02 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:02 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:59:07 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:59:12 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:59:12 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:12 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:59:12 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 140ms
2022-04-06 13:59:12 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:12 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:12 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:59:17 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:59:22 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:59:22 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:22 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:59:22 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 114ms
2022-04-06 13:59:22 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:22 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:22 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:59:27 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:59:32 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:59:32 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:32 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:59:32 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 88ms
2022-04-06 13:59:32 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:32 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:32 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:59:37 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:59:42 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:59:42 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:42 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:59:42 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 0 received, 100% packet loss, time 126ms
2022-04-06 13:59:42 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:42 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:42 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:59:47 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.374 ms
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.384 ms
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.265 ms
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.380 ms
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 4 received, 20% packet loss, time 100ms
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.265/0.350/0.384/0.054 ms
2022-04-06 13:59:52 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 13:59:52 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 13:59:57 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.381 ms
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.288 ms
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.376 ms
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.368 ms
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.376 ms
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 137ms
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.288/0.357/0.381/0.042 ms
2022-04-06 14:00:02 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 14:00:02 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 14:00:02 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
.2022-04-06 14:03:05 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:03:05 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:03:05 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:03:05 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 14:03:05 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 14:03:08 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:03:08 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:03:16 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-06 14:03:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:03:24 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-06 14:03:24 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:03:32 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-06 14:03:32 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:03:37 - test_nics.py - [line:87] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-06 14:03:37 - test_nics.py - [line:89] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-06/test_silver_ConnectivityReboot_13_31_41
2022-04-06 14:03:40 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-06 14:03:40 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:03:45 - test_nics.py - [line:91] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-06 14:03:45 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 14:03:45 - test_nics.py - [line:93] - root - INFO - this is Test_Nics teardown
2022-04-06 14:03:45 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_silver_ConnectivityReboot case ============================
2022-04-06 14:03:45 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_gold_PI_Networking_SRIOV_CheckDevice_14_03_45/test_gold_PI_Networking_SRIOV_CheckDevice.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_gold_PI_Networking_SRIOV_CheckDevice_14_03_45
2022-04-06 14:03:45 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-04-06 14:03:45 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-06 14:03:45 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-06 14:03:46 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:03:46 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:03:46 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 14:03:46 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:03:46 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:03:46 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 14:03:46 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 14:03:46 - test_nics.py - [line:44] - root - INFO - --Start rmmod irdma --
2022-04-06 14:03:49 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:03:49 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:03:54 - test_nics.py - [line:46] - root - INFO - --Finish rmmod irdma --
2022-04-06 14:03:54 - test_nics.py - [line:47] - root - INFO - --Start rmmod ice --
2022-04-06 14:03:57 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:04:08 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:04:13 - test_nics.py - [line:49] - root - INFO - --Finish rmmod ice --
2022-04-06 14:04:13 - test_nics.py - [line:50] - root - INFO - --Start modprobe ice --
2022-04-06 14:04:16 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:04:20 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:04:25 - test_nics.py - [line:52] - root - INFO - --Finish modprobe ice --
2022-04-06 14:04:28 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:04:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:04:36 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2 | grep ^version:
2022-04-06 14:04:36 - sshInstance.py - [line:54] - root - INFO - version: 1.6.4

2022-04-06 14:04:41 - test_nics.py - [line:58] - root - INFO - Passed: driver version is what expected.
2022-04-06 14:04:41 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 14:04:44 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:04:44 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:04:49 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 14:04:49 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 14:04:52 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:05:04 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:05:09 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 14:05:09 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 14:05:12 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:05:17 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:05:22 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 14:05:25 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:05:25 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:05:33 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 14:05:33 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 14:05:41 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 14:05:41 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 2134 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:05:49 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-06 14:05:49 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 5376330685  bytes 8139741048664 (7.4 TiB)
        RX errors 1  dropped 0  overruns 0  frame 1
        TX packets 259833902  bytes 17262644324 (16.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:05:57 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:05:57 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:05 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11

2022-04-06 14:06:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:13 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v0 192.168.10.11
2022-04-06 14:06:13 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:21 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v1 192.168.10.12
2022-04-06 14:06:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:30 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v2 192.168.10.13
2022-04-06 14:06:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:38 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v3 192.168.10.14
2022-04-06 14:06:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:46 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11
2022-04-06 14:07:00 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 96ms


F2022-04-06 14:07:08 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:07:11 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:07:19 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:07:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:07:27 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-06 14:07:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:07:35 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-06 14:07:35 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:07:43 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-06 14:07:43 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:07:48 - test_nics.py - [line:87] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-06 14:07:48 - test_nics.py - [line:89] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-06/test_gold_PI_Networking_SRIOV_CheckDevice_14_03_45
2022-04-06 14:07:51 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-06 14:07:51 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:07:56 - test_nics.py - [line:91] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-06 14:07:56 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 14:07:56 - test_nics.py - [line:93] - root - INFO - this is Test_Nics teardown
2022-04-06 14:07:56 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-04-06 14:07:56 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_InternetProtocolv4v6_14_07_56/test_PI_Networking_InternetProtocolv4v6.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_InternetProtocolv4v6_14_07_56
2022-04-06 14:07:56 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_InternetProtocolv4v6 case ============================
2022-04-06 14:07:56 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-06 14:07:56 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-06 14:07:56 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:07:56 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:07:56 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 14:07:56 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:07:57 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:07:57 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 14:07:57 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 14:07:57 - test_nics.py - [line:44] - root - INFO - --Start rmmod irdma --
2022-04-06 14:08:00 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:08:00 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:08:05 - test_nics.py - [line:46] - root - INFO - --Finish rmmod irdma --
2022-04-06 14:08:05 - test_nics.py - [line:47] - root - INFO - --Start rmmod ice --
2022-04-06 14:08:08 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:08:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:08:24 - test_nics.py - [line:49] - root - INFO - --Finish rmmod ice --
2022-04-06 14:08:24 - test_nics.py - [line:50] - root - INFO - --Start modprobe ice --
2022-04-06 14:08:28 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:08:32 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:08:37 - test_nics.py - [line:52] - root - INFO - --Finish modprobe ice --
2022-04-06 14:08:40 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:08:40 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:08:48 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2 | grep ^version:
2022-04-06 14:08:48 - sshInstance.py - [line:54] - root - INFO - version: 1.6.4

2022-04-06 14:08:53 - test_nics.py - [line:58] - root - INFO - Passed: driver version is what expected.
2022-04-06 14:08:53 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 14:08:56 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:08:56 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:09:01 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 14:09:01 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 14:09:04 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:09:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:09:21 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 14:09:21 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 14:09:24 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:09:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:09:33 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 14:09:36 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:09:36 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:09:44 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 14:09:44 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 14:09:52 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 14:09:52 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 469 (469.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 17  bytes 2314 (2.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:10:00 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-06 14:10:00 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 5376330910  bytes 8139741085698 (7.4 TiB)
        RX errors 1  dropped 0  overruns 0  frame 1
        TX packets 259833924  bytes 17262649080 (16.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:10:08 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 14:10:08 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:10:16 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-06 14:10:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:10:24 - sshInstance.py - [line:50] - root - INFO - ping -w 5 192.168.10.11
2022-04-06 14:10:29 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.485 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.194 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.188 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.172 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.198 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 137ms
rtt min/avg/max/mdev = 0.172/0.247/0.485/0.119 ms

2022-04-06 14:10:37 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens785f2 fe80::42a6:b7ff:fe82:eb6
2022-04-06 14:10:42 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than ens785f2.
PING fe80::42a6:b7ff:fe82:eb6(fe80::42a6:b7ff:fe82:eb6) from :: ens785f2: 56 data bytes
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=1 ttl=64 time=0.513 ms
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=2 ttl=64 time=0.201 ms
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=3 ttl=64 time=0.199 ms
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=4 ttl=64 time=0.190 ms
64 bytes from fe80::42a6:b7ff:fe82:eb6%ens785f2: icmp_seq=5 ttl=64 time=0.189 ms

--- fe80::42a6:b7ff:fe82:eb6 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 85ms
rtt min/avg/max/mdev = 0.189/0.258/0.513/0.128 ms

.2022-04-06 14:10:50 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:10:50 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:10:58 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:10:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:11:06 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-06 14:11:06 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:11:14 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-06 14:11:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:11:22 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-06 14:11:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:11:27 - test_nics.py - [line:87] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-06 14:11:27 - test_nics.py - [line:89] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-06/test_PI_Networking_InternetProtocolv4v6_14_07_56
2022-04-06 14:11:30 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-06 14:11:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:11:35 - test_nics.py - [line:91] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-06 14:11:35 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 14:11:35 - test_nics.py - [line:93] - root - INFO - this is Test_Nics teardown
2022-04-06 14:11:35 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_InternetProtocolv4v6 case ============================
2022-04-06 14:11:35 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_Link_State_Check_14_11_35/test_PI_Networking_Link_State_Check.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_Link_State_Check_14_11_35
2022-04-06 14:11:35 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_Link_State_Check case ============================
2022-04-06 14:11:35 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-06 14:11:35 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-06 14:11:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:11:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:11:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 14:11:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:11:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:11:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 14:11:35 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 14:11:35 - test_nics.py - [line:44] - root - INFO - --Start rmmod irdma --
2022-04-06 14:11:38 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:11:38 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:11:43 - test_nics.py - [line:46] - root - INFO - --Finish rmmod irdma --
2022-04-06 14:11:43 - test_nics.py - [line:47] - root - INFO - --Start rmmod ice --
2022-04-06 14:11:46 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:11:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:12:03 - test_nics.py - [line:49] - root - INFO - --Finish rmmod ice --
2022-04-06 14:12:03 - test_nics.py - [line:50] - root - INFO - --Start modprobe ice --
2022-04-06 14:12:06 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:12:10 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:12:15 - test_nics.py - [line:52] - root - INFO - --Finish modprobe ice --
2022-04-06 14:12:18 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:12:18 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:12:26 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2 | grep ^version:
2022-04-06 14:12:26 - sshInstance.py - [line:54] - root - INFO - version: 1.6.4

2022-04-06 14:12:31 - test_nics.py - [line:58] - root - INFO - Passed: driver version is what expected.
2022-04-06 14:12:31 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 14:12:34 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:12:34 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:12:39 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 14:12:39 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 14:12:42 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:12:54 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:12:59 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 14:12:59 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 14:13:02 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:13:06 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:13:11 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 14:13:14 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:13:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:13:22 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 14:13:22 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 14:13:30 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 14:13:30 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 2134 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:13:38 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-06 14:13:38 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 5376330972  bytes 8139741093788 (7.4 TiB)
        RX errors 1  dropped 0  overruns 0  frame 1
        TX packets 259833956  bytes 17262654307 (16.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:13:47 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
2022-04-06 14:13:47 - sshInstance.py - [line:54] - root - INFO - 0000:4b:00.2

2022-04-06 14:13:55 - sshInstance.py - [line:50] - root - INFO - lspci -vvs 00:4b:00.2 | grep LnkCap:
2022-04-06 14:13:55 - sshInstance.py - [line:54] - root - INFO - 		LnkCap:	Port #0, Speed 16GT/s, Width x16, ASPM not supported

2022-04-06 14:14:03 - sshInstance.py - [line:50] - root - INFO - lspci -vvs 00:4b:00.2 | grep LnkSta:
2022-04-06 14:14:03 - sshInstance.py - [line:54] - root - INFO - 		LnkSta:	Speed 16GT/s, Width x16, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-

2022-04-06 14:14:08 - test_nics.py - [line:266] - root - INFO - --check the speed and width of the ethernet ens785f2
2022-04-06 14:14:08 - test_nics.py - [line:270] - root - INFO - the linkCap and LnkSta value are matched. The speed and width value are: 16GT/s and Width x16.
.2022-04-06 14:14:11 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:14:11 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:14:19 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:14:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:14:27 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-06 14:14:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:14:35 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-06 14:14:35 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:14:43 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-06 14:14:43 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:14:48 - test_nics.py - [line:87] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-06 14:14:48 - test_nics.py - [line:89] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-06/test_PI_Networking_Link_State_Check_14_11_35
2022-04-06 14:14:51 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-06 14:14:51 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:14:56 - test_nics.py - [line:91] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-06 14:14:56 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 14:14:56 - test_nics.py - [line:93] - root - INFO - this is Test_Nics teardown
2022-04-06 14:14:56 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_Link_State_Check case ============================
2022-04-06 14:14:56 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_ConnectivityShutdown_14_14_56/test_PI_Networking_ConnectivityShutdown.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_ConnectivityShutdown_14_14_56
2022-04-06 14:14:56 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_ConnectivityShutdown case ============================
2022-04-06 14:14:56 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-06 14:14:56 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-06 14:14:56 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:14:56 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:14:57 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 14:14:57 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:14:57 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:14:57 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 14:14:57 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 14:14:57 - test_nics.py - [line:44] - root - INFO - --Start rmmod irdma --
2022-04-06 14:15:00 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:15:00 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:15:05 - test_nics.py - [line:46] - root - INFO - --Finish rmmod irdma --
2022-04-06 14:15:05 - test_nics.py - [line:47] - root - INFO - --Start rmmod ice --
2022-04-06 14:15:08 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:15:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:15:24 - test_nics.py - [line:49] - root - INFO - --Finish rmmod ice --
2022-04-06 14:15:24 - test_nics.py - [line:50] - root - INFO - --Start modprobe ice --
2022-04-06 14:15:27 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:15:32 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:15:37 - test_nics.py - [line:52] - root - INFO - --Finish modprobe ice --
2022-04-06 14:15:40 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:15:40 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:15:48 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2 | grep ^version:
2022-04-06 14:15:48 - sshInstance.py - [line:54] - root - INFO - version: 1.6.4

2022-04-06 14:15:53 - test_nics.py - [line:58] - root - INFO - Passed: driver version is what expected.
2022-04-06 14:15:53 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 14:15:56 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:15:56 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:16:01 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 14:16:01 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 14:16:04 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:16:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:16:19 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 14:16:19 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 14:16:22 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:16:26 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:16:31 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 14:16:34 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:16:35 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:16:43 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 14:16:43 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 14:16:51 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 14:16:51 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 2134 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:16:59 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-06 14:16:59 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 5376331011  bytes 8139741098986 (7.4 TiB)
        RX errors 1  dropped 0  overruns 0  frame 1
        TX packets 259833965  bytes 17262656525 (16.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:17:07 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-06 14:17:07 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:17:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 14:17:15 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:17:23 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11

2022-04-06 14:17:27 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.482 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.192 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.183 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.185 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.183 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 92ms
rtt min/avg/max/mdev = 0.183/0.245/0.482/0.118 ms

2022-04-06 14:17:32 - power.py - [line:18] - root - INFO - checking the machine status
2022-04-06 14:17:32 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status
....
2022-04-06 14:17:52 - commonFunc.py - [line:25] - root - ERROR - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:17:52 - commonFunc.py - [line:26] - root - INFO - fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status

2022-04-06 14:17:52 - power.py - [line:22] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:17:52 - test_nics.py - [line:311] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:17:52 - sshInstance.py - [line:143] - root - INFO - ping sut, please wait ......
2022-04-06 14:18:52 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.415 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.327 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.384 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.396 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.387 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 78ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.327/0.381/0.415/0.038 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 14:18:57 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 14:18:57 - power.py - [line:39] - root - INFO - starting to power off the machine....
2022-04-06 14:18:57 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power off
....
2022-04-06 14:19:17 - commonFunc.py - [line:25] - root - ERROR - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:19:17 - commonFunc.py - [line:26] - root - INFO - fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power off

2022-04-06 14:19:17 - power.py - [line:44] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:19:17 - test_nics.py - [line:314] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:19:27 - power.py - [line:18] - root - INFO - checking the machine status
2022-04-06 14:19:27 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status
....
2022-04-06 14:19:47 - commonFunc.py - [line:25] - root - ERROR - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:19:47 - commonFunc.py - [line:26] - root - INFO - fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status

2022-04-06 14:19:47 - power.py - [line:22] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
F2022-04-06 14:19:50 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:19:50 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:19:58 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:19:58 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:20:06 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 0
2022-04-06 14:20:07 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:20:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 0
2022-04-06 14:20:15 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:20:23 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-06 14:20:23 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:20:28 - test_nics.py - [line:87] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-06 14:20:28 - test_nics.py - [line:89] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-06/test_PI_Networking_ConnectivityShutdown_14_14_56
2022-04-06 14:20:31 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-06 14:20:31 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:20:36 - test_nics.py - [line:91] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-06 14:20:36 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-06 14:20:36 - test_nics.py - [line:93] - root - INFO - this is Test_Nics teardown
2022-04-06 14:20:36 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_ConnectivityShutdown case ============================
                             [100%]

=================================== FAILURES ===================================
_____________ Test_Nics.test_gold_PI_Networking_SRIOV_CheckDevice ______________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7f8179d4a320>

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicGold
    @pytest.mark.nicSilver
    @pytest.mark.nicSimple
    def test_gold_PI_Networking_SRIOV_CheckDevice(self):
        cmd = "echo 4 > /sys/class/net/{}/device/sriov_numvfs".format(self.sut_conf["pf1"])
        stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, cmd)
        if stdout or stderr:
            assert 200 == 400
        sut2_ip = "192.168.10.11"
        self.cn_test_sut.ssh_exec_cmd(self.client2, "ifconfig {} {}\n".format(self.pkg_generator["pf1"], sut2_ip))
        manual_ip_cmd = "ifconfig {}{} 192.168.{}.{}"
        for i in range(4):
            vf = "v"+str(i)
            ip_part = str(int(sut2_ip.split(".")[3])+i)
            stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, manual_ip_cmd.format(self.sut_conf["pf1"], vf,sut2_ip.split(".")[2] ,ip_part))
            if stdout or stderr:
                assert 200 == 400
    
        ping_ipv4_cmd = "ping -c 5 {}"
        ping_ipv6_cmd = "ping6 -c 5 -I {}{} {}"
        for i in range(4):
            vf = "v"+str(i)
            stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, ping_ipv4_cmd.format(sut2_ip))
            if stdout.find("received, 0% packet loss") == -1:
>               assert 200 == 400
E               assert 200 == 400

npxtester/Tests/testNics/test_nics.py:178: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-04-06 14:03:45 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_gold_PI_Networking_SRIOV_CheckDevice_14_03_45/test_gold_PI_Networking_SRIOV_CheckDevice.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_gold_PI_Networking_SRIOV_CheckDevice_14_03_45
2022-04-06 14:03:45 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-04-06 14:03:45 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-06 14:03:45 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-06 14:03:46 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:03:46 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:03:46 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 14:03:46 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:03:46 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:03:46 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 14:03:46 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 14:03:46 - test_nics.py - [line:44] - root - INFO - --Start rmmod irdma --
2022-04-06 14:03:49 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:03:49 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:03:54 - test_nics.py - [line:46] - root - INFO - --Finish rmmod irdma --
2022-04-06 14:03:54 - test_nics.py - [line:47] - root - INFO - --Start rmmod ice --
2022-04-06 14:03:57 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:04:08 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:04:13 - test_nics.py - [line:49] - root - INFO - --Finish rmmod ice --
2022-04-06 14:04:13 - test_nics.py - [line:50] - root - INFO - --Start modprobe ice --
2022-04-06 14:04:16 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:04:20 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:04:25 - test_nics.py - [line:52] - root - INFO - --Finish modprobe ice --
2022-04-06 14:04:28 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:04:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:04:36 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2 | grep ^version:
2022-04-06 14:04:36 - sshInstance.py - [line:54] - root - INFO - version: 1.6.4

2022-04-06 14:04:41 - test_nics.py - [line:58] - root - INFO - Passed: driver version is what expected.
2022-04-06 14:04:41 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 14:04:44 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:04:44 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:04:49 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 14:04:49 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 14:04:52 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:05:04 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:05:09 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 14:05:09 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 14:05:12 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:05:17 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:05:22 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 14:05:25 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:05:25 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:05:33 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 14:05:33 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 14:05:41 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 14:05:41 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 2134 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:05:49 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-06 14:05:49 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 5376330685  bytes 8139741048664 (7.4 TiB)
        RX errors 1  dropped 0  overruns 0  frame 1
        TX packets 259833902  bytes 17262644324 (16.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-04-06 14:05:57 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-04-06 14:05:57 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:05 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11

2022-04-06 14:06:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:13 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v0 192.168.10.11
2022-04-06 14:06:13 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:21 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v1 192.168.10.12
2022-04-06 14:06:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:30 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v2 192.168.10.13
2022-04-06 14:06:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:38 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2v3 192.168.10.14
2022-04-06 14:06:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:06:46 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11
2022-04-06 14:07:00 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 96ms


------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:50 echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ifconfig ens787f2 192.168.10.11

INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ifconfig ens785f2v0 192.168.10.11
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ifconfig ens785f2v1 192.168.10.12
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ifconfig ens785f2v2 192.168.10.13
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ifconfig ens785f2v3 192.168.10.14
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ping -c 5 192.168.10.11
INFO     root:sshInstance.py:54 PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 96ms
______________ Test_Nics.test_PI_Networking_ConnectivityShutdown _______________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7f8179bbfd68>

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicSimple
    def test_PI_Networking_ConnectivityShutdown(self):
        self.bmc_conf = settings.__getattribute__("bmc_conf")
        sut1_ip = "192.168.10.10"
        sut2_ip = "192.168.10.11"
        self.cn_test_sut.ssh_exec_cmd(self.client2, "ifconfig {} {}".format(self.pkg_generator["pf1"], sut2_ip))
        self.cn_test_sut.ssh_exec_cmd(self.client, "ifconfig {} {}".format(self.sut_conf["pf1"], sut1_ip))
        rs = 0
        cmdip = "ping -c 5 {}\n".format(sut2_ip)
        stdout,stderr = self.cn_test_sut.ssh_exec_cmd(self.client, cmdip)
        if stdout.find("received, 0% packet loss") == -1:
            assert 200 == 400
    
        powers = power()
        output = powers.power_status(self.sut_conf, self.bmc_conf)
        logging.info(output)
        assert 200 == self.cn_test_sut.ping_sut(self.session, self.sut_conf["host"])
        output = powers.power_off(self.sut_conf, self.bmc_conf)
        logging.info(output)
        time.sleep(10)
        output = powers.power_status(self.sut_conf, self.bmc_conf)
>       if output.find("Power is off") > -1:
E       TypeError: a bytes-like object is required, not 'str'

npxtester/Tests/testNics/test_nics.py:317: TypeError
---------------------------- Captured stdout setup -----------------------------
2022-04-06 14:14:56 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_ConnectivityShutdown_14_14_56/test_PI_Networking_ConnectivityShutdown.log, case_logdir: /root/testconfig/testlogs/2022-04-06/test_PI_Networking_ConnectivityShutdown_14_14_56
2022-04-06 14:14:56 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_ConnectivityShutdown case ============================
2022-04-06 14:14:56 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-06 14:14:56 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-06 14:14:56 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:14:56 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:14:57 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-04-06 14:14:57 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-06 14:14:57 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-06 14:14:57 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-04-06 14:14:57 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-06 14:14:57 - test_nics.py - [line:44] - root - INFO - --Start rmmod irdma --
2022-04-06 14:15:00 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:15:00 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:15:05 - test_nics.py - [line:46] - root - INFO - --Finish rmmod irdma --
2022-04-06 14:15:05 - test_nics.py - [line:47] - root - INFO - --Start rmmod ice --
2022-04-06 14:15:08 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:15:19 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:15:24 - test_nics.py - [line:49] - root - INFO - --Finish rmmod ice --
2022-04-06 14:15:24 - test_nics.py - [line:50] - root - INFO - --Start modprobe ice --
2022-04-06 14:15:27 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:15:32 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:15:37 - test_nics.py - [line:52] - root - INFO - --Finish modprobe ice --
2022-04-06 14:15:40 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:15:40 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:15:48 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2 | grep ^version:
2022-04-06 14:15:48 - sshInstance.py - [line:54] - root - INFO - version: 1.6.4

2022-04-06 14:15:53 - test_nics.py - [line:58] - root - INFO - Passed: driver version is what expected.
2022-04-06 14:15:53 - sshInstance.py - [line:190] - root - INFO - start to rmmod irdma....
2022-04-06 14:15:56 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-06 14:15:56 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-04-06 14:16:01 - sshInstance.py - [line:193] - root - INFO - finished rmmod irdma....
2022-04-06 14:16:01 - sshInstance.py - [line:194] - root - INFO - start to rmmod ice....
2022-04-06 14:16:04 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-06 14:16:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:16:19 - sshInstance.py - [line:197] - root - INFO - finished rmmod ice....
2022-04-06 14:16:19 - sshInstance.py - [line:199] - root - INFO - start to modprobe ice....
2022-04-06 14:16:22 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-06 14:16:26 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:16:31 - sshInstance.py - [line:201] - root - INFO - finished modprobe ice....
2022-04-06 14:16:34 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 up
2022-04-06 14:16:35 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:16:43 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-04-06 14:16:43 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-06 14:16:51 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-04-06 14:16:51 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe72:ccca  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 2134 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-06 14:16:59 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-04-06 14:16:59 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::42a6:b7ff:fe82:eb6  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 5376331011  bytes 8139741098986 (7.4 TiB)
        RX errors 1  dropped 0  overruns 0  frame 1
        TX packets 259833965  bytes 17262656525 (16.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-04-06 14:17:07 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2 192.168.10.11
2022-04-06 14:17:07 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:17:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2 192.168.10.10
2022-04-06 14:17:15 - sshInstance.py - [line:54] - root - INFO - 
2022-04-06 14:17:23 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11

2022-04-06 14:17:27 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.482 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.192 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.183 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.185 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.183 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 92ms
rtt min/avg/max/mdev = 0.183/0.245/0.482/0.118 ms

2022-04-06 14:17:32 - power.py - [line:18] - root - INFO - checking the machine status
2022-04-06 14:17:32 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status
....
2022-04-06 14:17:52 - commonFunc.py - [line:25] - root - ERROR - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:17:52 - commonFunc.py - [line:26] - root - INFO - fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status

2022-04-06 14:17:52 - power.py - [line:22] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:17:52 - test_nics.py - [line:311] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:17:52 - sshInstance.py - [line:143] - root - INFO - ping sut, please wait ......
2022-04-06 14:18:52 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ping -w 5 10.239.182.209....
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.415 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.327 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.384 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.396 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.387 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - --- 10.239.182.209 ping statistics ---
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 5 packets transmitted, 5 received, 0% packet loss, time 78ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - rtt min/avg/max/mdev = 0.327/0.381/0.415/0.038 ms
2022-04-06 14:18:57 - commonFunc.py - [line:30] - root - INFO - 
2022-04-06 14:18:57 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: ping -w 5 10.239.182.209
2022-04-06 14:18:57 - power.py - [line:39] - root - INFO - starting to power off the machine....
2022-04-06 14:18:57 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power off
....
2022-04-06 14:19:17 - commonFunc.py - [line:25] - root - ERROR - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:19:17 - commonFunc.py - [line:26] - root - INFO - fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power off

2022-04-06 14:19:17 - power.py - [line:44] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:19:17 - test_nics.py - [line:314] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:19:27 - power.py - [line:18] - root - INFO - checking the machine status
2022-04-06 14:19:27 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status
....
2022-04-06 14:19:47 - commonFunc.py - [line:25] - root - ERROR - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
2022-04-06 14:19:47 - commonFunc.py - [line:26] - root - INFO - fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status

2022-04-06 14:19:47 - power.py - [line:22] - root - INFO - b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:50 ifconfig ens787f2 192.168.10.11
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ifconfig ens785f2 192.168.10.10
INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 ping -c 5 192.168.10.11

INFO     root:sshInstance.py:54 PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.482 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.192 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.183 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.185 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.183 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 92ms
rtt min/avg/max/mdev = 0.183/0.245/0.482/0.118 ms

INFO     root:power.py:18 checking the machine status
INFO     root:commonFunc.py:16 starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status
....
ERROR    root:commonFunc.py:25 b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
INFO     root:commonFunc.py:26 fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status

INFO     root:power.py:22 b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
INFO     root:test_nics.py:311 b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
INFO     root:sshInstance.py:143 ping sut, please wait ......
INFO     root:commonFunc.py:16 starting to execute the cmd: ping -w 5 10.239.182.209....
INFO     root:commonFunc.py:30 PING 10.239.182.209 (10.239.182.209) 56(84) bytes of data.
INFO     root:commonFunc.py:30 64 bytes from 10.239.182.209: icmp_seq=1 ttl=61 time=0.415 ms
INFO     root:commonFunc.py:30 64 bytes from 10.239.182.209: icmp_seq=2 ttl=61 time=0.327 ms
INFO     root:commonFunc.py:30 64 bytes from 10.239.182.209: icmp_seq=3 ttl=61 time=0.384 ms
INFO     root:commonFunc.py:30 64 bytes from 10.239.182.209: icmp_seq=4 ttl=61 time=0.396 ms
INFO     root:commonFunc.py:30 64 bytes from 10.239.182.209: icmp_seq=5 ttl=61 time=0.387 ms
INFO     root:commonFunc.py:30 
INFO     root:commonFunc.py:30 --- 10.239.182.209 ping statistics ---
INFO     root:commonFunc.py:30 5 packets transmitted, 5 received, 0% packet loss, time 78ms
INFO     root:commonFunc.py:30 rtt min/avg/max/mdev = 0.327/0.381/0.415/0.038 ms
INFO     root:commonFunc.py:30 
INFO     root:commonFunc.py:31 finished exeucting the cmd: ping -w 5 10.239.182.209
INFO     root:power.py:39 starting to power off the machine....
INFO     root:commonFunc.py:16 starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power off
....
ERROR    root:commonFunc.py:25 b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
INFO     root:commonFunc.py:26 fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power off

INFO     root:power.py:44 b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
INFO     root:test_nics.py:314 b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
INFO     root:power.py:18 checking the machine status
INFO     root:commonFunc.py:16 starting to execute the cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status
....
ERROR    root:commonFunc.py:25 b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
INFO     root:commonFunc.py:26 fail to executing cmd: ipmitool -I lanplus -H 10.239.182.128 -U root -P Intel@123 power status

INFO     root:power.py:22 b'Error: Unable to establish IPMI v2 / RMCP+ session\n'
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:88
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_iperf_client_4hour.py:88: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:137
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_iperf_client_4hour.py:137: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:70
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:109
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:109: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:565
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:565: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:691
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:691: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:931
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:931: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_network_sriov_stress.py:1067
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:1067: PytestUnknownMarkWarning: Unknown pytest.mark.nicIperfTcpSUTGuestStress - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicIperfTcpSUTGuestStress

npxtester/Tests/testNics/test_network_sriov_stress.py:1068
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:1068: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:100
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:100: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:126
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:126: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:156
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:156: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:227
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:227: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:253
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:253: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:296
  /root/.jenkins/workspace/cyp-test-nic-simple/npxtester/Tests/testNics/test_nics.py:296: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_simple_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_nics.py::Test_Nics::test_gold_PI_Networking_SRIOV_CheckDevice
FAILED npxtester/Tests/testNics/test_nics.py::Test_Nics::test_PI_Networking_ConnectivityShutdown
===== 2 failed, 6 passed, 11 deselected, 17 warnings in 3605.64s (1:00:05) =====
[8mha:////4JadWPtzQEFx9CzixTlssp2D6uuorSv3wnTa6h1wuGrmAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiISEKRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g3QKkBhvgAAAA==[0m[Pipeline] }
[8mha:////4Goa9rseL6gCK8+j51lIjOVJAeE64BF71YmRtb4KtKxFAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiIQokRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g2TqBHnvgAAAA==[0m[Pipeline] // stage
[8mha:////4AK444efjkykafC1HGbgxn6nPSQkL/HNauaXETS7R91oAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIRqEqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A+OvzUfBAAAA[0m[Pipeline] stage
[8mha:////4EqpMgzslAWPDRl1bp4feAKRfPoiBNazp8uDBURuqJGsAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycogUwYRQJ9aoCycITQhJo/9LkpJOnIircQcClZjwYNmWrPd8QRU8NOQ1swp7g6EzbHCjzokl8v3FUWKWzqwjDOQUa1VqSarjXFuKCmYVJSw4LBV2joJBHWHFrbiL2gnU9Sn6vB04lEbe4AEFz+QofPyWycP6OspA+OP8BcA0RCi3+2y7zedZvQH4j6CMwgAAAA==[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4M0P44+7KKMsBaEAgOPFTC6kJ9gOLfRk2xH1/27GZQUTAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICokRUaS03vMDExjix7oztkFS8iK/xBwKRqNhitbPNPF+wTBGOHC22hjpHqXEYfG+nhQPH7uJ5wJbP2DAl9galGSRrU88oORuYU5SwELAy1HhOjmyGtWjVXVVeka1OOU7fQUDp9A0eUIjJnFXMXxgjbK69Tkw/z18BjCFkKPe7T23ftwcfeL4AAAA=[0m[Pipeline] }
[8mha:////4ME5TlbHmzr5qdpFH/mkGWKP7XmPx2rIKtfLHFMqug00AAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIihQohqrRWGl5gYmOcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThwM9poGS7Gz6N1o8sKJw3B1PGHPF+yYIjuNrZ5aVrpZsOWkYUlRwkrARlPnOFoyCbailw9ZOUmmOqeQv6OA0qo7PKEQ2ZxkSF+YA+xuo4pMP89fAczeJyj3da768AH8/EyevgAAAA==[0m[Pipeline] // stage
[8mha:////4Fe3eqQpZrcpnjrK1jN1d/MbMZ7ufuA8IOyekGcoBhh7AAAAoh+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIU2DlWthkaTxAhxkBmF5NFqDyRV/MOMjJj5a/+e817vbFOEUeOTrWWOk+p9qoPg5ufGjl218CjavmiaqbEwarKjhU39rRgxWKxLMux0thYqgMnT06w1a15mCIYcsVZ4uwOGrlv7ngi03NZTJQvTBG729Akpl/nbwBT3wvyshRk+w9e8C3YvQAAAA==[0m[Pipeline] }
[8mha:////4Fl8XDDe7BXdXsXj7uDbwTY/cDAcq+nOEdlmagh5XH3DAAAAoh+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIU2DlWthkaTxAhxkBmF5NFqDyRV/MOMjJj5a/+e817vbFOEUeOTrWWOk+p9qoPg5ufGjl218CjavmiaqbEwarKjhU39rRgxWKxLMux0thYqgMnT06w1a15mCIYcsVZ4uwOGrlv7ngi03NZTJQvTBG729Akpl/nbwBT3wvyci/Iyg/tuWn0vQAAAA==[0m[Pipeline] // node
[8mha:////4Oc/DLR66YI1esGEMsMY02BciEZxcpD10WBUR6yLP96pAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRQFSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLcXZNsPy6AOvr0AAAA=[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
