Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"1.6.4"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","connect_switch_sut_pf":"ens2f0","pf1":"ens2f0","pf1_ipv6":"fe80::b696:91ff:fe9c:f7a4","os":"RHEL"},"dhcp":{"ipv4":"192.168.10.11","ipv6":"fe80::b696:91ff:fea5:9b45"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 16 items / 15 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-02 02:39:14 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
2022-03-02 02:39:14 - test_network_sriov_stress.py - [line:31] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-02 02:39:14 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-02 02:39:14 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-02 02:39:15 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-02 02:39:15 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-02 02:39:15 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-02 02:39:15 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-02 02:39:15 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-02 02:39:18 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-02 02:39:22 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:39:30 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-02 02:39:35 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:39:43 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-02 02:39:43 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-02 02:39:48 - test_network_sriov_stress.py - [line:383] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-02 02:39:51 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-02 02:39:52 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-02 02:39:57 - test_network_sriov_stress.py - [line:103] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-02 02:39:57 - test_network_sriov_stress.py - [line:391] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-02 02:39:57 - test_network_sriov_stress.py - [line:394] - root - INFO - pf_id_key: 4b
2022-03-02 02:40:03 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar  2 01:52:11 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-02 02:40:06 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-02 02:40:09 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 02:40:09 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:40:14 - test_network_sriov_stress.py - [line:117] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-02 02:40:17 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-02 02:40:17 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-02 02:40:22 - test_network_sriov_stress.py - [line:131] - root - INFO - Succssfully Gotten vf_id list:

2022-03-02 02:40:25 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-02 02:40:25 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:40:33 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-02 02:40:34 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:40:39 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 02:40:42 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-02 02:40:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:40:48 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 02:40:48 - test_network_sriov_stress.py - [line:416] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 02:40:51 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 02:40:51 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-02 02:40:56 - test_network_sriov_stress.py - [line:427] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-02 02:40:59 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-02 02:40:59 - sshInstance.py - [line:50] - root - INFO - no

2022-03-02 02:41:04 - test_network_sriov_stress.py - [line:191] - root - INFO - Default network is active? no

2022-03-02 02:41:04 - test_network_sriov_stress.py - [line:200] - root - INFO - virsh net-start default
2022-03-02 02:41:07 - sshInstance.py - [line:46] - root - INFO - virsh net-start default
2022-03-02 02:41:08 - sshInstance.py - [line:50] - root - INFO - Network default started


2022-03-02 02:41:13 - test_network_sriov_stress.py - [line:204] - root - INFO - Successfully started network default.
2022-03-02 02:41:17 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-02 02:41:18 - sshInstance.py - [line:71] - root - INFO - 
** (process:56067): [1;33mWARNING[0m **: [34m02:49:04.812[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 02:41:20 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 02:41:23 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest1
2022-03-02 02:41:27 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:56146): [1;33mWARNING[0m **: [34m02:49:14.584[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
2022-03-02 02:41:28 - sshInstance.py - [line:71] - root - INFO - WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 02:41:30 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 02:41:33 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest2
2022-03-02 02:41:36 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 02:41:36 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:41:41 - test_network_sriov_stress.py - [line:243] - root - ERROR - not found IP of VMtest1
2022-03-02 02:42:44 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 02:42:44 - sshInstance.py - [line:50] - root - INFO - 192.168.122.134/24

2022-03-02 02:42:49 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest1 IP: 192.168.122.134/24

2022-03-02 02:42:52 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-02 02:42:52 - sshInstance.py - [line:50] - root - INFO - 192.168.122.2/24

2022-03-02 02:42:57 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest2 IP: 192.168.122.2/24

2022-03-02 02:42:57 - test_network_sriov_stress.py - [line:444] - root - INFO - ip of VM1: 192.168.122.134
2022-03-02 02:42:57 - test_network_sriov_stress.py - [line:445] - root - INFO - ip of VM1: 192.168.122.2
2022-03-02 02:43:01 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.322 ms
2022-03-02 02:43:02 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.467 ms
2022-03-02 02:43:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.470 ms
2022-03-02 02:43:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.467 ms
2022-03-02 02:43:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.463 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4107ms
rtt min/avg/max/mdev = 0.322/0.437/0.470/0.063 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:43:14 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
The authenticity of host '192.168.122.134 (192.168.122.134)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-02 02:43:23 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.134' (ECDSA) to the list of known hosts.
root@192.168.122.134's password: 
2022-03-02 02:43:32 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 01:51:17 PM EST
  System load:  0.0                Processes:             138
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Feb 28 17:56:03 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 02:43:41 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 02:43:47 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 02:43:53 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 02:43:58 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 02:44:04 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-02 02:44:07 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 02:44:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 02:44:23 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-02 02:44:32 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 02:44:41 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 02:44:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 02:44:59 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 02:45:06 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.2
PING 192.168.122.2 (192.168.122.2) 56(84) bytes of data.
64 bytes from 192.168.122.2: icmp_seq=1 ttl=64 time=0.374 ms
2022-03-02 02:45:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=2 ttl=64 time=0.278 ms
2022-03-02 02:45:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=3 ttl=64 time=0.345 ms
2022-03-02 02:45:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=4 ttl=64 time=0.465 ms
2022-03-02 02:45:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=5 ttl=64 time=0.496 ms

--- 192.168.122.2 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.278/0.391/0.496/0.082 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:45:19 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.2
root@192.168.122.2's password: 
2022-03-02 02:45:28 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 01:53:12 PM EST
  System load:  0.0                Processes:             136
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.2
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Feb 28 17:56:58 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 02:45:37 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 02:45:43 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 02:45:49 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 02:45:54 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 02:46:00 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-02 02:46:03 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 02:46:09 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 02:46:19 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-02 02:46:28 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 02:46:37 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 02:46:46 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 02:46:55 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.2 closed.
[root@WW25ICX2 ~]# 
2022-03-02 02:46:58 - test_network_sriov_stress.py - [line:465] - root - INFO - Ping two vms IP from SUT:
2022-03-02 02:47:02 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.526 ms
2022-03-02 02:47:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.348 ms
2022-03-02 02:47:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.215 ms
2022-03-02 02:47:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.191 ms
2022-03-02 02:47:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.225 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4117ms
rtt min/avg/max/mdev = 0.191/0.301/0.526/0.124 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:47:13 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.427 ms
2022-03-02 02:47:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.252 ms
2022-03-02 02:47:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.143 ms
2022-03-02 02:47:16 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.233 ms
2022-03-02 02:47:17 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.221 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4111ms
rtt min/avg/max/mdev = 0.143/0.255/0.427/0.094 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:47:20 - test_network_sriov_stress.py - [line:473] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 02:47:24 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.447 ms
2022-03-02 02:47:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.513 ms
2022-03-02 02:47:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.506 ms
2022-03-02 02:47:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.424 ms
2022-03-02 02:47:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.500 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4104ms
rtt min/avg/max/mdev = 0.424/0.478/0.513/0.035 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:47:37 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 02:47:46 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 01:55:31 PM EST
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 13:51:17 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 02:47:53 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.608 ms
2022-03-02 02:47:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.336 ms
2022-03-02 02:47:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.312 ms
2022-03-02 02:47:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.264 ms
2022-03-02 02:47:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.350 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.264/0.374/0.608/0.120 ms
root@localhost:~# 
2022-03-02 02:48:37 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 02:48:40 - test_network_sriov_stress.py - [line:481] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 02:48:44 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.436 ms
2022-03-02 02:48:45 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.248 ms
2022-03-02 02:48:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.169 ms
2022-03-02 02:48:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.213 ms
2022-03-02 02:48:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.185 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4077ms
rtt min/avg/max/mdev = 0.169/0.250/0.436/0.097 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:48:54 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 02:48:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:49:01 - test_network_sriov_stress.py - [line:257] - root - INFO - Successfully removed VFs from PF.
2022-03-02 02:49:04 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-02 02:49:05 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-02 02:49:10 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-02 02:49:13 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-02 02:49:13 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-02 02:49:18 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest1
2022-03-02 02:49:21 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-02 02:49:21 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-02 02:49:26 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-02 02:49:29 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-02 02:49:29 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-02 02:49:34 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest2
2022-03-02 02:49:34 - test_network_sriov_stress.py - [line:383] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2022-03-02 02:49:37 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-02 02:49:38 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-02 02:49:43 - test_network_sriov_stress.py - [line:103] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-02 02:49:43 - test_network_sriov_stress.py - [line:391] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-02 02:49:43 - test_network_sriov_stress.py - [line:394] - root - INFO - pf_id_key: 4b
2022-03-02 02:49:49 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-02 02:49:52 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-02 02:49:55 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 02:49:55 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:50:00 - test_network_sriov_stress.py - [line:117] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-02 02:50:03 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-02 02:50:03 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-02 02:50:08 - test_network_sriov_stress.py - [line:131] - root - INFO - Succssfully Gotten vf_id list:

2022-03-02 02:50:11 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-02 02:50:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:50:19 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-02 02:50:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:50:25 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 02:50:28 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-02 02:50:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:50:34 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 02:50:34 - test_network_sriov_stress.py - [line:416] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 02:50:37 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 02:50:37 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-02 02:50:42 - test_network_sriov_stress.py - [line:427] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-02 02:50:45 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-02 02:50:45 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-02 02:50:50 - test_network_sriov_stress.py - [line:191] - root - INFO - Default network is active? yes

2022-03-02 02:50:54 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-02 02:50:55 - sshInstance.py - [line:71] - root - INFO - 
** (process:57752): [1;33mWARNING[0m **: [34m02:58:42.071[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 02:50:58 - test_network_sriov_stress.py - [line:223] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:57752): [1;33mWARNING[0m **: [34m02:58:42.071[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 02:50:58 - test_network_sriov_stress.py - [line:224] - root - ERROR - Failed to create a VM: 
2022-03-02 02:51:02 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:57757): [1;33mWARNING[0m **: [34m02:58:49.964[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 02:51:04 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 02:51:07 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest1
2022-03-02 02:51:11 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:57804): [1;33mWARNING[0m **: [34m02:58:58.926[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 02:51:14 - test_network_sriov_stress.py - [line:223] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:57804): [1;33mWARNING[0m **: [34m02:58:58.926[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 02:51:14 - test_network_sriov_stress.py - [line:224] - root - ERROR - Failed to create a VM: 
2022-03-02 02:51:18 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:57811): [1;33mWARNING[0m **: [34m02:59:05.889[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 02:51:20 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 02:51:23 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest2
2022-03-02 02:51:26 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 02:51:26 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:51:31 - test_network_sriov_stress.py - [line:243] - root - ERROR - not found IP of VMtest1
2022-03-02 02:52:34 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 02:52:34 - sshInstance.py - [line:50] - root - INFO - 192.168.122.134/24

2022-03-02 02:52:39 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest1 IP: 192.168.122.134/24

2022-03-02 02:52:42 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-02 02:52:42 - sshInstance.py - [line:50] - root - INFO - 192.168.122.2/24

2022-03-02 02:52:47 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest2 IP: 192.168.122.2/24

2022-03-02 02:52:47 - test_network_sriov_stress.py - [line:444] - root - INFO - ip of VM1: 192.168.122.134
2022-03-02 02:52:47 - test_network_sriov_stress.py - [line:445] - root - INFO - ip of VM1: 192.168.122.2
2022-03-02 02:52:51 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.449 ms
2022-03-02 02:52:52 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.442 ms
2022-03-02 02:52:53 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.389 ms
2022-03-02 02:52:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.423 ms
2022-03-02 02:52:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.469 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4113ms
rtt min/avg/max/mdev = 0.389/0.434/0.469/0.032 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:53:04 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 02:53:13 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:00:58 PM EST
  System load:  0.38               Processes:             145
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 13:55:31 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 02:53:22 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 02:53:28 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 02:53:34 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 02:53:39 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 02:53:45 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-02 02:53:48 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 02:53:54 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 02:54:04 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-02 02:54:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 02:54:22 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 02:54:31 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 02:54:40 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 02:54:47 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.2
PING 192.168.122.2 (192.168.122.2) 56(84) bytes of data.
64 bytes from 192.168.122.2: icmp_seq=1 ttl=64 time=0.503 ms
2022-03-02 02:54:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=2 ttl=64 time=0.385 ms
2022-03-02 02:54:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=3 ttl=64 time=0.525 ms
2022-03-02 02:54:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=4 ttl=64 time=0.506 ms
2022-03-02 02:54:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=5 ttl=64 time=0.207 ms

--- 192.168.122.2 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4079ms
rtt min/avg/max/mdev = 0.207/0.425/0.525/0.120 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:55:00 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.2
root@192.168.122.2's password: 
2022-03-02 02:55:10 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:02:54 PM EST
  System load:  0.0                Processes:             140
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.2
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Mar  1 13:53:13 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 02:55:19 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 02:55:25 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 02:55:31 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 02:55:36 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 02:55:42 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-02 02:55:45 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 02:55:51 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 02:56:01 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-02 02:56:10 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 02:56:19 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 02:56:28 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 02:56:37 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.2 closed.
[root@WW25ICX2 ~]# 
2022-03-02 02:56:40 - test_network_sriov_stress.py - [line:465] - root - INFO - Ping two vms IP from SUT:
2022-03-02 02:56:44 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.379 ms
2022-03-02 02:56:45 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.265 ms
2022-03-02 02:56:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.269 ms
2022-03-02 02:56:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.299 ms
2022-03-02 02:56:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.225 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4107ms
rtt min/avg/max/mdev = 0.225/0.287/0.379/0.053 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:56:55 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.444 ms
2022-03-02 02:56:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.303 ms
2022-03-02 02:56:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.164 ms
2022-03-02 02:56:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.228 ms
2022-03-02 02:56:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.193 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4101ms
rtt min/avg/max/mdev = 0.164/0.266/0.444/0.101 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:57:02 - test_network_sriov_stress.py - [line:473] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 02:57:06 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.420 ms
2022-03-02 02:57:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.475 ms
2022-03-02 02:57:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.282 ms
2022-03-02 02:57:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.387 ms
2022-03-02 02:57:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.282 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4096ms
rtt min/avg/max/mdev = 0.282/0.369/0.475/0.077 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:57:19 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 02:57:28 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:05:12 PM EST
  System load:  0.01               Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 14:00:59 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 02:57:35 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=2.11 ms
2022-03-02 02:57:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.225 ms
2022-03-02 02:57:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.131 ms
2022-03-02 02:57:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.231 ms
2022-03-02 02:57:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.232 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4054ms
rtt min/avg/max/mdev = 0.131/0.584/2.105/0.761 ms
root@localhost:~# 
2022-03-02 02:58:19 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 02:58:22 - test_network_sriov_stress.py - [line:481] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 02:58:26 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.264 ms
2022-03-02 02:58:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.178 ms
2022-03-02 02:58:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.106 ms
2022-03-02 02:58:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.204 ms
2022-03-02 02:58:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.264 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4134ms
rtt min/avg/max/mdev = 0.106/0.203/0.264/0.059 ms
[root@WW25ICX2 ~]# 
2022-03-02 02:58:36 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 02:58:38 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:58:43 - test_network_sriov_stress.py - [line:257] - root - INFO - Successfully removed VFs from PF.
2022-03-02 02:58:46 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-02 02:58:46 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-02 02:58:51 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-02 02:58:54 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-02 02:58:54 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-02 02:58:59 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest1
2022-03-02 02:59:02 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-02 02:59:02 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-02 02:59:07 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-02 02:59:10 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-02 02:59:11 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-02 02:59:16 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest2
2022-03-02 02:59:16 - test_network_sriov_stress.py - [line:383] - root - INFO - 

********************************************************Stress Disable and Enable for 3 time when VF is Assigned VM guest.*************************************************************


2022-03-02 02:59:19 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-02 02:59:19 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-02 02:59:24 - test_network_sriov_stress.py - [line:103] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-02 02:59:24 - test_network_sriov_stress.py - [line:391] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-02 02:59:24 - test_network_sriov_stress.py - [line:394] - root - INFO - pf_id_key: 4b
2022-03-02 02:59:30 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-02 02:59:33 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-02 02:59:36 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 02:59:36 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 02:59:41 - test_network_sriov_stress.py - [line:117] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-02 02:59:44 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-02 02:59:44 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-02 02:59:49 - test_network_sriov_stress.py - [line:131] - root - INFO - Succssfully Gotten vf_id list:

2022-03-02 02:59:52 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-02 02:59:53 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:00:01 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-02 03:00:01 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:00:06 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 03:00:09 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-02 03:00:10 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:00:15 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 03:00:15 - test_network_sriov_stress.py - [line:416] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 03:00:18 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 03:00:18 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-02 03:00:23 - test_network_sriov_stress.py - [line:427] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-02 03:00:26 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-02 03:00:26 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-02 03:00:31 - test_network_sriov_stress.py - [line:191] - root - INFO - Default network is active? yes

2022-03-02 03:00:35 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:58879): [1;33mWARNING[0m **: [34m03:08:23.044[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:00:38 - test_network_sriov_stress.py - [line:223] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:58879): [1;33mWARNING[0m **: [34m03:08:23.044[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:00:38 - test_network_sriov_stress.py - [line:224] - root - ERROR - Failed to create a VM: 
2022-03-02 03:00:42 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:58887): [1;33mWARNING[0m **: [34m03:08:30.107[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 03:00:45 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 03:00:48 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest1
2022-03-02 03:00:52 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:58933): [1;33mWARNING[0m **: [34m03:08:40.010[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:00:55 - test_network_sriov_stress.py - [line:223] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:58933): [1;33mWARNING[0m **: [34m03:08:40.010[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:00:55 - test_network_sriov_stress.py - [line:224] - root - ERROR - Failed to create a VM: 
2022-03-02 03:00:59 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:58941): [1;33mWARNING[0m **: [34m03:08:47.021[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 03:01:01 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 03:01:04 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest2
2022-03-02 03:01:07 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:01:07 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:01:12 - test_network_sriov_stress.py - [line:243] - root - ERROR - not found IP of VMtest1
2022-03-02 03:02:15 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:02:15 - sshInstance.py - [line:50] - root - INFO - 192.168.122.134/24

2022-03-02 03:02:20 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest1 IP: 192.168.122.134/24

2022-03-02 03:02:23 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:02:24 - sshInstance.py - [line:50] - root - INFO - 192.168.122.2/24

2022-03-02 03:02:29 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest2 IP: 192.168.122.2/24

2022-03-02 03:02:29 - test_network_sriov_stress.py - [line:444] - root - INFO - ip of VM1: 192.168.122.134
2022-03-02 03:02:29 - test_network_sriov_stress.py - [line:445] - root - INFO - ip of VM1: 192.168.122.2
2022-03-02 03:02:33 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.338 ms
2022-03-02 03:02:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.425 ms
2022-03-02 03:02:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.471 ms
2022-03-02 03:02:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.467 ms
2022-03-02 03:02:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.463 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4134ms
rtt min/avg/max/mdev = 0.338/0.432/0.471/0.056 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:02:46 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 03:02:55 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:10:39 PM EST
  System load:  0.0                Processes:             141
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 14:05:13 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:03:04 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 03:03:10 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 03:03:16 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 03:03:21 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 03:03:27 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-02 03:03:30 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 03:03:36 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 03:03:46 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-02 03:03:55 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 03:04:04 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 03:04:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 346 (346.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 03:04:22 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:04:29 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.2
PING 192.168.122.2 (192.168.122.2) 56(84) bytes of data.
64 bytes from 192.168.122.2: icmp_seq=1 ttl=64 time=0.118 ms
2022-03-02 03:04:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=2 ttl=64 time=0.361 ms
2022-03-02 03:04:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=3 ttl=64 time=0.176 ms
2022-03-02 03:04:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=4 ttl=64 time=0.271 ms
2022-03-02 03:04:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=5 ttl=64 time=0.235 ms

--- 192.168.122.2 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.118/0.232/0.361/0.083 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:04:42 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.2
root@192.168.122.2's password: 
2022-03-02 03:04:51 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:12:35 PM EST
  System load:  0.0                Processes:             151
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.2
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Mar  1 14:02:55 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:05:00 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 03:05:06 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 03:05:12 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 03:05:17 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 03:05:23 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-02 03:05:26 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 03:05:32 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 03:05:42 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-02 03:05:51 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 03:06:00 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 03:06:09 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 03:06:18 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.2 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:06:21 - test_network_sriov_stress.py - [line:465] - root - INFO - Ping two vms IP from SUT:
2022-03-02 03:06:25 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.362 ms
2022-03-02 03:06:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.061 ms
2022-03-02 03:06:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.123 ms
2022-03-02 03:06:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.056 ms
2022-03-02 03:06:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.126 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4126ms
rtt min/avg/max/mdev = 0.056/0.145/0.362/0.112 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:06:36 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.368 ms
2022-03-02 03:06:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.306 ms
2022-03-02 03:06:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.194 ms
2022-03-02 03:06:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.227 ms
2022-03-02 03:06:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.121 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4120ms
rtt min/avg/max/mdev = 0.121/0.243/0.368/0.086 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:06:43 - test_network_sriov_stress.py - [line:473] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 03:06:47 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.359 ms
2022-03-02 03:06:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.464 ms
2022-03-02 03:06:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.466 ms
2022-03-02 03:06:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.466 ms
2022-03-02 03:06:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.462 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4115ms
rtt min/avg/max/mdev = 0.359/0.443/0.466/0.046 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:07:00 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 03:07:09 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:14:53 PM EST
  System load:  0.0                Processes:             128
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 14:10:39 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:07:16 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.254 ms
2022-03-02 03:07:17 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.130 ms
2022-03-02 03:07:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.266 ms
2022-03-02 03:07:19 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.246 ms
2022-03-02 03:07:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.140 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4084ms
rtt min/avg/max/mdev = 0.130/0.207/0.266/0.059 ms
root@localhost:~# 
2022-03-02 03:08:00 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:08:03 - test_network_sriov_stress.py - [line:481] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 03:08:07 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.228 ms
2022-03-02 03:08:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.246 ms
2022-03-02 03:08:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.265 ms
2022-03-02 03:08:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.261 ms
2022-03-02 03:08:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.250 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4089ms
rtt min/avg/max/mdev = 0.228/0.250/0.265/0.013 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:08:17 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 03:08:19 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:08:24 - test_network_sriov_stress.py - [line:257] - root - INFO - Successfully removed VFs from PF.
2022-03-02 03:08:27 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-02 03:08:27 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-02 03:08:32 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-02 03:08:35 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-02 03:08:35 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-02 03:08:40 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest1
2022-03-02 03:08:43 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-02 03:08:44 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-02 03:08:49 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-02 03:08:52 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-02 03:08:52 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-02 03:08:57 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest2
2022-03-02 03:08:57 - test_network_sriov_stress.py - [line:383] - root - INFO - 

********************************************************Stress Disable and Enable for 4 time when VF is Assigned VM guest.*************************************************************


2022-03-02 03:09:00 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-02 03:09:00 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-02 03:09:05 - test_network_sriov_stress.py - [line:103] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-02 03:09:05 - test_network_sriov_stress.py - [line:391] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-02 03:09:05 - test_network_sriov_stress.py - [line:394] - root - INFO - pf_id_key: 4b
2022-03-02 03:09:11 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-02 03:09:15 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-02 03:09:18 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 03:09:18 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:09:23 - test_network_sriov_stress.py - [line:117] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-02 03:09:26 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-02 03:09:26 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-02 03:09:31 - test_network_sriov_stress.py - [line:131] - root - INFO - Succssfully Gotten vf_id list:

2022-03-02 03:09:34 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-02 03:09:34 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:09:42 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-02 03:09:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:09:48 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 03:09:51 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-02 03:09:52 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:09:57 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 03:09:57 - test_network_sriov_stress.py - [line:416] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 03:10:00 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 03:10:00 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-02 03:10:05 - test_network_sriov_stress.py - [line:427] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-02 03:10:08 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-02 03:10:08 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-02 03:10:13 - test_network_sriov_stress.py - [line:191] - root - INFO - Default network is active? yes

2022-03-02 03:10:17 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:59969): [1;33mWARNING[0m **: [34m03:18:04.556[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:10:20 - test_network_sriov_stress.py - [line:223] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:59969): [1;33mWARNING[0m **: [34m03:18:04.556[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:10:20 - test_network_sriov_stress.py - [line:224] - root - ERROR - Failed to create a VM: 
2022-03-02 03:10:24 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:59985): [1;33mWARNING[0m **: [34m03:18:11.648[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 03:10:26 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 03:10:29 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest1
2022-03-02 03:10:33 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:60032): [1;33mWARNING[0m **: [34m03:18:20.450[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:10:36 - test_network_sriov_stress.py - [line:223] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:60032): [1;33mWARNING[0m **: [34m03:18:20.450[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:10:36 - test_network_sriov_stress.py - [line:224] - root - ERROR - Failed to create a VM: 
2022-03-02 03:10:40 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:60037): [1;33mWARNING[0m **: [34m03:18:27.652[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 03:10:43 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 03:10:46 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest2
2022-03-02 03:10:49 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:10:49 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:10:54 - test_network_sriov_stress.py - [line:243] - root - ERROR - not found IP of VMtest1
2022-03-02 03:11:57 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:11:57 - sshInstance.py - [line:50] - root - INFO - 192.168.122.134/24

2022-03-02 03:12:02 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest1 IP: 192.168.122.134/24

2022-03-02 03:12:05 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:12:05 - sshInstance.py - [line:50] - root - INFO - 192.168.122.2/24

2022-03-02 03:12:10 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest2 IP: 192.168.122.2/24

2022-03-02 03:12:10 - test_network_sriov_stress.py - [line:444] - root - INFO - ip of VM1: 192.168.122.134
2022-03-02 03:12:10 - test_network_sriov_stress.py - [line:445] - root - INFO - ip of VM1: 192.168.122.2
2022-03-02 03:12:14 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.213 ms
2022-03-02 03:12:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.476 ms
2022-03-02 03:12:16 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.469 ms
2022-03-02 03:12:17 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.397 ms
2022-03-02 03:12:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.466 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4133ms
rtt min/avg/max/mdev = 0.213/0.404/0.476/0.100 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:12:27 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 03:12:36 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:20:20 PM EST
  System load:  0.12               Processes:             137
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 14:14:54 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:12:45 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 03:12:51 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 03:12:57 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 03:13:02 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 03:13:08 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-02 03:13:11 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 03:13:17 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 03:13:27 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-02 03:13:36 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 03:13:45 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 03:13:54 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1038 (1.0 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 03:14:03 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:14:10 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.2
PING 192.168.122.2 (192.168.122.2) 56(84) bytes of data.
64 bytes from 192.168.122.2: icmp_seq=1 ttl=64 time=0.417 ms
2022-03-02 03:14:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=2 ttl=64 time=0.313 ms
2022-03-02 03:14:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=3 ttl=64 time=0.472 ms
2022-03-02 03:14:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=4 ttl=64 time=0.476 ms
2022-03-02 03:14:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=5 ttl=64 time=0.351 ms

--- 192.168.122.2 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4096ms
rtt min/avg/max/mdev = 0.313/0.405/0.476/0.069 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:14:23 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.2
root@192.168.122.2's password: 
2022-03-02 03:14:32 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:22:16 PM EST
  System load:  0.03               Processes:             140
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.2
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Mar  1 14:12:36 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:14:41 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 03:14:47 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 03:14:53 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 03:14:58 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 03:15:04 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-02 03:15:07 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 03:15:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 03:15:23 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-02 03:15:32 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 03:15:41 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 03:15:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 03:15:59 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.2 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:16:02 - test_network_sriov_stress.py - [line:465] - root - INFO - Ping two vms IP from SUT:
2022-03-02 03:16:06 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.490 ms
2022-03-02 03:16:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.160 ms
2022-03-02 03:16:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.245 ms
2022-03-02 03:16:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.099 ms
2022-03-02 03:16:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.139 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4126ms
rtt min/avg/max/mdev = 0.099/0.226/0.490/0.141 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:16:17 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.423 ms
2022-03-02 03:16:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.238 ms
2022-03-02 03:16:19 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.308 ms
2022-03-02 03:16:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.217 ms
2022-03-02 03:16:21 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.305 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4120ms
rtt min/avg/max/mdev = 0.217/0.298/0.423/0.072 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:16:24 - test_network_sriov_stress.py - [line:473] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 03:16:28 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.346 ms
2022-03-02 03:16:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.459 ms
2022-03-02 03:16:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.358 ms
2022-03-02 03:16:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.319 ms
2022-03-02 03:16:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.468 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4114ms
rtt min/avg/max/mdev = 0.319/0.390/0.468/0.061 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:16:41 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 03:16:50 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:24:34 PM EST
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 14:20:20 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:16:57 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.263 ms
2022-03-02 03:16:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.368 ms
2022-03-02 03:16:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.186 ms
2022-03-02 03:17:00 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.205 ms
2022-03-02 03:17:01 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.208 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4100ms
rtt min/avg/max/mdev = 0.186/0.246/0.368/0.066 ms
root@localhost:~# 
2022-03-02 03:17:41 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:17:44 - test_network_sriov_stress.py - [line:481] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 03:17:48 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.288 ms
2022-03-02 03:17:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.205 ms
2022-03-02 03:17:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.235 ms
2022-03-02 03:17:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.274 ms
2022-03-02 03:17:52 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.263 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4086ms
rtt min/avg/max/mdev = 0.205/0.253/0.288/0.029 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:17:58 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 03:18:01 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:18:06 - test_network_sriov_stress.py - [line:257] - root - INFO - Successfully removed VFs from PF.
2022-03-02 03:18:09 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-02 03:18:09 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-02 03:18:14 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-02 03:18:17 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-02 03:18:17 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-02 03:18:22 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest1
2022-03-02 03:18:25 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-02 03:18:25 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-02 03:18:30 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-02 03:18:33 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-02 03:18:33 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-02 03:18:38 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest2
2022-03-02 03:18:38 - test_network_sriov_stress.py - [line:383] - root - INFO - 

********************************************************Stress Disable and Enable for 5 time when VF is Assigned VM guest.*************************************************************


2022-03-02 03:18:41 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-02 03:18:42 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-02 03:18:47 - test_network_sriov_stress.py - [line:103] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-02 03:18:47 - test_network_sriov_stress.py - [line:391] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-02 03:18:47 - test_network_sriov_stress.py - [line:394] - root - INFO - pf_id_key: 4b
2022-03-02 03:18:53 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-02 03:18:56 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-02 03:18:59 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 03:18:59 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:19:04 - test_network_sriov_stress.py - [line:117] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-02 03:19:07 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-02 03:19:07 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-02 03:19:12 - test_network_sriov_stress.py - [line:131] - root - INFO - Succssfully Gotten vf_id list:

2022-03-02 03:19:15 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-02 03:19:15 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:19:23 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-02 03:19:24 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:19:29 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 03:19:32 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-02 03:19:33 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:19:38 - test_network_sriov_stress.py - [line:164] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-02 03:19:38 - test_network_sriov_stress.py - [line:416] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 03:19:41 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-02 03:19:41 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-02 03:19:46 - test_network_sriov_stress.py - [line:427] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-02 03:19:49 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-02 03:19:49 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-02 03:19:54 - test_network_sriov_stress.py - [line:191] - root - INFO - Default network is active? yes

2022-03-02 03:19:58 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-02 03:19:59 - sshInstance.py - [line:71] - root - INFO - 
** (process:61527): [1;33mWARNING[0m **: [34m03:27:46.284[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:20:02 - test_network_sriov_stress.py - [line:223] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:61527): [1;33mWARNING[0m **: [34m03:27:46.284[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:20:02 - test_network_sriov_stress.py - [line:224] - root - ERROR - Failed to create a VM: 
2022-03-02 03:20:06 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-02 03:20:07 - sshInstance.py - [line:71] - root - INFO - 
** (process:61533): [1;33mWARNING[0m **: [34m03:27:54.285[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 03:20:08 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
2022-03-02 03:20:09 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-02 03:20:12 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest1
2022-03-02 03:20:16 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:61581): [1;33mWARNING[0m **: [34m03:28:04.061[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:20:19 - test_network_sriov_stress.py - [line:223] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:61581): [1;33mWARNING[0m **: [34m03:28:04.061[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-02 03:20:19 - test_network_sriov_stress.py - [line:224] - root - ERROR - Failed to create a VM: 
2022-03-02 03:20:23 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:61772): [1;33mWARNING[0m **: [34m03:28:11.061[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-02 03:20:25 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-02 03:20:28 - test_network_sriov_stress.py - [line:226] - root - INFO - Successfully created a VM: VMtest2
2022-03-02 03:20:31 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:20:31 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:20:36 - test_network_sriov_stress.py - [line:243] - root - ERROR - not found IP of VMtest1
2022-03-02 03:21:39 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:21:39 - sshInstance.py - [line:50] - root - INFO - 192.168.122.134/24

2022-03-02 03:21:44 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest1 IP: 192.168.122.134/24

2022-03-02 03:21:47 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-02 03:21:48 - sshInstance.py - [line:50] - root - INFO - 192.168.122.2/24

2022-03-02 03:21:53 - test_network_sriov_stress.py - [line:238] - root - INFO - Successfully got VMtest2 IP: 192.168.122.2/24

2022-03-02 03:21:53 - test_network_sriov_stress.py - [line:444] - root - INFO - ip of VM1: 192.168.122.134
2022-03-02 03:21:53 - test_network_sriov_stress.py - [line:445] - root - INFO - ip of VM1: 192.168.122.2
2022-03-02 03:21:57 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.389 ms
2022-03-02 03:21:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.436 ms
2022-03-02 03:21:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.516 ms
2022-03-02 03:22:00 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.458 ms
2022-03-02 03:22:01 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.299 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.299/0.419/0.516/0.076 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:22:10 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 03:22:19 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:30:02 PM EST
  System load:  0.0                Processes:             143
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 14:24:35 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:22:28 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 03:22:34 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 03:22:40 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 03:22:45 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 03:22:51 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-02 03:22:54 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 03:23:00 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 03:23:10 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-02 03:23:19 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 03:23:28 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 03:23:37 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 03:23:46 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:23:53 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.2
PING 192.168.122.2 (192.168.122.2) 56(84) bytes of data.
64 bytes from 192.168.122.2: icmp_seq=1 ttl=64 time=0.328 ms
2022-03-02 03:23:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=2 ttl=64 time=0.463 ms
2022-03-02 03:23:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=3 ttl=64 time=0.363 ms
2022-03-02 03:23:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=4 ttl=64 time=0.353 ms
2022-03-02 03:23:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.2: icmp_seq=5 ttl=64 time=0.459 ms

--- 192.168.122.2 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4127ms
rtt min/avg/max/mdev = 0.328/0.393/0.463/0.057 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:24:06 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.2
root@192.168.122.2's password: 
2022-03-02 03:24:15 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:31:59 PM EST
  System load:  0.0                Processes:             137
  Usage of /:   40.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.2
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Mar  1 14:22:16 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:24:24 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-02 03:24:30 - test_network_sriov_stress.py - [line:336] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-02 03:24:36 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-02 03:24:41 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-02 03:24:47 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-02 03:24:50 - test_network_sriov_stress.py - [line:297] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-02 03:24:56 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-02 03:25:06 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-02 03:25:15 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-02 03:25:24 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-02 03:25:33 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-02 03:25:42 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.2 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:25:45 - test_network_sriov_stress.py - [line:465] - root - INFO - Ping two vms IP from SUT:
2022-03-02 03:25:49 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.490 ms
2022-03-02 03:25:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.273 ms
2022-03-02 03:25:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.296 ms
2022-03-02 03:25:52 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.251 ms
2022-03-02 03:25:53 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.335 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4091ms
rtt min/avg/max/mdev = 0.251/0.329/0.490/0.085 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:26:00 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.453 ms
2022-03-02 03:26:01 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.285 ms
2022-03-02 03:26:02 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.230 ms
2022-03-02 03:26:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.236 ms
2022-03-02 03:26:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.227 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.227/0.286/0.453/0.086 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:26:07 - test_network_sriov_stress.py - [line:473] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 03:26:11 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.134
PING 192.168.122.134 (192.168.122.134) 56(84) bytes of data.
64 bytes from 192.168.122.134: icmp_seq=1 ttl=64 time=0.263 ms
2022-03-02 03:26:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=2 ttl=64 time=0.440 ms
2022-03-02 03:26:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=3 ttl=64 time=0.453 ms
2022-03-02 03:26:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=4 ttl=64 time=0.456 ms
2022-03-02 03:26:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.134: icmp_seq=5 ttl=64 time=0.467 ms

--- 192.168.122.134 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.263/0.415/0.467/0.081 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:26:24 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.134
root@192.168.122.134's password: 
2022-03-02 03:26:33 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 01 Mar 2022 02:34:16 PM EST
  System load:  0.0                Processes:             131
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.134
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

379 updates can be installed immediately.
245 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Tue Mar  1 14:30:03 2022 from 192.168.122.1
root@localhost:~# 
2022-03-02 03:26:40 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.292 ms
2022-03-02 03:26:41 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.253 ms
2022-03-02 03:26:42 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.216 ms
2022-03-02 03:26:43 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.264 ms
2022-03-02 03:26:44 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.328 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4077ms
rtt min/avg/max/mdev = 0.216/0.270/0.328/0.037 ms
root@localhost:~# 
2022-03-02 03:27:24 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.134 closed.
[root@WW25ICX2 ~]# 
2022-03-02 03:27:27 - test_network_sriov_stress.py - [line:481] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-02 03:27:31 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.256 ms
2022-03-02 03:27:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.254 ms
2022-03-02 03:27:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.242 ms
2022-03-02 03:27:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.236 ms
2022-03-02 03:27:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.218 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4118ms
rtt min/avg/max/mdev = 0.218/0.241/0.256/0.016 ms
[root@WW25ICX2 ~]# 
2022-03-02 03:27:41 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 03:27:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:27:48 - test_network_sriov_stress.py - [line:257] - root - INFO - Successfully removed VFs from PF.
2022-03-02 03:27:51 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-02 03:27:51 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-02 03:27:56 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-02 03:27:59 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-02 03:27:59 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-02 03:28:04 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest1
2022-03-02 03:28:07 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-02 03:28:08 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-02 03:28:13 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-02 03:28:16 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-02 03:28:16 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-02 03:28:21 - test_network_sriov_stress.py - [line:282] - root - INFO - Successfully removed the VM: VMtest2
.2022-03-02 03:28:24 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-02 03:28:24 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest2'


2022-03-02 03:28:29 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-02 03:28:32 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-02 03:28:32 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest2'


2022-03-02 03:28:37 - test_network_sriov_stress.py - [line:285] - root - ERROR - Failed to removed the VM VMtest2
2022-03-02 03:28:40 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-02 03:28:40 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest1'


2022-03-02 03:28:45 - test_network_sriov_stress.py - [line:272] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-02 03:28:48 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-02 03:28:48 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest1'


2022-03-02 03:28:53 - test_network_sriov_stress.py - [line:285] - root - ERROR - Failed to removed the VM VMtest1
2022-03-02 03:28:56 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-02 03:28:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:29:04 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 0
2022-03-02 03:29:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:29:12 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-02 03:29:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:29:20 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-02 03:29:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-02 03:29:25 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-02 03:29:25 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
                  [100%]

=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:57
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:57: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:91
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:91: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:66
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:66: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:105
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:105: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:376
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:376: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:493
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:493: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:792
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:792: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:76
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:76: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:100
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:100: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:122
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:122: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:148
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:148: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:186
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:186: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:210
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:210: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html -
========== 1 passed, 15 deselected, 13 warnings in 3011.14s (0:50:11) ==========
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
[8mha:////4LN/0LMxu1hyybTBeE6CHwDx82bv/lkvxFk3cdgHTSuWAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMPkEZb3/VO3favo5XL4AAAA=[0m[Pipeline] sh
+ sed -i $'s/\r//g' /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4FgvIflgycWoJq7MsZycbV9d7HENRG2WSX14oF+Me/GuAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiAR2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwZyt32U/vwBq1seBO+AAAA[0m[Pipeline] sh
+ chmod a+x /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4P37N80+NRbzyFlga2j1WDon6H/4VmnQwrRysqQpQX/3AAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigagQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUO62n9qHN+xdYwq+AAAA[0m[Pipeline] sh
+ sh /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
/root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh: line 7: [: too many arguments
[8mha:////4P3ih/vRXCzaXCkS1CQDBQXrb3I4EZcCr0NGGH+tKlR4AAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigUSDqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFDu9p/avgEjVhSLvgAAAA==[0m[Pipeline] }
[8mha:////4ISV0Ptmba0km8a80Gq+UClogdZnPDxCJXroOoeI5sULAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiREGBqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFDu9p/avgE81EHZvgAAAA==[0m[Pipeline] // stage
[8mha:////4LmA5LOJ1yGOO5YQ6RYn+/szIsYEkfxAArsUKSFs0Xa0AAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIpoEBCVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Nu9INt9AE/B/a+9AAAA[0m[Pipeline] }
[8mha:////4KVKO0UZMawo8C9tjXN4L1+ryWbU4zmvD2sDlsKoyYtXAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUVI5jZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0gL/eCrPwAXH35DL0AAAA=[0m[Pipeline] // node
[8mha:////4A8vvhfR6oegt+2XAbvn3Z0Fx6j3lb1QUh2abilCs+OGAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMJBiA5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBAx/ra70AAAA=[0m[Pipeline] End of Pipeline
Finished: SUCCESS
