Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/Jiz1028/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"1.6.4"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","pf1":"ens2f0","os":"RHEL"},"pkg_generator":{"host":"10.112.97.60","pf1":"ens2f1"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 17 items / 16 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-14 15:53:16 - NicTestFixture.py - [line:37] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
2022-03-14 15:53:16 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-14 15:53:16 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-14 15:53:16 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-14 15:53:16 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-14 15:53:16 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-14 15:53:16 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-14 15:53:16 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-14 15:53:16 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-14 15:53:19 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-14 15:53:19 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-14 15:53:27 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-14 15:53:32 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:53:40 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-14 15:53:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:53:53 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 up
2022-03-14 15:53:53 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:54:01 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-14 15:54:01 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-14 15:54:09 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-14 15:54:09 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fe9c:f7a4  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19  bytes 3068 (2.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-14 15:54:17 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1
2022-03-14 15:54:17 - sshInstance.py - [line:50] - root - INFO - ens2f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea5:9b45  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a5:9b:45  txqueuelen 1000  (Ethernet)
        RX packets 6097575926  bytes 9229273140717 (8.3 TiB)
        RX errors 0  dropped 85  overruns 0  frame 0
        TX packets 211278862  bytes 16112312126 (15.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-14 15:54:22 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-14 15:54:25 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 15:54:26 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 15:54:31 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 15:54:31 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 15:54:31 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 15:54:37 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 14 15:57:08 2022 from 10.254.214.76
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 15:54:40 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 15:54:43 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 15:54:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:54:48 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 15:54:51 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 15:54:51 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 15:54:56 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 15:54:59 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 15:54:59 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:55:07 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 15:55:08 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:55:13 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:55:16 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 15:55:17 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:55:22 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:55:22 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:55:25 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:55:25 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 15:55:30 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 15:55:33 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 15:55:33 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 15:55:38 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 15:55:42 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:19215): [1;33mWARNING[0m **: [34m16:04:07.265[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:55:44 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:55:47 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 15:55:51 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:19271): [1;33mWARNING[0m **: [34m16:04:16.258[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:55:53 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:55:56 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 15:55:59 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:55:59 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:56:04 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 15:57:07 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:57:07 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 15:57:12 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.72/24

2022-03-14 15:57:15 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:57:15 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 15:57:20 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.208/24

2022-03-14 15:57:20 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 15:57:20 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 15:57:24 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.226 ms
2022-03-14 15:57:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.476 ms
2022-03-14 15:57:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.361 ms
2022-03-14 15:57:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.357 ms
2022-03-14 15:57:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.468 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.226/0.377/0.476/0.093 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:57:37 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 15:57:46 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:06:08 AM EDT
  System load:  0.0                Processes:             137
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:47:21 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:57:55 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 15:58:01 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 15:58:07 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 15:58:12 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 15:58:19 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 15:58:22 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 15:58:28 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 15:58:38 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 15:58:47 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 15:58:56 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 15:59:05 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 15:59:14 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:59:21 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.302 ms
2022-03-14 15:59:22 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.257 ms
2022-03-14 15:59:23 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.114 ms
2022-03-14 15:59:24 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.468 ms
2022-03-14 15:59:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.472 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4132ms
rtt min/avg/max/mdev = 0.114/0.322/0.472/0.136 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:59:34 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 15:59:43 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:08:04 AM EDT
  System load:  0.0                Processes:             131
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:49:17 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:59:52 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 15:59:58 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 16:00:04 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 16:00:09 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 16:00:15 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 16:00:18 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 16:00:24 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 16:00:34 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 16:00:43 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 16:00:52 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 16:01:01 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 16:01:10 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 16:01:13 - test_network_sriov_stress.py - [line:468] - root - INFO - Ping two vms IP from SUT:
2022-03-14 16:01:17 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.644 ms
2022-03-14 16:01:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.173 ms
2022-03-14 16:01:19 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.216 ms
2022-03-14 16:01:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.116 ms
2022-03-14 16:01:21 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.182 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.116/0.266/0.644/0.191 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:01:28 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.361 ms
2022-03-14 16:01:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.314 ms
2022-03-14 16:01:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.185 ms
2022-03-14 16:01:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.210 ms
2022-03-14 16:01:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.189 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4091ms
rtt min/avg/max/mdev = 0.185/0.251/0.361/0.074 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:01:35 - test_network_sriov_stress.py - [line:476] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 16:01:39 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.313 ms
2022-03-14 16:01:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.328 ms
2022-03-14 16:01:41 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.307 ms
2022-03-14 16:01:42 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.471 ms
2022-03-14 16:01:43 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.476 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.307/0.379/0.476/0.077 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:01:52 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 16:02:01 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:10:23 AM EDT
  System load:  0.0                Processes:             129
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 04:06:09 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 16:02:08 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.425 ms
2022-03-14 16:02:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.143 ms
2022-03-14 16:02:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.219 ms
2022-03-14 16:02:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.144 ms
2022-03-14 16:02:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.223 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4095ms
rtt min/avg/max/mdev = 0.143/0.230/0.425/0.103 ms
root@localhost:~# 
2022-03-14 16:02:52 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 16:02:55 - test_network_sriov_stress.py - [line:484] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 16:02:59 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 16:03:02 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 16:03:05 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4121ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 16:03:11 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 16:03:13 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:03:18 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 16:03:21 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 16:03:21 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 16:03:26 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 16:03:29 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 16:03:29 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 16:03:34 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 16:03:37 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 16:03:38 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 16:03:43 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 16:03:46 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 16:03:46 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 16:03:51 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 16:03:51 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2022-03-14 16:03:54 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 16:03:54 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 16:03:59 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 16:03:59 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 16:03:59 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 16:04:05 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 16:04:08 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 16:04:11 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 16:04:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:04:16 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 16:04:19 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 16:04:20 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 16:04:25 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 16:04:28 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 16:04:28 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:04:36 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 16:04:36 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:04:41 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 16:04:44 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 16:04:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:04:50 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 16:04:50 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 16:04:53 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 16:04:53 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 16:04:58 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 16:05:01 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 16:05:01 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 16:05:06 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 16:05:10 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:28103): [1;33mWARNING[0m **: [34m16:13:35.555[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
2022-03-14 16:05:11 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-14 16:05:14 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:28103): [1;33mWARNING[0m **: [34m16:13:35.555[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:05:14 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 16:05:18 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:28108): [1;33mWARNING[0m **: [34m16:13:43.553[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 16:05:20 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 16:05:23 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 16:05:27 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:28163): [1;33mWARNING[0m **: [34m16:13:52.565[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
2022-03-14 16:05:28 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-14 16:05:31 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:28163): [1;33mWARNING[0m **: [34m16:13:52.565[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:05:31 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 16:05:35 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:28174): [1;33mWARNING[0m **: [34m16:14:00.522[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 16:05:37 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 16:05:40 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 16:05:43 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 16:05:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:05:48 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 16:06:52 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 16:06:52 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 16:06:57 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.72/24

2022-03-14 16:07:00 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 16:07:00 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 16:07:05 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.208/24

2022-03-14 16:07:05 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 16:07:05 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 16:07:09 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.321 ms
2022-03-14 16:07:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.283 ms
2022-03-14 16:07:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.381 ms
2022-03-14 16:07:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.470 ms
2022-03-14 16:07:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.483 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4105ms
rtt min/avg/max/mdev = 0.283/0.387/0.483/0.082 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:07:22 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 16:07:31 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:15:52 AM EDT
  System load:  0.08               Processes:             139
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 04:10:23 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 16:07:40 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 16:07:46 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 16:07:52 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 16:07:57 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 16:08:03 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 16:08:06 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 16:08:12 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 16:08:22 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 16:08:31 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 16:08:40 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 16:08:49 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 16:08:58 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 16:09:05 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.464 ms
2022-03-14 16:09:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.476 ms
2022-03-14 16:09:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.317 ms
2022-03-14 16:09:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.461 ms
2022-03-14 16:09:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.465 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4134ms
rtt min/avg/max/mdev = 0.317/0.436/0.476/0.064 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:09:18 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 16:09:27 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:17:48 AM EDT
  System load:  0.09               Processes:             140
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 04:08:05 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 16:09:36 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 16:09:42 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 16:09:48 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 16:09:53 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 16:09:59 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 16:10:02 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 16:10:08 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 16:10:18 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 16:10:27 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 16:10:36 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 16:10:45 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 16:10:54 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 16:10:57 - test_network_sriov_stress.py - [line:468] - root - INFO - Ping two vms IP from SUT:
2022-03-14 16:11:01 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.404 ms
2022-03-14 16:11:02 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.281 ms
2022-03-14 16:11:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.296 ms
2022-03-14 16:11:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.228 ms
2022-03-14 16:11:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.275 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.228/0.296/0.404/0.062 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:11:12 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.615 ms
2022-03-14 16:11:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.289 ms
2022-03-14 16:11:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.114 ms
2022-03-14 16:11:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.264 ms
2022-03-14 16:11:16 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.255 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4093ms
rtt min/avg/max/mdev = 0.114/0.307/0.615/0.166 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:11:19 - test_network_sriov_stress.py - [line:476] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 16:11:23 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.300 ms
2022-03-14 16:11:24 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.460 ms
2022-03-14 16:11:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.395 ms
2022-03-14 16:11:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.298 ms
2022-03-14 16:11:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.460 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4086ms
rtt min/avg/max/mdev = 0.298/0.382/0.460/0.075 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:11:36 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 16:11:45 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:20:06 AM EDT
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 04:15:52 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 16:11:52 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.338 ms
2022-03-14 16:11:53 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.238 ms
2022-03-14 16:11:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.130 ms
2022-03-14 16:11:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.364 ms
2022-03-14 16:11:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.342 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4084ms
rtt min/avg/max/mdev = 0.130/0.282/0.364/0.087 ms
root@localhost:~# 
2022-03-14 16:12:36 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 16:12:39 - test_network_sriov_stress.py - [line:484] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 16:12:43 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 16:12:46 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 16:12:49 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4124ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 16:12:55 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 16:12:57 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:13:02 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 16:13:05 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 16:13:06 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 16:13:11 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 16:13:14 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 16:13:14 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 16:13:19 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 16:13:22 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 16:13:22 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 16:13:27 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 16:13:30 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 16:13:30 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 16:13:35 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 16:13:35 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 3 time when VF is Assigned VM guest.*************************************************************


2022-03-14 16:13:38 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 16:13:39 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 16:13:44 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 16:13:44 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 16:13:44 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 16:13:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 16:13:53 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 16:13:56 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 16:13:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:14:01 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 16:14:04 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 16:14:04 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 16:14:09 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 16:14:12 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 16:14:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:14:20 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 16:14:21 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:14:26 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 16:14:29 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 16:14:30 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:14:35 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 16:14:35 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 16:14:38 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 16:14:38 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 16:14:43 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 16:14:46 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 16:14:46 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 16:14:51 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 16:14:55 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-14 16:14:56 - sshInstance.py - [line:71] - root - INFO - 
** (process:31746): [1;33mWARNING[0m **: [34m16:23:20.087[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:14:59 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:31746): [1;33mWARNING[0m **: [34m16:23:20.087[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:14:59 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 16:15:03 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-14 16:15:04 - sshInstance.py - [line:71] - root - INFO - 
** (process:31751): [1;33mWARNING[0m **: [34m16:23:28.071[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 16:15:06 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 16:15:09 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 16:15:13 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:31799): [1;33mWARNING[0m **: [34m16:23:37.860[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:15:16 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:31799): [1;33mWARNING[0m **: [34m16:23:37.860[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:15:16 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 16:15:20 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:31807): [1;33mWARNING[0m **: [34m16:23:44.853[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 16:15:22 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 16:15:25 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 16:15:28 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 16:15:28 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:15:33 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 16:16:36 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 16:16:36 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 16:16:41 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.72/24

2022-03-14 16:16:44 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 16:16:44 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 16:16:49 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.208/24

2022-03-14 16:16:49 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 16:16:49 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 16:16:53 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.354 ms
2022-03-14 16:16:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.403 ms
2022-03-14 16:16:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.288 ms
2022-03-14 16:16:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.282 ms
2022-03-14 16:16:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.463 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4105ms
rtt min/avg/max/mdev = 0.282/0.358/0.463/0.068 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:17:06 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 16:17:15 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:25:36 AM EDT
  System load:  0.07               Processes:             135
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 04:20:06 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 16:17:24 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 16:17:30 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 16:17:36 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 16:17:41 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 16:17:47 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 16:17:50 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 16:17:56 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 16:18:06 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 16:18:15 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 16:18:24 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 16:18:33 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 16:18:42 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 16:18:49 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.214 ms
2022-03-14 16:18:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.460 ms
2022-03-14 16:18:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.299 ms
2022-03-14 16:18:52 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.281 ms
2022-03-14 16:18:53 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.319 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4133ms
rtt min/avg/max/mdev = 0.214/0.314/0.460/0.083 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:19:02 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 16:19:11 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:27:33 AM EDT
  System load:  0.0                Processes:             137
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 04:17:48 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 16:19:20 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 16:19:26 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 16:19:32 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 16:19:37 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 16:19:43 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 16:19:46 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 16:19:52 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 16:20:02 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 16:20:11 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 16:20:20 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 16:20:29 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 346 (346.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 16:20:38 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 16:20:41 - test_network_sriov_stress.py - [line:468] - root - INFO - Ping two vms IP from SUT:
2022-03-14 16:20:45 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.358 ms
2022-03-14 16:20:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.236 ms
2022-03-14 16:20:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.335 ms
2022-03-14 16:20:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.250 ms
2022-03-14 16:20:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.299 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.236/0.295/0.358/0.050 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:20:56 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.338 ms
2022-03-14 16:20:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.313 ms
2022-03-14 16:20:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.229 ms
2022-03-14 16:20:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.225 ms
2022-03-14 16:21:00 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.185 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4093ms
rtt min/avg/max/mdev = 0.185/0.258/0.338/0.057 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:21:03 - test_network_sriov_stress.py - [line:476] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 16:21:07 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.406 ms
2022-03-14 16:21:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.527 ms
2022-03-14 16:21:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.450 ms
2022-03-14 16:21:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.412 ms
2022-03-14 16:21:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.530 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4086ms
rtt min/avg/max/mdev = 0.406/0.465/0.530/0.054 ms
[root@WW25ICX2 ~]# 
2022-03-14 16:21:20 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 16:21:29 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 04:29:51 AM EDT
  System load:  0.0                Processes:             131
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 04:25:37 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 16:21:36 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.417 ms
2022-03-14 16:21:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.217 ms
2022-03-14 16:21:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.171 ms
2022-03-14 16:21:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.222 ms
2022-03-14 16:21:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.207 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4077ms
rtt min/avg/max/mdev = 0.171/0.246/0.417/0.086 ms
root@localhost:~# 
2022-03-14 16:22:20 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 16:22:23 - test_network_sriov_stress.py - [line:484] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 16:22:27 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 16:22:30 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 16:22:33 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4122ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 16:22:39 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 16:22:42 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:22:47 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 16:22:50 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 16:22:50 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 16:22:55 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 16:22:58 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 16:22:58 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 16:23:03 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 16:23:06 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 16:23:06 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 16:23:11 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 16:23:14 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 16:23:14 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 16:23:19 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 16:23:19 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 4 time when VF is Assigned VM guest.*************************************************************


2022-03-14 16:23:22 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 16:23:23 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 16:23:28 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 16:23:28 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 16:23:28 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 16:23:34 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 16:23:37 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 16:23:40 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 16:23:40 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:23:45 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 16:23:48 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 16:23:48 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 16:23:53 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 16:23:56 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 16:23:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:24:04 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 16:24:05 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:24:10 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 16:24:13 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 16:24:14 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 16:24:19 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 16:24:19 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 16:24:22 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 16:24:22 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 16:24:27 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 16:24:30 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 16:24:30 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 16:24:35 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 16:24:39 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:38440): [1;33mWARNING[0m **: [34m16:33:04.305[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
2022-03-14 16:24:40 - sshInstance.py - [line:71] - root - INFO - WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:24:43 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:38440): [1;33mWARNING[0m **: [34m16:33:04.305[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:24:43 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 16:24:47 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:38449): [1;33mWARNING[0m **: [34m16:33:12.156[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 16:24:49 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 16:24:52 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 16:24:56 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:38492): [1;33mWARNING[0m **: [34m16:33:21.296[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 16:24:57 - sshInstance.py - [line:71] - root - INFO - ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:25:00 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:38492): [1;33mWARNING[0m **: [34m16:33:21.296[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 16:25:00 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 16:25:04 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole
2022-03-14 16:25:05 - sshInstance.py - [line:71] - root - INFO - 
** (process:38500): [1;33mWARNING[0m **: [34m16:33:29.410[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 16:25:07 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# Aborted by [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Sending interrupt signal to process
/root/.jenkins/workspace/test-test-nic-sriov-5times@tmp/durable-b1f47ba9/script.sh: line 1: 710214 Terminated              pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
script returned exit code 143
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4AfI3SthhIf/wHKBxkZZVuznCBOLGICd+mTaK5J1XhvpAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMHmfoKzrT+3fkMfZ274AAAA=[0m[Pipeline] }
[8mha:////4O1G14z5oV6C9jl1Q5yIn+pZFQRmsElhyj6JiXyHA8ixAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiBB2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7BpKm1V++AAAA[0m[Pipeline] // stage
[8mha:////4KtBCOpIKS64HlRGbxVDHBnhT4546C6ceKSEgLxKWO63AAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUauVY2WZoPEGEGAOZXUwWofJEXs07yMiMlb/67zXv9cYyRRw5OtVYaj2lyqsu9G56auDYXgMPquGLqpgSB6tKO5Rc29OMJYvFvCzHQmNlqQqcPDnBWjfmYYpgyBVniZM7aOS+vuOJTE9lMVG+MEZsbn2dmH6dvwGMXSfIt3tBtvsA/gVtV70AAAA=[0m[Pipeline] }
[8mha:////4PVa+eOfGCB5ryE2GyokIfyPZOVvh3emQVgJTOuHuCGAAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IMJC7GybVh8Qsq1Fpo3sP2IUx+kb/mP0gkcfJO95zlvN5Yp4gjR6daS52nVHvVh8HNT40cu2vgUbV8UTVT4mBVZceKG3tasGKxWJblWGlsLNWBkycn2OrWPEwRDLniLHF2B43cN3c8kem5LCbKF6aI3W1oEtOv8zeAqe8FebkXZOUHjeqpjr0AAAA=[0m[Pipeline] // node
[8mha:////4OyM7hMK6utvbTfbnNkjhtaoCHWCq3+ZbQ+BNe9AvJHZAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRoKBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Lu9INt+AKvzzsS9AAAA[0m[Pipeline] End of Pipeline
Finished: ABORTED
