Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"1.6.4"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","connect_switch_sut_pf":"ens2f0","pf1":"ens2f0","pf1_ipv6":"fe80::b696:91ff:fe9c:f7a4","os":"RHEL"},"dhcp":{"ipv4":"192.168.10.11","ipv6":"fe80::b696:91ff:fea5:9b45"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 16 items / 15 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-08 02:38:44 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
2022-03-08 02:38:44 - test_network_sriov_stress.py - [line:31] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-08 02:38:44 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-08 02:38:44 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-08 02:38:44 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-08 02:38:44 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-08 02:38:44 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-08 02:38:44 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-08 02:38:44 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-08 02:38:47 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-08 02:38:47 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-08 02:38:55 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-08 02:38:59 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:39:07 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-08 02:39:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:39:20 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-08 02:39:20 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-08 02:39:25 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-08 02:39:28 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-08 02:39:29 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-08 02:39:34 - test_network_sriov_stress.py - [line:108] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-08 02:39:34 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-08 02:39:34 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 4b
2022-03-08 02:39:40 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Tue Mar  8 02:03:54 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-08 02:39:43 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-08 02:39:46 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 02:39:46 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:39:51 - test_network_sriov_stress.py - [line:122] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-08 02:39:54 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-08 02:39:54 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-08 02:39:59 - test_network_sriov_stress.py - [line:136] - root - INFO - Succssfully Gotten vf_id list:

2022-03-08 02:40:02 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-08 02:40:02 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:40:10 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-08 02:40:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:40:16 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 02:40:19 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-08 02:40:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:40:25 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 02:40:25 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 02:40:28 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 02:40:28 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-08 02:40:33 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-08 02:40:36 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-08 02:40:36 - sshInstance.py - [line:50] - root - INFO - no

2022-03-08 02:40:41 - test_network_sriov_stress.py - [line:196] - root - INFO - Default network is active? no

2022-03-08 02:40:41 - test_network_sriov_stress.py - [line:205] - root - INFO - virsh net-start default
2022-03-08 02:40:44 - sshInstance.py - [line:46] - root - INFO - virsh net-start default
2022-03-08 02:40:45 - sshInstance.py - [line:50] - root - INFO - Network default started


2022-03-08 02:40:50 - test_network_sriov_stress.py - [line:209] - root - INFO - Successfully started network default.
2022-03-08 02:40:54 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:119291): [1;33mWARNING[0m **: [34m02:48:42.100[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 02:40:56 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-08 02:40:59 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest1
2022-03-08 02:41:03 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole
2022-03-08 02:41:04 - sshInstance.py - [line:71] - root - INFO - 
** (process:119359): [1;33mWARNING[0m **: [34m02:48:51.180[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 02:41:05 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-08 02:41:08 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest2
2022-03-08 02:41:11 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 02:41:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:41:16 - test_network_sriov_stress.py - [line:248] - root - ERROR - not found IP of VMtest1
2022-03-08 02:42:19 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 02:42:19 - sshInstance.py - [line:50] - root - INFO - 192.168.122.65/24

2022-03-08 02:42:24 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest1 IP: 192.168.122.65/24

2022-03-08 02:42:27 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-08 02:42:27 - sshInstance.py - [line:50] - root - INFO - 192.168.122.184/24

2022-03-08 02:42:32 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest2 IP: 192.168.122.184/24

2022-03-08 02:42:32 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.65
2022-03-08 02:42:32 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.184
2022-03-08 02:42:36 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.338 ms
2022-03-08 02:42:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.285 ms
2022-03-08 02:42:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.481 ms
2022-03-08 02:42:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.451 ms
2022-03-08 02:42:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.489 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.285/0.408/0.489/0.086 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:42:49 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
The authenticity of host '192.168.122.65 (192.168.122.65)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-08 02:42:58 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.65' (ECDSA) to the list of known hosts.
root@192.168.122.65's password: 
2022-03-08 02:43:07 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 01:50:51 PM EST
  System load:  0.07               Processes:             138
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Thu Mar  3 18:49:17 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 02:43:16 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 02:43:22 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 02:43:28 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 02:43:33 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 02:43:39 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-08 02:43:42 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 02:43:48 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 02:43:58 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-08 02:44:07 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 02:44:16 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 02:44:25 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 02:44:34 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 02:44:41 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.184
PING 192.168.122.184 (192.168.122.184) 56(84) bytes of data.
64 bytes from 192.168.122.184: icmp_seq=1 ttl=64 time=0.403 ms
2022-03-08 02:44:42 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=2 ttl=64 time=0.481 ms
2022-03-08 02:44:43 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=3 ttl=64 time=0.499 ms
2022-03-08 02:44:44 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=4 ttl=64 time=0.467 ms
2022-03-08 02:44:45 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=5 ttl=64 time=0.351 ms

--- 192.168.122.184 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4079ms
rtt min/avg/max/mdev = 0.351/0.440/0.499/0.056 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:44:54 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.184
root@192.168.122.184's password: 
2022-03-08 02:45:03 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 01:52:48 PM EST
  System load:  0.0                Processes:             143
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.184
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Thu Mar  3 18:47:20 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 02:45:12 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 02:45:18 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 02:45:24 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 02:45:29 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 02:45:35 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-08 02:45:38 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 02:45:44 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 02:45:54 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-08 02:46:03 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 02:46:12 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 02:46:21 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 02:46:30 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.184 closed.
[root@WW25ICX2 ~]# 
2022-03-08 02:46:33 - test_network_sriov_stress.py - [line:470] - root - INFO - Ping two vms IP from SUT:
2022-03-08 02:46:37 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.293 ms
2022-03-08 02:46:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.298 ms
2022-03-08 02:46:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.201 ms
2022-03-08 02:46:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.197 ms
2022-03-08 02:46:41 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.196 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4108ms
rtt min/avg/max/mdev = 0.196/0.237/0.298/0.047 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:46:48 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.405 ms
2022-03-08 02:46:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.264 ms
2022-03-08 02:46:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.267 ms
2022-03-08 02:46:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.262 ms
2022-03-08 02:46:52 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.238 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.238/0.287/0.405/0.060 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:46:55 - test_network_sriov_stress.py - [line:478] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 02:46:59 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.349 ms
2022-03-08 02:47:00 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.234 ms
2022-03-08 02:47:01 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.463 ms
2022-03-08 02:47:02 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.318 ms
2022-03-08 02:47:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.471 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.234/0.367/0.471/0.089 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:47:12 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 02:47:21 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 01:55:06 PM EST
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 13:50:52 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 02:47:28 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.559 ms
2022-03-08 02:47:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.351 ms
2022-03-08 02:47:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.272 ms
2022-03-08 02:47:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.125 ms
2022-03-08 02:47:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.205 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4076ms
rtt min/avg/max/mdev = 0.125/0.302/0.559/0.148 ms
root@localhost:~# 
2022-03-08 02:48:12 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 02:48:15 - test_network_sriov_stress.py - [line:486] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 02:48:19 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.455 ms
2022-03-08 02:48:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.283 ms
2022-03-08 02:48:21 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.198 ms
2022-03-08 02:48:22 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.180 ms
2022-03-08 02:48:23 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.201 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4135ms
rtt min/avg/max/mdev = 0.180/0.263/0.455/0.103 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:48:29 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 02:48:32 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:48:37 - test_network_sriov_stress.py - [line:262] - root - INFO - Successfully removed VFs from PF.
2022-03-08 02:48:40 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-08 02:48:40 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-08 02:48:45 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-08 02:48:48 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-08 02:48:48 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-08 02:48:53 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-08 02:48:56 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-08 02:48:56 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-08 02:49:01 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-08 02:49:04 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-08 02:49:04 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-08 02:49:09 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-08 02:49:09 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2022-03-08 02:49:12 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-08 02:49:13 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-08 02:49:18 - test_network_sriov_stress.py - [line:108] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-08 02:49:18 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-08 02:49:18 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 4b
2022-03-08 02:49:24 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-08 02:49:27 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-08 02:49:30 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 02:49:30 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:49:35 - test_network_sriov_stress.py - [line:122] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-08 02:49:38 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-08 02:49:38 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-08 02:49:43 - test_network_sriov_stress.py - [line:136] - root - INFO - Succssfully Gotten vf_id list:

2022-03-08 02:49:46 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-08 02:49:46 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:49:54 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-08 02:49:55 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:50:00 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 02:50:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-08 02:50:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:50:09 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 02:50:09 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 02:50:12 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 02:50:12 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-08 02:50:17 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-08 02:50:20 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-08 02:50:20 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-08 02:50:25 - test_network_sriov_stress.py - [line:196] - root - INFO - Default network is active? yes

2022-03-08 02:50:29 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:120814): [1;33mWARNING[0m **: [34m02:58:17.201[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 02:50:32 - test_network_sriov_stress.py - [line:228] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:120814): [1;33mWARNING[0m **: [34m02:58:17.201[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 02:50:32 - test_network_sriov_stress.py - [line:229] - root - ERROR - Failed to create a VM: 
2022-03-08 02:50:36 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:120992): [1;33mWARNING[0m **: [34m02:58:24.365[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 02:50:39 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-08 02:50:42 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest1
2022-03-08 02:50:46 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:121041): [1;33mWARNING[0m **: [34m02:58:34.358[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
2022-03-08 02:50:47 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-08 02:50:50 - test_network_sriov_stress.py - [line:228] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:121041): [1;33mWARNING[0m **: [34m02:58:34.358[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 02:50:50 - test_network_sriov_stress.py - [line:229] - root - ERROR - Failed to create a VM: 
2022-03-08 02:50:54 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole
2022-03-08 02:50:55 - sshInstance.py - [line:71] - root - INFO - 
** (process:121046): [1;33mWARNING[0m **: [34m02:58:42.477[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 02:50:57 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-08 02:51:00 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest2
2022-03-08 02:51:03 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 02:51:03 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:51:08 - test_network_sriov_stress.py - [line:248] - root - ERROR - not found IP of VMtest1
2022-03-08 02:52:11 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 02:52:11 - sshInstance.py - [line:50] - root - INFO - 192.168.122.65/24

2022-03-08 02:52:16 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest1 IP: 192.168.122.65/24

2022-03-08 02:52:19 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-08 02:52:19 - sshInstance.py - [line:50] - root - INFO - 192.168.122.184/24

2022-03-08 02:52:24 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest2 IP: 192.168.122.184/24

2022-03-08 02:52:24 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.65
2022-03-08 02:52:24 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.184
2022-03-08 02:52:28 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.471 ms
2022-03-08 02:52:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.319 ms
2022-03-08 02:52:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.468 ms
2022-03-08 02:52:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.467 ms
2022-03-08 02:52:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.429 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4128ms
rtt min/avg/max/mdev = 0.319/0.430/0.471/0.063 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:52:41 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 02:52:50 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:00:35 PM EST
  System load:  0.15               Processes:             142
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 13:55:06 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 02:52:59 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 02:53:05 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 02:53:11 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 02:53:16 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 02:53:22 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-08 02:53:25 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 02:53:31 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 02:53:41 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-08 02:53:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 02:53:59 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 02:54:08 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 02:54:17 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 02:54:24 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.184
PING 192.168.122.184 (192.168.122.184) 56(84) bytes of data.
64 bytes from 192.168.122.184: icmp_seq=1 ttl=64 time=0.280 ms
2022-03-08 02:54:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=2 ttl=64 time=0.481 ms
2022-03-08 02:54:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=3 ttl=64 time=0.476 ms
2022-03-08 02:54:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=4 ttl=64 time=0.475 ms
2022-03-08 02:54:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=5 ttl=64 time=0.546 ms

--- 192.168.122.184 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4092ms
rtt min/avg/max/mdev = 0.280/0.451/0.546/0.092 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:54:37 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.184
root@192.168.122.184's password: 
2022-03-08 02:54:47 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:02:31 PM EST
  System load:  0.02               Processes:             137
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.184
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 13:52:49 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 02:54:57 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 02:55:03 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 02:55:09 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 02:55:14 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 02:55:20 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-08 02:55:23 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 02:55:29 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 02:55:39 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-08 02:55:48 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 02:55:57 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 02:56:06 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1038 (1.0 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 02:56:15 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.184 closed.
[root@WW25ICX2 ~]# 
2022-03-08 02:56:18 - test_network_sriov_stress.py - [line:470] - root - INFO - Ping two vms IP from SUT:
2022-03-08 02:56:22 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.329 ms
2022-03-08 02:56:23 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.132 ms
2022-03-08 02:56:24 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.250 ms
2022-03-08 02:56:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.258 ms
2022-03-08 02:56:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.262 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4081ms
rtt min/avg/max/mdev = 0.132/0.246/0.329/0.064 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:56:33 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.383 ms
2022-03-08 02:56:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.264 ms
2022-03-08 02:56:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.237 ms
2022-03-08 02:56:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.244 ms
2022-03-08 02:56:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.268 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4075ms
rtt min/avg/max/mdev = 0.237/0.279/0.383/0.054 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:56:40 - test_network_sriov_stress.py - [line:478] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 02:56:44 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.455 ms
2022-03-08 02:56:45 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.477 ms
2022-03-08 02:56:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.301 ms
2022-03-08 02:56:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.398 ms
2022-03-08 02:56:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.400 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4133ms
rtt min/avg/max/mdev = 0.301/0.406/0.477/0.062 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:56:57 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 02:57:06 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:04:50 PM EST
  System load:  0.0                Processes:             131
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:00:35 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 02:57:13 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.510 ms
2022-03-08 02:57:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.322 ms
2022-03-08 02:57:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.390 ms
2022-03-08 02:57:16 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.290 ms
2022-03-08 02:57:17 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.255 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4100ms
rtt min/avg/max/mdev = 0.255/0.353/0.510/0.090 ms
root@localhost:~# 
2022-03-08 02:57:57 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 02:58:00 - test_network_sriov_stress.py - [line:486] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 02:58:04 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.202 ms
2022-03-08 02:58:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.112 ms
2022-03-08 02:58:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.184 ms
2022-03-08 02:58:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.206 ms
2022-03-08 02:58:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.183 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4106ms
rtt min/avg/max/mdev = 0.112/0.177/0.206/0.036 ms
[root@WW25ICX2 ~]# 
2022-03-08 02:58:14 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 02:58:16 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:58:21 - test_network_sriov_stress.py - [line:262] - root - INFO - Successfully removed VFs from PF.
2022-03-08 02:58:24 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-08 02:58:24 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-08 02:58:29 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-08 02:58:32 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-08 02:58:32 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-08 02:58:37 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-08 02:58:40 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-08 02:58:41 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-08 02:58:46 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-08 02:58:49 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-08 02:58:49 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-08 02:58:54 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-08 02:58:54 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 3 time when VF is Assigned VM guest.*************************************************************


2022-03-08 02:58:57 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-08 02:58:57 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-08 02:59:02 - test_network_sriov_stress.py - [line:108] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-08 02:59:02 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-08 02:59:02 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 4b
2022-03-08 02:59:08 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-08 02:59:11 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-08 02:59:14 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 02:59:14 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:59:19 - test_network_sriov_stress.py - [line:122] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-08 02:59:22 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-08 02:59:23 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-08 02:59:28 - test_network_sriov_stress.py - [line:136] - root - INFO - Succssfully Gotten vf_id list:

2022-03-08 02:59:31 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-08 02:59:31 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:59:39 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-08 02:59:39 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:59:44 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 02:59:47 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-08 02:59:48 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 02:59:53 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 02:59:53 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 02:59:56 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 02:59:56 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-08 03:00:01 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-08 03:00:04 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-08 03:00:04 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-08 03:00:09 - test_network_sriov_stress.py - [line:196] - root - INFO - Default network is active? yes

2022-03-08 03:00:13 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:122134): [1;33mWARNING[0m **: [34m03:08:01.604[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:00:16 - test_network_sriov_stress.py - [line:228] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:122134): [1;33mWARNING[0m **: [34m03:08:01.604[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:00:16 - test_network_sriov_stress.py - [line:229] - root - ERROR - Failed to create a VM: 
2022-03-08 03:00:20 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:122139): [1;33mWARNING[0m **: [34m03:08:08.606[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 03:00:22 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
2022-03-08 03:00:23 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-08 03:00:26 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest1
2022-03-08 03:00:30 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:122197): [1;33mWARNING[0m **: [34m03:08:18.651[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:00:33 - test_network_sriov_stress.py - [line:228] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:122197): [1;33mWARNING[0m **: [34m03:08:18.651[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:00:33 - test_network_sriov_stress.py - [line:229] - root - ERROR - Failed to create a VM: 
2022-03-08 03:00:37 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole
2022-03-08 03:00:38 - sshInstance.py - [line:71] - root - INFO - 
** (process:122204): [1;33mWARNING[0m **: [34m03:08:25.785[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 03:00:39 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-08 03:00:42 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest2
2022-03-08 03:00:45 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:00:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:00:50 - test_network_sriov_stress.py - [line:248] - root - ERROR - not found IP of VMtest1
2022-03-08 03:01:53 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:01:54 - sshInstance.py - [line:50] - root - INFO - 192.168.122.65/24

2022-03-08 03:01:59 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest1 IP: 192.168.122.65/24

2022-03-08 03:02:02 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:02:02 - sshInstance.py - [line:50] - root - INFO - 192.168.122.184/24

2022-03-08 03:02:07 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest2 IP: 192.168.122.184/24

2022-03-08 03:02:07 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.65
2022-03-08 03:02:07 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.184
2022-03-08 03:02:11 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.323 ms
2022-03-08 03:02:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.298 ms
2022-03-08 03:02:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.461 ms
2022-03-08 03:02:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.474 ms
2022-03-08 03:02:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.474 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4131ms
rtt min/avg/max/mdev = 0.298/0.406/0.474/0.078 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:02:24 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 03:02:33 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:10:16 PM EST
  System load:  0.07               Processes:             137
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:04:50 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:02:42 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 03:02:48 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 03:02:54 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 03:02:59 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 03:03:05 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-08 03:03:08 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 03:03:14 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 03:03:24 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-08 03:03:33 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 03:03:42 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 03:03:51 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 03:04:00 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:04:07 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.184
PING 192.168.122.184 (192.168.122.184) 56(84) bytes of data.
64 bytes from 192.168.122.184: icmp_seq=1 ttl=64 time=0.400 ms
2022-03-08 03:04:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=2 ttl=64 time=0.533 ms
2022-03-08 03:04:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=3 ttl=64 time=0.521 ms
2022-03-08 03:04:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=4 ttl=64 time=0.388 ms
2022-03-08 03:04:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=5 ttl=64 time=0.478 ms

--- 192.168.122.184 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4096ms
rtt min/avg/max/mdev = 0.388/0.464/0.533/0.060 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:04:20 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.184
root@192.168.122.184's password: 
2022-03-08 03:04:29 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:12:14 PM EST
  System load:  0.09               Processes:             136
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.184
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:02:32 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:04:38 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 03:04:44 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 03:04:50 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 03:04:55 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 03:05:01 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-08 03:05:04 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 03:05:10 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 03:05:20 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-08 03:05:29 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 03:05:38 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 03:05:47 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 346 (346.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 03:05:56 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.184 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:05:59 - test_network_sriov_stress.py - [line:470] - root - INFO - Ping two vms IP from SUT:
2022-03-08 03:06:03 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.673 ms
2022-03-08 03:06:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.291 ms
2022-03-08 03:06:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.273 ms
2022-03-08 03:06:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.271 ms
2022-03-08 03:06:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.264 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4126ms
rtt min/avg/max/mdev = 0.264/0.354/0.673/0.160 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:06:14 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.931 ms
2022-03-08 03:06:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.227 ms
2022-03-08 03:06:16 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.252 ms
2022-03-08 03:06:17 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.272 ms
2022-03-08 03:06:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.235 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4120ms
rtt min/avg/max/mdev = 0.227/0.383/0.931/0.274 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:06:21 - test_network_sriov_stress.py - [line:478] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 03:06:25 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.286 ms
2022-03-08 03:06:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.465 ms
2022-03-08 03:06:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.318 ms
2022-03-08 03:06:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.275 ms
2022-03-08 03:06:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.484 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4114ms
rtt min/avg/max/mdev = 0.275/0.365/0.484/0.092 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:06:38 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 03:06:47 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:14:31 PM EST
  System load:  0.0                Processes:             127
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:10:17 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:06:54 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.378 ms
2022-03-08 03:06:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.128 ms
2022-03-08 03:06:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.152 ms
2022-03-08 03:06:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.162 ms
2022-03-08 03:06:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.152 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4073ms
rtt min/avg/max/mdev = 0.128/0.194/0.378/0.092 ms
root@localhost:~# 
2022-03-08 03:07:38 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:07:41 - test_network_sriov_stress.py - [line:486] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 03:07:45 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.193 ms
2022-03-08 03:07:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.227 ms
2022-03-08 03:07:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.198 ms
2022-03-08 03:07:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.208 ms
2022-03-08 03:07:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.135 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4088ms
rtt min/avg/max/mdev = 0.135/0.192/0.227/0.032 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:07:55 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 03:07:57 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:08:02 - test_network_sriov_stress.py - [line:262] - root - INFO - Successfully removed VFs from PF.
2022-03-08 03:08:05 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-08 03:08:05 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-08 03:08:10 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-08 03:08:13 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-08 03:08:14 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-08 03:08:19 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-08 03:08:22 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-08 03:08:22 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-08 03:08:27 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-08 03:08:30 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-08 03:08:30 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-08 03:08:35 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-08 03:08:35 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 4 time when VF is Assigned VM guest.*************************************************************


2022-03-08 03:08:38 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-08 03:08:39 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-08 03:08:44 - test_network_sriov_stress.py - [line:108] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-08 03:08:44 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-08 03:08:44 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 4b
2022-03-08 03:08:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-08 03:08:53 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-08 03:08:56 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 03:08:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:09:01 - test_network_sriov_stress.py - [line:122] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-08 03:09:04 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-08 03:09:04 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-08 03:09:09 - test_network_sriov_stress.py - [line:136] - root - INFO - Succssfully Gotten vf_id list:

2022-03-08 03:09:12 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-08 03:09:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:09:20 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-08 03:09:21 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:09:26 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 03:09:29 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-08 03:09:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:09:34 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 03:09:34 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 03:09:37 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 03:09:38 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-08 03:09:43 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-08 03:09:46 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-08 03:09:46 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-08 03:09:51 - test_network_sriov_stress.py - [line:196] - root - INFO - Default network is active? yes

2022-03-08 03:09:55 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:123296): [1;33mWARNING[0m **: [34m03:17:42.904[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:09:58 - test_network_sriov_stress.py - [line:228] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:123296): [1;33mWARNING[0m **: [34m03:17:42.904[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:09:58 - test_network_sriov_stress.py - [line:229] - root - ERROR - Failed to create a VM: 
2022-03-08 03:10:02 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-08 03:10:03 - sshInstance.py - [line:71] - root - INFO - 
** (process:123301): [1;33mWARNING[0m **: [34m03:17:50.077[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 03:10:05 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-08 03:10:08 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest1
2022-03-08 03:10:12 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:123347): [1;33mWARNING[0m **: [34m03:17:59.758[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:10:15 - test_network_sriov_stress.py - [line:228] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:123347): [1;33mWARNING[0m **: [34m03:17:59.758[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:10:15 - test_network_sriov_stress.py - [line:229] - root - ERROR - Failed to create a VM: 
2022-03-08 03:10:19 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:123352): [1;33mWARNING[0m **: [34m03:18:06.969[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 03:10:21 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
2022-03-08 03:10:22 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-08 03:10:25 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest2
2022-03-08 03:10:28 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:10:28 - sshInstance.py - [line:50] - root - INFO - 192.168.122.65/24

2022-03-08 03:10:33 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest1 IP: 192.168.122.65/24

2022-03-08 03:10:36 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:10:36 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:10:41 - test_network_sriov_stress.py - [line:248] - root - ERROR - not found IP of VMtest2
2022-03-08 03:11:44 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:11:44 - sshInstance.py - [line:50] - root - INFO - 192.168.122.184/24

2022-03-08 03:11:49 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest2 IP: 192.168.122.184/24

2022-03-08 03:11:49 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.65
2022-03-08 03:11:49 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.184
2022-03-08 03:11:53 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.451 ms
2022-03-08 03:11:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.305 ms
2022-03-08 03:11:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.298 ms
2022-03-08 03:11:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.336 ms
2022-03-08 03:11:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.359 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4114ms
rtt min/avg/max/mdev = 0.298/0.349/0.451/0.060 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:12:06 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 03:12:15 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:20:00 PM EST
  System load:  0.0                Processes:             137
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:14:31 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:12:24 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 03:12:30 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 03:12:36 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 03:12:41 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 03:12:47 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-08 03:12:50 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 03:12:56 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 03:13:06 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-08 03:13:15 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 03:13:24 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 03:13:33 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 346 (346.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 03:13:42 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:13:49 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.184
PING 192.168.122.184 (192.168.122.184) 56(84) bytes of data.
64 bytes from 192.168.122.184: icmp_seq=1 ttl=64 time=0.272 ms
2022-03-08 03:13:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=2 ttl=64 time=0.292 ms
2022-03-08 03:13:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=3 ttl=64 time=0.449 ms
2022-03-08 03:13:52 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=4 ttl=64 time=0.472 ms
2022-03-08 03:13:53 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=5 ttl=64 time=0.484 ms

--- 192.168.122.184 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4079ms
rtt min/avg/max/mdev = 0.272/0.393/0.484/0.095 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:14:02 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.184
root@192.168.122.184's password: 
2022-03-08 03:14:11 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:21:56 PM EST
  System load:  0.0                Processes:             132
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.184
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:12:15 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:14:20 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 03:14:26 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 03:14:32 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 03:14:37 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 03:14:43 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-08 03:14:46 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 03:14:52 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 03:15:02 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-08 03:15:11 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 03:15:20 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 03:15:29 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 03:15:38 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.184 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:15:41 - test_network_sriov_stress.py - [line:470] - root - INFO - Ping two vms IP from SUT:
2022-03-08 03:15:45 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.430 ms
2022-03-08 03:15:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.248 ms
2022-03-08 03:15:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.268 ms
2022-03-08 03:15:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.285 ms
2022-03-08 03:15:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.267 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4109ms
rtt min/avg/max/mdev = 0.248/0.299/0.430/0.068 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:15:56 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.426 ms
2022-03-08 03:15:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.259 ms
2022-03-08 03:15:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.231 ms
2022-03-08 03:15:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.261 ms
2022-03-08 03:16:00 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.239 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4104ms
rtt min/avg/max/mdev = 0.231/0.283/0.426/0.073 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:16:03 - test_network_sriov_stress.py - [line:478] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 03:16:07 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.265 ms
2022-03-08 03:16:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.399 ms
2022-03-08 03:16:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.301 ms
2022-03-08 03:16:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.474 ms
2022-03-08 03:16:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.469 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.265/0.381/0.474/0.088 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:16:20 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 03:16:29 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:24:14 PM EST
  System load:  0.0                Processes:             137
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:20:00 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:16:36 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.296 ms
2022-03-08 03:16:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.202 ms
2022-03-08 03:16:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.202 ms
2022-03-08 03:16:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.175 ms
2022-03-08 03:16:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.222 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4074ms
rtt min/avg/max/mdev = 0.175/0.219/0.296/0.041 ms
root@localhost:~# 
2022-03-08 03:17:20 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:17:23 - test_network_sriov_stress.py - [line:486] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 03:17:27 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.262 ms
2022-03-08 03:17:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.249 ms
2022-03-08 03:17:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.270 ms
2022-03-08 03:17:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.229 ms
2022-03-08 03:17:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.258 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4134ms
rtt min/avg/max/mdev = 0.229/0.253/0.270/0.022 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:17:37 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 03:17:40 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:17:45 - test_network_sriov_stress.py - [line:262] - root - INFO - Successfully removed VFs from PF.
2022-03-08 03:17:48 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-08 03:17:48 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-08 03:17:53 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-08 03:17:56 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-08 03:17:56 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-08 03:18:01 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-08 03:18:04 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-08 03:18:04 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-08 03:18:09 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-08 03:18:12 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-08 03:18:12 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-08 03:18:17 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-08 03:18:17 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 5 time when VF is Assigned VM guest.*************************************************************


2022-03-08 03:18:20 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-08 03:18:21 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-08 03:18:26 - test_network_sriov_stress.py - [line:108] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-08 03:18:26 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-08 03:18:26 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 4b
2022-03-08 03:18:32 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-03-08 03:18:35 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-08 03:18:38 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 03:18:38 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:18:43 - test_network_sriov_stress.py - [line:122] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-08 03:18:46 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-08 03:18:46 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-08 03:18:51 - test_network_sriov_stress.py - [line:136] - root - INFO - Succssfully Gotten vf_id list:

2022-03-08 03:18:54 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-08 03:18:54 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:19:02 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-08 03:19:03 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:19:08 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 03:19:11 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-08 03:19:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:19:17 - test_network_sriov_stress.py - [line:169] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-08 03:19:17 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 03:19:20 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-08 03:19:20 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-08 03:19:25 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-08 03:19:28 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-08 03:19:28 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-08 03:19:33 - test_network_sriov_stress.py - [line:196] - root - INFO - Default network is active? yes

2022-03-08 03:19:37 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:124792): [1;33mWARNING[0m **: [34m03:27:24.992[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:19:40 - test_network_sriov_stress.py - [line:228] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:124792): [1;33mWARNING[0m **: [34m03:27:24.992[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:19:40 - test_network_sriov_stress.py - [line:229] - root - ERROR - Failed to create a VM: 
2022-03-08 03:19:44 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:124796): [1;33mWARNING[0m **: [34m03:27:32.058[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 03:19:46 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-08 03:19:49 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest1
2022-03-08 03:19:53 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:124845): [1;33mWARNING[0m **: [34m03:27:41.047[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:19:56 - test_network_sriov_stress.py - [line:228] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:124845): [1;33mWARNING[0m **: [34m03:27:41.047[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-08 03:19:56 - test_network_sriov_stress.py - [line:229] - root - ERROR - Failed to create a VM: 
2022-03-08 03:20:00 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:124850): [1;33mWARNING[0m **: [34m03:27:47.977[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-08 03:20:02 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-08 03:20:05 - test_network_sriov_stress.py - [line:231] - root - INFO - Successfully created a VM: VMtest2
2022-03-08 03:20:08 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:20:08 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:20:13 - test_network_sriov_stress.py - [line:248] - root - ERROR - not found IP of VMtest1
2022-03-08 03:21:16 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:21:16 - sshInstance.py - [line:50] - root - INFO - 192.168.122.65/24

2022-03-08 03:21:21 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest1 IP: 192.168.122.65/24

2022-03-08 03:21:24 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-08 03:21:24 - sshInstance.py - [line:50] - root - INFO - 192.168.122.184/24

2022-03-08 03:21:29 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully got VMtest2 IP: 192.168.122.184/24

2022-03-08 03:21:29 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.65
2022-03-08 03:21:29 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.184
2022-03-08 03:21:33 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.497 ms
2022-03-08 03:21:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.412 ms
2022-03-08 03:21:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.356 ms
2022-03-08 03:21:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.367 ms
2022-03-08 03:21:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.384 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4129ms
rtt min/avg/max/mdev = 0.356/0.403/0.497/0.052 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:21:46 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 03:21:55 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:29:40 PM EST
  System load:  0.16               Processes:             135
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:24:14 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:22:04 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 03:22:10 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 03:22:16 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 03:22:21 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 03:22:27 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-08 03:22:30 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 03:22:36 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 03:22:46 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-08 03:22:55 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 03:23:04 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 03:23:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 03:23:22 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:23:29 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.184
PING 192.168.122.184 (192.168.122.184) 56(84) bytes of data.
64 bytes from 192.168.122.184: icmp_seq=1 ttl=64 time=0.124 ms
2022-03-08 03:23:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=2 ttl=64 time=0.518 ms
2022-03-08 03:23:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=3 ttl=64 time=0.539 ms
2022-03-08 03:23:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=4 ttl=64 time=0.418 ms
2022-03-08 03:23:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.184: icmp_seq=5 ttl=64 time=0.494 ms

--- 192.168.122.184 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.124/0.418/0.539/0.154 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:23:42 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.184
root@192.168.122.184's password: 
2022-03-08 03:23:51 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:31:36 PM EST
  System load:  0.0                Processes:             145
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.184
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:21:57 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:24:00 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-08 03:24:06 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-08 03:24:12 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-08 03:24:17 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-08 03:24:23 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-03-08 03:24:26 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-08 03:24:32 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-08 03:24:42 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-08 03:24:51 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-08 03:25:00 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-08 03:25:09 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1038 (1.0 KB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-08 03:25:18 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.184 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:25:21 - test_network_sriov_stress.py - [line:470] - root - INFO - Ping two vms IP from SUT:
2022-03-08 03:25:25 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.563 ms
2022-03-08 03:25:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.296 ms
2022-03-08 03:25:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.283 ms
2022-03-08 03:25:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.300 ms
2022-03-08 03:25:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.307 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4127ms
rtt min/avg/max/mdev = 0.283/0.349/0.563/0.109 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:25:36 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.762 ms
2022-03-08 03:25:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.291 ms
2022-03-08 03:25:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.212 ms
2022-03-08 03:25:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.218 ms
2022-03-08 03:25:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.195 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4121ms
rtt min/avg/max/mdev = 0.195/0.335/0.762/0.216 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:25:43 - test_network_sriov_stress.py - [line:478] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 03:25:47 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.65
PING 192.168.122.65 (192.168.122.65) 56(84) bytes of data.
64 bytes from 192.168.122.65: icmp_seq=1 ttl=64 time=0.395 ms
2022-03-08 03:25:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=2 ttl=64 time=0.494 ms
2022-03-08 03:25:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=3 ttl=64 time=0.507 ms
2022-03-08 03:25:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=4 ttl=64 time=0.485 ms
2022-03-08 03:25:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.65: icmp_seq=5 ttl=64 time=0.340 ms

--- 192.168.122.65 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4116ms
rtt min/avg/max/mdev = 0.340/0.444/0.507/0.066 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:26:00 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.65
root@192.168.122.65's password: 
2022-03-08 03:26:09 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 07 Mar 2022 02:33:55 PM EST
  System load:  0.0                Processes:             128
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.65
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Mon Mar  7 14:29:41 2022 from 192.168.122.1
root@localhost:~# 
2022-03-08 03:26:17 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.380 ms
2022-03-08 03:26:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.356 ms
2022-03-08 03:26:19 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.330 ms
2022-03-08 03:26:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.263 ms
2022-03-08 03:26:21 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.123 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.123/0.290/0.380/0.092 ms
root@localhost:~# 
2022-03-08 03:27:01 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.65 closed.
[root@WW25ICX2 ~]# 
2022-03-08 03:27:04 - test_network_sriov_stress.py - [line:486] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-08 03:27:08 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.204 ms
2022-03-08 03:27:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.255 ms
2022-03-08 03:27:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.192 ms
2022-03-08 03:27:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.283 ms
2022-03-08 03:27:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.266 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4089ms
rtt min/avg/max/mdev = 0.192/0.240/0.283/0.035 ms
[root@WW25ICX2 ~]# 
2022-03-08 03:27:18 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 03:27:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:27:25 - test_network_sriov_stress.py - [line:262] - root - INFO - Successfully removed VFs from PF.
2022-03-08 03:27:28 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-08 03:27:28 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-08 03:27:33 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-08 03:27:36 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-08 03:27:36 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-08 03:27:41 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-08 03:27:44 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-08 03:27:44 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-08 03:27:49 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-08 03:27:52 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-08 03:27:52 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-08 03:27:57 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
.2022-03-08 03:28:00 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-08 03:28:01 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest2'


2022-03-08 03:28:06 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-08 03:28:09 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-08 03:28:09 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest2'


2022-03-08 03:28:14 - test_network_sriov_stress.py - [line:290] - root - ERROR - Failed to removed the VM VMtest2
2022-03-08 03:28:17 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-08 03:28:17 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest1'


2022-03-08 03:28:22 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-08 03:28:25 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-08 03:28:25 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest1'


2022-03-08 03:28:30 - test_network_sriov_stress.py - [line:290] - root - ERROR - Failed to removed the VM VMtest1
2022-03-08 03:28:33 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-08 03:28:33 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:28:41 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 0
2022-03-08 03:28:41 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:28:49 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-08 03:28:49 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:28:54 - test_network_sriov_stress.py - [line:79] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-08 03:28:54 - test_network_sriov_stress.py - [line:81] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-08/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]_02_38_44
2022-03-08 03:28:57 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-08 03:28:57 - sshInstance.py - [line:50] - root - INFO - 
2022-03-08 03:29:02 - test_network_sriov_stress.py - [line:83] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-08 03:29:02 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-08 03:29:02 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
                  [100%]

=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:62
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:62: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:101
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:101: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:71
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:71: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:381
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:381: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:498
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:498: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:797
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:797: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:78
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:78: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:102
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:102: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:124
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:124: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:188
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:188: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:212
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:212: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html -
========== 1 passed, 15 deselected, 12 warnings in 3018.39s (0:50:18) ==========
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
[8mha:////4LN/0LMxu1hyybTBeE6CHwDx82bv/lkvxFk3cdgHTSuWAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMPkEZb3/VO3favo5XL4AAAA=[0m[Pipeline] sh
+ sed -i $'s/\r//g' /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4FgvIflgycWoJq7MsZycbV9d7HENRG2WSX14oF+Me/GuAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiAR2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwZyt32U/vwBq1seBO+AAAA[0m[Pipeline] sh
+ chmod a+x /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4P37N80+NRbzyFlga2j1WDon6H/4VmnQwrRysqQpQX/3AAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigagQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUO62n9qHN+xdYwq+AAAA[0m[Pipeline] sh
+ sh /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
/root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh: line 7: [: too many arguments
[8mha:////4P3ih/vRXCzaXCkS1CQDBQXrb3I4EZcCr0NGGH+tKlR4AAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigUSDqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFDu9p/avgEjVhSLvgAAAA==[0m[Pipeline] }
[8mha:////4ISV0Ptmba0km8a80Gq+UClogdZnPDxCJXroOoeI5sULAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiREGBqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFDu9p/avgE81EHZvgAAAA==[0m[Pipeline] // stage
[8mha:////4LmA5LOJ1yGOO5YQ6RYn+/szIsYEkfxAArsUKSFs0Xa0AAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIpoEBCVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Nu9INt9AE/B/a+9AAAA[0m[Pipeline] }
[8mha:////4KVKO0UZMawo8C9tjXN4L1+ryWbU4zmvD2sDlsKoyYtXAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUVI5jZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0gL/eCrPwAXH35DL0AAAA=[0m[Pipeline] // node
[8mha:////4A8vvhfR6oegt+2XAbvn3Z0Fx6j3lb1QUh2abilCs+OGAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMJBiA5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBAx/ra70AAAA=[0m[Pipeline] End of Pipeline
Finished: SUCCESS
